// ============================================================================
// Phase 1 — Event Ontology System
// Standardized vocabulary of 180+ event types across 18 categories.
// All evidence sources convert into this vocabulary before analysis.
// ============================================================================

import type { EventTypeDefinition, EventCategory } from './types.ts';

// ---------------------------------------------------------------------------
// Event Type Registry — 180+ event types
// ---------------------------------------------------------------------------

export const EVENT_TYPE_REGISTRY: EventTypeDefinition[] = [
  // =========================================================================
  // DETENTION (20 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_DETAINS_PERSON',
    category: 'detention',
    eventName: 'Officer Detains Person',
    description: 'Officer initiates a detention by restricting a person\'s freedom of movement.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_DETE_001', 'POSTLD15_DETE_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ORDERS_STOP',
    category: 'detention',
    eventName: 'Officer Orders Stop',
    description: 'Officer gives verbal command to stop or remain in place.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_DETE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_HANDCUFFS_SUSPECT',
    category: 'detention',
    eventName: 'Officer Handcuffs Suspect',
    description: 'Officer applies handcuffs or restraints to a person during detention or arrest.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'handcuffs'],
    relatedDoctrineRules: ['POSTLD15_DETE_006'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_REQUESTS_ID',
    category: 'detention',
    eventName: 'Officer Requests Identification',
    description: 'Officer asks a person to identify themselves during a stop.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'identification_card'],
    relatedDoctrineRules: ['POSTLD15_DETE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_EXTENDS_DETENTION',
    category: 'detention',
    eventName: 'Officer Extends Detention',
    description: 'Duration of detention is extended beyond the initial purpose.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_DETE_003'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ARTICULATES_SUSPICION',
    category: 'detention',
    eventName: 'Officer Articulates Reasonable Suspicion',
    description: 'Officer states or documents the basis for reasonable suspicion.',
    actorTypes: ['officer'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD15_DETE_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_DETAINED_IN_PATROL_CAR',
    category: 'detention',
    eventName: 'Person Detained in Patrol Car',
    description: 'Detained person is placed inside a patrol vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'vehicle'],
    relatedDoctrineRules: ['POSTLD15_DETE_006'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_FIELD_INTERVIEW',
    category: 'detention',
    eventName: 'Officer Conducts Field Interview',
    description: 'Officer questions a detained person in the field.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_DETE_001', 'POSTLD15_ENCO_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_INITIATES_TRAFFIC_STOP',
    category: 'detention',
    eventName: 'Officer Initiates Traffic Stop',
    description: 'Officer activates lights/siren to stop a vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD15_DETE_001', 'POSTLD21_PATR_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_RELEASES_DETAINEE',
    category: 'detention',
    eventName: 'Officer Releases Detainee',
    description: 'Officer ends the detention and allows person to leave.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ORDERS_EXIT_VEHICLE',
    category: 'detention',
    eventName: 'Officer Orders Exit from Vehicle',
    description: 'Officer commands occupants to exit a vehicle during a stop.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'vehicle'],
    relatedDoctrineRules: ['POSTLD15_DETE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ORDERS_PRONE_POSITION',
    category: 'detention',
    eventName: 'Officer Orders Prone Position',
    description: 'Officer commands person to lie face-down on the ground.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_DETE_006', 'POSTLD20_FORC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ORDERS_HANDS_UP',
    category: 'detention',
    eventName: 'Officer Orders Hands Up',
    description: 'Officer commands person to raise their hands or show hands.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_SHOWUP',
    category: 'detention',
    eventName: 'Officer Conducts Show-Up Identification',
    description: 'Officer presents suspect to witness for field identification.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_DETE_005'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PATS_DOWN_PERSON',
    category: 'detention',
    eventName: 'Officer Pats Down Person',
    description: 'Officer conducts a protective pat-down frisk during detention.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_SEAR_006', 'POSTLD15_SEAR_007'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CHECKS_WARRANTS',
    category: 'detention',
    eventName: 'Officer Checks for Warrants',
    description: 'Officer runs warrant check on detained person through dispatch.',
    actorTypes: ['officer', 'dispatcher'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DETAINS_MULTIPLE',
    category: 'detention',
    eventName: 'Officer Detains Multiple Persons',
    description: 'Officer detains more than one person simultaneously.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_DETE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_COMPLIES_WITH_DETENTION',
    category: 'detention',
    eventName: 'Suspect Complies with Detention',
    description: 'Detained person cooperates with officer commands.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_CHALLENGES_DETENTION',
    category: 'detention',
    eventName: 'Suspect Verbally Challenges Detention',
    description: 'Detained person verbally questions the legality or basis of the detention.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD15_ENCO_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEPARATES_INDIVIDUALS',
    category: 'detention',
    eventName: 'Officer Separates Individuals',
    description: 'Officer physically separates detained individuals for questioning.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // SEARCH (22 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_SEARCHES_VEHICLE',
    category: 'search',
    eventName: 'Officer Searches Vehicle',
    description: 'Officer conducts a search of a vehicle\'s interior, trunk, or compartments.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD16_SEAR_001', 'POSTLD16_SEAR_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_PERSON',
    category: 'search',
    eventName: 'Officer Searches Person',
    description: 'Officer conducts a full search of a person\'s body and clothing.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD16_SEAR_001', 'POSTLD15_SEAR_006'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_REQUESTS_CONSENT_SEARCH',
    category: 'search',
    eventName: 'Officer Requests Consent to Search',
    description: 'Officer asks for verbal or written consent to conduct a search.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD16_CONS_001', 'POSTLD16_CONS_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_GRANTS_CONSENT',
    category: 'search',
    eventName: 'Person Grants Consent to Search',
    description: 'Person provides verbal or written consent for a search.',
    actorTypes: ['suspect', 'witness'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD16_CONS_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_DENIES_CONSENT',
    category: 'search',
    eventName: 'Person Denies Consent to Search',
    description: 'Person refuses consent for a search.',
    actorTypes: ['suspect', 'witness'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD16_CONS_001', 'POSTLD16_CONS_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_REVOKES_CONSENT',
    category: 'search',
    eventName: 'Person Revokes Consent',
    description: 'Person withdraws previously granted consent during a search.',
    actorTypes: ['suspect', 'witness'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD16_CONS_003'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_CONTAINER',
    category: 'search',
    eventName: 'Officer Searches Container',
    description: 'Officer searches a bag, backpack, purse, or other container.',
    actorTypes: ['officer'],
    objectTypes: ['container'],
    relatedDoctrineRules: ['POSTLD16_SEAR_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_BUILDING',
    category: 'search',
    eventName: 'Officer Searches Building',
    description: 'Officer conducts a search of a building or residence.',
    actorTypes: ['officer'],
    objectTypes: ['building'],
    relatedDoctrineRules: ['POSTLD16_WARR_001', 'POSTLD16_WARR_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_EXECUTES_WARRANT',
    category: 'search',
    eventName: 'Officer Executes Search Warrant',
    description: 'Officer executes a judicially authorized search warrant.',
    actorTypes: ['officer'],
    objectTypes: ['building', 'vehicle', 'person'],
    relatedDoctrineRules: ['POSTLD16_WARR_001', 'POSTLD16_WARR_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_PHONE',
    category: 'search',
    eventName: 'Officer Searches Electronic Device',
    description: 'Officer accesses or searches a phone or electronic device.',
    actorTypes: ['officer'],
    objectTypes: ['phone', 'electronic_device'],
    relatedDoctrineRules: ['POSTLD16_ELEC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_INVENTORY_SEARCH',
    category: 'search',
    eventName: 'Officer Conducts Inventory Search',
    description: 'Officer performs an inventory search of impounded vehicle or property.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle', 'container'],
    relatedDoctrineRules: ['POSTLD16_INVE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_INCIDENT_TO_ARREST',
    category: 'search',
    eventName: 'Officer Searches Incident to Arrest',
    description: 'Officer conducts search of person incident to a lawful arrest.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD16_INCI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_OBSERVES_PLAIN_VIEW',
    category: 'search',
    eventName: 'Officer Observes Item in Plain View',
    description: 'Officer sees contraband or evidence in plain view without searching.',
    actorTypes: ['officer'],
    objectTypes: ['contraband', 'weapon', 'narcotics'],
    relatedDoctrineRules: ['POSTLD16_PLAI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_PROTECTIVE_SWEEP',
    category: 'search',
    eventName: 'Officer Conducts Protective Sweep',
    description: 'Officer conducts a quick sweep of premises for safety.',
    actorTypes: ['officer'],
    objectTypes: ['building'],
    relatedDoctrineRules: ['POSTLD16_PROT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_STRIP_SEARCH',
    category: 'search',
    eventName: 'Officer Conducts Strip Search',
    description: 'Officer conducts a strip search in controlled environment.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD16_STRI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_K9_SNIFF',
    category: 'search',
    eventName: 'Officer Uses K-9 for Sniff Search',
    description: 'K-9 unit performs an exterior sniff of vehicle or property.',
    actorTypes: ['k9_handler'],
    objectTypes: ['vehicle', 'container', 'k9'],
    relatedDoctrineRules: ['POSTLD16_K9_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'K9_ALERTS_ON_TARGET',
    category: 'search',
    eventName: 'K-9 Alerts on Target',
    description: 'K-9 indicates positive alert on vehicle or object.',
    actorTypes: ['k9_handler'],
    objectTypes: ['vehicle', 'container', 'k9'],
    relatedDoctrineRules: ['POSTLD16_K9_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_TRUNK',
    category: 'search',
    eventName: 'Officer Searches Vehicle Trunk',
    description: 'Officer specifically searches the trunk compartment of a vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD16_SEAR_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_GLOVE_BOX',
    category: 'search',
    eventName: 'Officer Searches Glove Compartment',
    description: 'Officer searches glove box or center console of vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD16_SEAR_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ENTERS_CURTILAGE',
    category: 'search',
    eventName: 'Officer Enters Curtilage',
    description: 'Officer enters the curtilage (area surrounding a home) without warrant.',
    actorTypes: ['officer'],
    objectTypes: ['building', 'area'],
    relatedDoctrineRules: ['POSTLD16_CURT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_TECHNOLOGY_SEARCH',
    category: 'search',
    eventName: 'Officer Uses Technology for Search',
    description: 'Officer uses thermal imaging, GPS tracker, or other technology.',
    actorTypes: ['officer'],
    objectTypes: ['electronic_device'],
    relatedDoctrineRules: ['POSTLD16_TECH_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_AUTOMOBILE_EXCEPTION',
    category: 'search',
    eventName: 'Officer Searches Vehicle Under Automobile Exception',
    description: 'Officer searches vehicle based on probable cause without a warrant.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD16_AUTO_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // SEIZURE (12 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_SEIZES_CONTRABAND',
    category: 'seizure',
    eventName: 'Officer Seizes Contraband',
    description: 'Officer seizes illegal items found during search or in plain view.',
    actorTypes: ['officer'],
    objectTypes: ['contraband', 'narcotics'],
    relatedDoctrineRules: ['POSTLD16_SEIZ_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEIZES_WEAPON',
    category: 'seizure',
    eventName: 'Officer Seizes Weapon',
    description: 'Officer confiscates a weapon from a person or location.',
    actorTypes: ['officer'],
    objectTypes: ['weapon', 'firearm'],
    relatedDoctrineRules: ['POSTLD16_SEIZ_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEIZES_VEHICLE',
    category: 'seizure',
    eventName: 'Officer Seizes Vehicle',
    description: 'Officer impounds or seizes a vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD16_SEIZ_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEIZES_ELECTRONIC_DEVICE',
    category: 'seizure',
    eventName: 'Officer Seizes Electronic Device',
    description: 'Officer confiscates a phone, computer, or other electronic device.',
    actorTypes: ['officer'],
    objectTypes: ['phone', 'electronic_device'],
    relatedDoctrineRules: ['POSTLD16_ELEC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEIZES_CURRENCY',
    category: 'seizure',
    eventName: 'Officer Seizes Currency',
    description: 'Officer confiscates money or currency.',
    actorTypes: ['officer'],
    objectTypes: ['currency'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEIZES_DOCUMENTS',
    category: 'seizure',
    eventName: 'Officer Seizes Documents',
    description: 'Officer confiscates papers, IDs, or other documents.',
    actorTypes: ['officer'],
    objectTypes: ['document', 'identification_card'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_IMPOUNDS_VEHICLE',
    category: 'seizure',
    eventName: 'Officer Impounds Vehicle',
    description: 'Officer arranges for vehicle to be towed and impounded.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_TAGS_EVIDENCE',
    category: 'seizure',
    eventName: 'Officer Tags Evidence',
    description: 'Officer labels and tags seized items as evidence.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_EVID_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PHOTOGRAPHS_EVIDENCE',
    category: 'seizure',
    eventName: 'Officer Photographs Evidence',
    description: 'Officer photographs seized evidence before collection.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD30_PHOT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_RETURNS_PROPERTY',
    category: 'seizure',
    eventName: 'Officer Returns Property',
    description: 'Officer returns seized property to owner.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_ITEM_COLLECTED',
    category: 'seizure',
    eventName: 'Evidence Item Collected',
    description: 'Physical evidence is collected and bagged at the scene.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_EVID_001', 'POSTLD24_EVID_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_TRANSFERRED',
    category: 'seizure',
    eventName: 'Evidence Transferred Between Personnel',
    description: 'Evidence item changes custody from one person to another.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_CHAI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // FORCE (22 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_DRAWS_WEAPON',
    category: 'force',
    eventName: 'Officer Draws Weapon',
    description: 'Officer unholsters and points a firearm.',
    actorTypes: ['officer'],
    objectTypes: ['firearm'],
    relatedDoctrineRules: ['POSTLD20_FORC_001', 'POSTLD20_FORC_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_FIRES_WEAPON',
    category: 'force',
    eventName: 'Officer Fires Weapon',
    description: 'Officer discharges a firearm.',
    actorTypes: ['officer'],
    objectTypes: ['firearm'],
    relatedDoctrineRules: ['POSTLD20_DEAD_001', 'POSTLD20_FORC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DEPLOYS_TASER',
    category: 'force',
    eventName: 'Officer Deploys Taser',
    description: 'Officer uses a conducted energy device (Taser/CEW).',
    actorTypes: ['officer'],
    objectTypes: ['taser'],
    relatedDoctrineRules: ['POSTLD20_LESS_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_BATON',
    category: 'force',
    eventName: 'Officer Uses Baton',
    description: 'Officer strikes with an impact weapon.',
    actorTypes: ['officer'],
    objectTypes: ['baton'],
    relatedDoctrineRules: ['POSTLD20_IMPA_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DEPLOYS_OC_SPRAY',
    category: 'force',
    eventName: 'Officer Deploys OC Spray',
    description: 'Officer uses oleoresin capsicum (pepper spray).',
    actorTypes: ['officer'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD20_LESS_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_PHYSICAL_FORCE',
    category: 'force',
    eventName: 'Officer Uses Physical Force',
    description: 'Officer uses hands, body, or physical techniques to control.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_FORC_001', 'POSTLD20_CONT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_TAKES_DOWN_PERSON',
    category: 'force',
    eventName: 'Officer Takes Down Person',
    description: 'Officer physically brings person to the ground.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_CONT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_APPLIES_CAROTID_RESTRAINT',
    category: 'force',
    eventName: 'Officer Applies Neck Restraint',
    description: 'Officer applies carotid or neck restraint hold.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_NECK_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DEPLOYS_LESS_LETHAL',
    category: 'force',
    eventName: 'Officer Deploys Less-Lethal Munitions',
    description: 'Officer uses beanbag rounds, rubber bullets, or similar.',
    actorTypes: ['officer'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD20_LESS_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_K9_FORCE',
    category: 'force',
    eventName: 'Officer Deploys K-9 for Apprehension',
    description: 'K-9 is deployed to bite or apprehend a suspect.',
    actorTypes: ['k9_handler'],
    objectTypes: ['k9', 'person'],
    relatedDoctrineRules: ['POSTLD20_K9F_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_VEHICLE_FORCE',
    category: 'force',
    eventName: 'Officer Uses Vehicle as Force',
    description: 'Officer uses patrol vehicle to stop or immobilize suspect vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD20_VEHI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_WARNS_FORCE',
    category: 'force',
    eventName: 'Officer Gives Force Warning',
    description: 'Officer verbally warns that force will be used if not compliant.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_WARN_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DEESCALATES',
    category: 'force',
    eventName: 'Officer Attempts De-escalation',
    description: 'Officer uses verbal commands or tactics to reduce tension.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_DEES_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_RESISTS_ACTIVELY',
    category: 'force',
    eventName: 'Suspect Actively Resists',
    description: 'Suspect physically resists officer control.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD20_FORC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_RESISTS_PASSIVELY',
    category: 'force',
    eventName: 'Suspect Passively Resists',
    description: 'Suspect refuses to comply but does not physically resist.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD20_FORC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_ASSAULTS_OFFICER',
    category: 'force',
    eventName: 'Suspect Assaults Officer',
    description: 'Suspect physically attacks or strikes an officer.',
    actorTypes: ['suspect'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_FORC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_DISPLAYS_WEAPON',
    category: 'force',
    eventName: 'Suspect Displays Weapon',
    description: 'Suspect brandishes or reveals a weapon.',
    actorTypes: ['suspect'],
    objectTypes: ['weapon', 'firearm'],
    relatedDoctrineRules: ['POSTLD20_DEAD_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_REPORTS_FORCE_USED',
    category: 'force',
    eventName: 'Officer Reports Force Used',
    description: 'Officer documents force used in report or to supervisor.',
    actorTypes: ['officer'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD20_REPO_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUPERVISOR_RESPONDS_FORCE',
    category: 'force',
    eventName: 'Supervisor Responds to Force Incident',
    description: 'Supervising officer responds to scene after force is used.',
    actorTypes: ['supervisor'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD20_REPO_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_INJURED_BY_FORCE',
    category: 'force',
    eventName: 'Person Injured by Force',
    description: 'Person sustains injury as a result of force application.',
    actorTypes: ['suspect', 'officer', 'bystander'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_MEDI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PROVIDES_MEDICAL_AID',
    category: 'force',
    eventName: 'Officer Provides Medical Aid',
    description: 'Officer renders or summons medical assistance after force.',
    actorTypes: ['officer', 'ems'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_MEDI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_HOLSTERS_WEAPON',
    category: 'force',
    eventName: 'Officer Holsters Weapon',
    description: 'Officer returns firearm to holster.',
    actorTypes: ['officer'],
    objectTypes: ['firearm'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // MOVEMENT (16 types)
  // =========================================================================
  {
    eventTypeId: 'SUSPECT_RUNS',
    category: 'movement',
    eventName: 'Suspect Runs',
    description: 'Suspect flees on foot from officers.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD21_PURS_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_ENTERS_VEHICLE',
    category: 'movement',
    eventName: 'Suspect Enters Vehicle',
    description: 'Suspect gets into a vehicle.',
    actorTypes: ['suspect'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_EXITS_VEHICLE',
    category: 'movement',
    eventName: 'Suspect Exits Vehicle',
    description: 'Suspect gets out of a vehicle.',
    actorTypes: ['suspect'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_FLEES_IN_VEHICLE',
    category: 'movement',
    eventName: 'Suspect Flees in Vehicle',
    description: 'Suspect drives away from officers.',
    actorTypes: ['suspect'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD21_PURS_001', 'POSTLD21_PURS_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PURSUES_ON_FOOT',
    category: 'movement',
    eventName: 'Officer Pursues on Foot',
    description: 'Officer chases suspect on foot.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD21_PURS_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PURSUES_IN_VEHICLE',
    category: 'movement',
    eventName: 'Officer Pursues in Vehicle',
    description: 'Officer engages in vehicle pursuit.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD21_PURS_002', 'POSTLD21_PURS_003'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ARRIVES_AT_SCENE',
    category: 'movement',
    eventName: 'Officer Arrives at Scene',
    description: 'Officer arrives at the incident location.',
    actorTypes: ['officer'],
    objectTypes: ['area'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DEPARTS_SCENE',
    category: 'movement',
    eventName: 'Officer Departs Scene',
    description: 'Officer leaves the incident location.',
    actorTypes: ['officer'],
    objectTypes: ['area'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_ENTERS_BUILDING',
    category: 'movement',
    eventName: 'Suspect Enters Building',
    description: 'Suspect enters a structure or building.',
    actorTypes: ['suspect'],
    objectTypes: ['building'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_EXITS_BUILDING',
    category: 'movement',
    eventName: 'Suspect Exits Building',
    description: 'Suspect leaves a structure or building.',
    actorTypes: ['suspect'],
    objectTypes: ['building'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_APPROACHES_VEHICLE',
    category: 'movement',
    eventName: 'Officer Approaches Vehicle',
    description: 'Officer walks up to a stopped vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD21_PATR_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_APPROACHES_PERSON',
    category: 'movement',
    eventName: 'Officer Approaches Person',
    description: 'Officer walks toward a person for contact.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_ENCO_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_WALKS_AWAY',
    category: 'movement',
    eventName: 'Suspect Walks Away',
    description: 'Suspect walks away from officer contact.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD15_ENCO_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_MOVES_HANDS_TO_WAISTBAND',
    category: 'movement',
    eventName: 'Person Moves Hands to Waistband',
    description: 'Person reaches toward waistband area.',
    actorTypes: ['suspect'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_TERMINATES_PURSUIT',
    category: 'movement',
    eventName: 'Officer Terminates Pursuit',
    description: 'Officer ends a vehicle or foot pursuit.',
    actorTypes: ['officer'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD21_PURS_003'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'BACKUP_UNIT_ARRIVES',
    category: 'movement',
    eventName: 'Backup Unit Arrives',
    description: 'Additional officers arrive at the scene.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // COMMUNICATION (18 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_REQUESTS_BACKUP',
    category: 'communication',
    eventName: 'Officer Requests Backup',
    description: 'Officer radios for additional units.',
    actorTypes: ['officer'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONTACTS_DISPATCH',
    category: 'communication',
    eventName: 'Officer Contacts Dispatch',
    description: 'Officer communicates with dispatch center.',
    actorTypes: ['officer'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'DISPATCH_SENDS_CALL',
    category: 'communication',
    eventName: 'Dispatch Sends Call',
    description: 'Dispatch assigns a call to officer units.',
    actorTypes: ['dispatcher'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_READS_MIRANDA',
    category: 'communication',
    eventName: 'Officer Reads Miranda Rights',
    description: 'Officer administers Miranda warnings to a person.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_MIRA_001', 'POSTLD15_MIRA_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_INVOKES_RIGHTS',
    category: 'communication',
    eventName: 'Suspect Invokes Rights',
    description: 'Suspect invokes right to remain silent or right to attorney.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD15_MIRA_003', 'POSTLD15_MIRA_004'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_WAIVES_RIGHTS',
    category: 'communication',
    eventName: 'Suspect Waives Miranda Rights',
    description: 'Suspect waives right to silence and agrees to speak.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD15_MIRA_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_INTERROGATES_SUSPECT',
    category: 'communication',
    eventName: 'Officer Interrogates Suspect',
    description: 'Officer conducts custodial interrogation.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_MIRA_001', 'POSTLD15_INTE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_INTERVIEWS_WITNESS',
    category: 'communication',
    eventName: 'Officer Interviews Witness',
    description: 'Officer takes a statement from a witness.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'WITNESS_PROVIDES_STATEMENT',
    category: 'communication',
    eventName: 'Witness Provides Statement',
    description: 'Witness gives verbal or written statement about events.',
    actorTypes: ['witness'],
    objectTypes: ['document'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_GIVES_VERBAL_COMMANDS',
    category: 'communication',
    eventName: 'Officer Gives Verbal Commands',
    description: 'Officer issues direct verbal orders to a person.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONTACTS_SUPERVISOR',
    category: 'communication',
    eventName: 'Officer Contacts Supervisor',
    description: 'Officer communicates with supervising officer.',
    actorTypes: ['officer'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_NOTIFIES_FAMILY',
    category: 'communication',
    eventName: 'Officer Notifies Family Member',
    description: 'Officer contacts family member of arrested or injured person.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_MAKES_SPONTANEOUS_STATEMENT',
    category: 'communication',
    eventName: 'Suspect Makes Spontaneous Statement',
    description: 'Suspect voluntarily makes a statement without questioning.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD15_MIRA_005'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_REQUESTS_ATTORNEY',
    category: 'communication',
    eventName: 'Suspect Requests Attorney',
    description: 'Suspect explicitly asks for legal representation.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD15_MIRA_004'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONTINUES_QUESTIONING_AFTER_INVOCATION',
    category: 'communication',
    eventName: 'Officer Continues Questioning After Rights Invocation',
    description: 'Officer asks questions after suspect invoked Miranda rights.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_MIRA_003', 'POSTLD15_MIRA_004'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CALLS_EMS',
    category: 'communication',
    eventName: 'Officer Calls EMS',
    description: 'Officer requests emergency medical services.',
    actorTypes: ['officer'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'DISPATCH_LOGS_EVENT',
    category: 'communication',
    eventName: 'Dispatch Logs Event',
    description: 'Dispatcher records a timestamped event in the CAD system.',
    actorTypes: ['dispatcher'],
    objectTypes: ['none'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PROVIDES_BADGE_NUMBER',
    category: 'communication',
    eventName: 'Officer Provides Badge Number',
    description: 'Officer identifies themselves with badge number to civilian.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // EVIDENCE_HANDLING (16 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_COLLECTS_EVIDENCE',
    category: 'evidence_handling',
    eventName: 'Officer Collects Evidence',
    description: 'Officer gathers and preserves physical evidence.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_EVID_001', 'POSTLD24_EVID_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PACKAGES_EVIDENCE',
    category: 'evidence_handling',
    eventName: 'Officer Packages Evidence',
    description: 'Officer places evidence in proper containers for transport.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_PACK_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_TRANSPORTS_EVIDENCE',
    category: 'evidence_handling',
    eventName: 'Officer Transports Evidence',
    description: 'Officer moves evidence from scene to storage facility.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_TRAN_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_LOGGED_INTO_STORAGE',
    category: 'evidence_handling',
    eventName: 'Evidence Logged into Storage',
    description: 'Evidence is checked into the evidence storage facility.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_STOR_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_CHECKED_OUT',
    category: 'evidence_handling',
    eventName: 'Evidence Checked Out',
    description: 'Evidence is retrieved from storage for examination.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_CHAI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_SUBMITTED_TO_LAB',
    category: 'evidence_handling',
    eventName: 'Evidence Submitted to Lab',
    description: 'Evidence is sent to forensic laboratory for analysis.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_LAB_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_CONTAMINATED',
    category: 'evidence_handling',
    eventName: 'Evidence Potentially Contaminated',
    description: 'Evidence may have been compromised or contaminated.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_CONT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'CHAIN_OF_CUSTODY_BREAK',
    category: 'evidence_handling',
    eventName: 'Chain of Custody Break',
    description: 'Gap or discrepancy in the evidence chain of custody.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_CHAI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_MARKS_EVIDENCE_LOCATION',
    category: 'evidence_handling',
    eventName: 'Officer Marks Evidence Location',
    description: 'Officer places markers at evidence locations on scene.',
    actorTypes: ['officer'],
    objectTypes: ['area'],
    relatedDoctrineRules: ['POSTLD30_MARK_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_TAKES_MEASUREMENTS',
    category: 'evidence_handling',
    eventName: 'Officer Takes Measurements',
    description: 'Officer measures distances at scene for documentation.',
    actorTypes: ['officer'],
    objectTypes: ['area'],
    relatedDoctrineRules: ['POSTLD30_MEAS_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_COLLECTS_DNA',
    category: 'evidence_handling',
    eventName: 'Officer Collects DNA Sample',
    description: 'Officer collects biological material for DNA analysis.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_DNA_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_COLLECTS_FINGERPRINTS',
    category: 'evidence_handling',
    eventName: 'Officer Collects Fingerprints',
    description: 'Officer lifts fingerprints from surfaces.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_FING_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_DESTROYED',
    category: 'evidence_handling',
    eventName: 'Evidence Destroyed',
    description: 'Evidence item is destroyed or disposed of.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'EVIDENCE_MISSING',
    category: 'evidence_handling',
    eventName: 'Evidence Reported Missing',
    description: 'Evidence item cannot be located in storage system.',
    actorTypes: ['officer'],
    objectTypes: ['evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_CHAI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PROCESSES_NARCOTICS',
    category: 'evidence_handling',
    eventName: 'Officer Processes Narcotics Evidence',
    description: 'Officer conducts field test or weighs narcotics.',
    actorTypes: ['officer'],
    objectTypes: ['narcotics', 'evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_NARC_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PROCESSES_FIREARM_EVIDENCE',
    category: 'evidence_handling',
    eventName: 'Officer Processes Firearm Evidence',
    description: 'Officer safely unloads and documents a recovered firearm.',
    actorTypes: ['officer'],
    objectTypes: ['firearm', 'evidence_bag'],
    relatedDoctrineRules: ['POSTLD24_FIRE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // VEHICLE_OPERATION (10 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_ACTIVATES_LIGHTS',
    category: 'vehicle_operation',
    eventName: 'Officer Activates Emergency Lights',
    description: 'Officer activates overhead lights on patrol vehicle.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD21_PATR_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ACTIVATES_SIREN',
    category: 'vehicle_operation',
    eventName: 'Officer Activates Siren',
    description: 'Officer activates audible siren.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_POSITIONS_VEHICLE',
    category: 'vehicle_operation',
    eventName: 'Officer Positions Vehicle',
    description: 'Officer positions patrol vehicle for tactical advantage or safety.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD21_PATR_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_SPOTLIGHT',
    category: 'vehicle_operation',
    eventName: 'Officer Uses Spotlight',
    description: 'Officer uses vehicle spotlight to illuminate scene or person.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_USES_PA_SYSTEM',
    category: 'vehicle_operation',
    eventName: 'Officer Uses PA System',
    description: 'Officer uses vehicle public address system to give commands.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PERFORMS_PIT_MANEUVER',
    category: 'vehicle_operation',
    eventName: 'Officer Performs PIT Maneuver',
    description: 'Officer executes a Pursuit Intervention Technique.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD21_PIT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DEPLOYS_SPIKE_STRIP',
    category: 'vehicle_operation',
    eventName: 'Officer Deploys Spike Strip',
    description: 'Officer deploys tire deflation device.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: ['POSTLD21_SPIK_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'VEHICLE_COLLISION_OCCURS',
    category: 'vehicle_operation',
    eventName: 'Vehicle Collision Occurs',
    description: 'Vehicle crash occurs during incident or pursuit.',
    actorTypes: ['officer', 'suspect'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ACTIVATES_DASHCAM',
    category: 'vehicle_operation',
    eventName: 'Officer Activates Dashcam',
    description: 'Officer activates or verifies dashcam recording.',
    actorTypes: ['officer'],
    objectTypes: ['dashcam'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_BLOCKS_VEHICLE',
    category: 'vehicle_operation',
    eventName: 'Officer Blocks Vehicle with Patrol Car',
    description: 'Officer uses patrol vehicle to block suspect vehicle movement.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // SCENE_CONTROL (12 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_ESTABLISHES_PERIMETER',
    category: 'scene_control',
    eventName: 'Officer Establishes Perimeter',
    description: 'Officer sets up a perimeter around incident scene.',
    actorTypes: ['officer'],
    objectTypes: ['area'],
    relatedDoctrineRules: ['POSTLD30_PERI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SECURES_CRIME_SCENE',
    category: 'scene_control',
    eventName: 'Officer Secures Crime Scene',
    description: 'Officer tapes off and secures a crime scene.',
    actorTypes: ['officer'],
    objectTypes: ['area'],
    relatedDoctrineRules: ['POSTLD30_SECU_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CREATES_CRIME_SCENE_LOG',
    category: 'scene_control',
    eventName: 'Officer Creates Crime Scene Log',
    description: 'Officer begins logging all personnel entering and exiting scene.',
    actorTypes: ['officer'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD30_LOG_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_PHOTOGRAPHS_SCENE',
    category: 'scene_control',
    eventName: 'Officer Photographs Scene',
    description: 'Officer takes photographs of the crime scene.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['area'],
    relatedDoctrineRules: ['POSTLD30_PHOT_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SKETCHES_SCENE',
    category: 'scene_control',
    eventName: 'Officer Sketches Scene',
    description: 'Officer creates a hand-drawn or digital diagram of the scene.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD30_SKET_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'DETECTIVE_ASSUMES_SCENE',
    category: 'scene_control',
    eventName: 'Detective Assumes Control of Scene',
    description: 'Investigative detective takes over scene management.',
    actorTypes: ['detective'],
    objectTypes: ['area'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_EVACUATES_AREA',
    category: 'scene_control',
    eventName: 'Officer Evacuates Area',
    description: 'Officer directs civilians to leave an area.',
    actorTypes: ['officer'],
    objectTypes: ['area', 'person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'UNAUTHORIZED_PERSON_ENTERS_SCENE',
    category: 'scene_control',
    eventName: 'Unauthorized Person Enters Crime Scene',
    description: 'Non-authorized individual enters secured crime scene.',
    actorTypes: ['bystander'],
    objectTypes: ['area'],
    relatedDoctrineRules: ['POSTLD30_SECU_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_RELEASES_SCENE',
    category: 'scene_control',
    eventName: 'Officer Releases Crime Scene',
    description: 'Scene is processed and released from police control.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['area'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ESTABLISHES_COMMAND_POST',
    category: 'scene_control',
    eventName: 'Officer Establishes Command Post',
    description: 'Officer sets up incident command post.',
    actorTypes: ['officer', 'supervisor'],
    objectTypes: ['area'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'CORONER_ARRIVES',
    category: 'scene_control',
    eventName: 'Coroner Arrives at Scene',
    description: 'Coroner or medical examiner arrives at death scene.',
    actorTypes: ['ems'],
    objectTypes: ['area'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'CRIME_LAB_ARRIVES',
    category: 'scene_control',
    eventName: 'Crime Lab Technician Arrives',
    description: 'Forensic technician arrives at scene for processing.',
    actorTypes: ['detective'],
    objectTypes: ['area'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // ARREST (14 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_ARRESTS_PERSON',
    category: 'arrest',
    eventName: 'Officer Arrests Person',
    description: 'Officer places person under formal arrest.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_ARRE_001', 'POSTLD15_ARRE_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_STATES_ARREST_CHARGES',
    category: 'arrest',
    eventName: 'Officer States Charges',
    description: 'Officer informs person of the charges at time of arrest.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_ARRE_003'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_TRANSPORTS_ARRESTEE',
    category: 'arrest',
    eventName: 'Officer Transports Arrestee',
    description: 'Officer transports arrested person to booking facility.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_BOOKS_ARRESTEE',
    category: 'arrest',
    eventName: 'Officer Books Arrestee',
    description: 'Officer completes booking process at jail or station.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CITES_AND_RELEASES',
    category: 'arrest',
    eventName: 'Officer Issues Citation and Releases',
    description: 'Officer issues a citation and releases the person.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'document'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_EXECUTES_ARREST_WARRANT',
    category: 'arrest',
    eventName: 'Officer Executes Arrest Warrant',
    description: 'Officer arrests person based on outstanding warrant.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'document'],
    relatedDoctrineRules: ['POSTLD15_ARRE_004'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_MAKES_WARRANTLESS_ARREST',
    category: 'arrest',
    eventName: 'Officer Makes Warrantless Arrest',
    description: 'Officer arrests person without a warrant based on probable cause.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD15_ARRE_001', 'POSTLD15_ARRE_005'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DOCUMENTS_PROBABLE_CAUSE',
    category: 'arrest',
    eventName: 'Officer Documents Probable Cause',
    description: 'Officer records the facts establishing probable cause for arrest.',
    actorTypes: ['officer'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD15_ARRE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_SURRENDERS',
    category: 'arrest',
    eventName: 'Suspect Surrenders',
    description: 'Suspect voluntarily submits to arrest.',
    actorTypes: ['suspect'],
    objectTypes: ['none'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEARCHES_INCIDENT_ARREST',
    category: 'arrest',
    eventName: 'Officer Searches Incident to Arrest',
    description: 'Officer searches person\'s body and immediate area incident to arrest.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD16_INCI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_INVENTORIES_PERSONAL_PROPERTY',
    category: 'arrest',
    eventName: 'Officer Inventories Personal Property',
    description: 'Officer catalogs arrestee\'s personal belongings.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'container'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_DWAI_ARREST',
    category: 'arrest',
    eventName: 'Officer Conducts DUI/DWI Arrest',
    description: 'Officer arrests person for driving under the influence.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'vehicle'],
    relatedDoctrineRules: ['POSTLD15_ARRE_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_FIELD_SOBRIETY',
    category: 'arrest',
    eventName: 'Officer Conducts Field Sobriety Test',
    description: 'Officer administers standardized field sobriety tests.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ADMINISTERS_BREATHALYZER',
    category: 'arrest',
    eventName: 'Officer Administers Breathalyzer',
    description: 'Officer uses breath testing device for BAC measurement.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'electronic_device'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // DOCUMENTATION (12 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_ACTIVATES_BODYCAM',
    category: 'documentation',
    eventName: 'Officer Activates Body-Worn Camera',
    description: 'Officer turns on body-worn camera to record.',
    actorTypes: ['officer'],
    objectTypes: ['bodycam'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DEACTIVATES_BODYCAM',
    category: 'documentation',
    eventName: 'Officer Deactivates Body-Worn Camera',
    description: 'Officer turns off body-worn camera.',
    actorTypes: ['officer'],
    objectTypes: ['bodycam'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'BODYCAM_BUFFER_STARTS',
    category: 'documentation',
    eventName: 'Body Camera Buffer Period Begins',
    description: 'Body camera pre-event buffer recording begins (typically 30-120s before activation).',
    actorTypes: ['officer'],
    objectTypes: ['bodycam'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_WRITES_REPORT',
    category: 'documentation',
    eventName: 'Officer Writes Report',
    description: 'Officer creates written incident or arrest report.',
    actorTypes: ['officer'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD18_REPO_001', 'POSTLD18_REPO_002'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SUPPLEMENTS_REPORT',
    category: 'documentation',
    eventName: 'Officer Supplements Report',
    description: 'Officer adds supplemental information to existing report.',
    actorTypes: ['officer'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD18_SUPP_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUPERVISOR_REVIEWS_REPORT',
    category: 'documentation',
    eventName: 'Supervisor Reviews Report',
    description: 'Supervising officer reviews and approves incident report.',
    actorTypes: ['supervisor'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD18_REVI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DRAWS_SCENE_DIAGRAM',
    category: 'documentation',
    eventName: 'Officer Draws Scene Diagram',
    description: 'Officer creates a diagram or map of the incident scene.',
    actorTypes: ['officer'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD18_DIAG_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_RECORDS_SERIAL_NUMBER',
    category: 'documentation',
    eventName: 'Officer Records Serial Number',
    description: 'Officer documents serial numbers of recovered items.',
    actorTypes: ['officer'],
    objectTypes: ['weapon', 'electronic_device'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_NOTES_TIME',
    category: 'documentation',
    eventName: 'Officer Notes Time',
    description: 'Officer documents a specific time for an event.',
    actorTypes: ['officer'],
    objectTypes: ['none'],
    relatedDoctrineRules: ['POSTLD18_TIME_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_DOCUMENTS_INJURIES',
    category: 'documentation',
    eventName: 'Officer Documents Injuries',
    description: 'Officer photographs and describes visible injuries.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD18_INJU_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_RECORDS_DASH_CAM_ID',
    category: 'documentation',
    eventName: 'Officer Records Dashcam/BWC ID',
    description: 'Officer notes which camera recorded the incident.',
    actorTypes: ['officer'],
    objectTypes: ['bodycam', 'dashcam'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'REPORT_FILED_LATE',
    category: 'documentation',
    eventName: 'Report Filed After Standard Timeframe',
    description: 'Report or supplemental filed significantly after the incident.',
    actorTypes: ['officer'],
    objectTypes: ['document'],
    relatedDoctrineRules: ['POSTLD18_REPO_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // SURVEILLANCE (8 types)
  // =========================================================================
  {
    eventTypeId: 'SURVEILLANCE_CAMERA_RECORDS',
    category: 'surveillance',
    eventName: 'Surveillance Camera Records Event',
    description: 'Third-party or public surveillance camera records activity.',
    actorTypes: ['unknown'],
    objectTypes: ['surveillance_camera'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_REQUESTS_SURVEILLANCE',
    category: 'surveillance',
    eventName: 'Officer Requests Surveillance Footage',
    description: 'Officer requests video from business or public camera system.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['surveillance_camera'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SURVEILLANCE_FOOTAGE_OBTAINED',
    category: 'surveillance',
    eventName: 'Surveillance Footage Obtained',
    description: 'Third-party surveillance video is acquired as evidence.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['surveillance_camera'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SURVEILLANCE_FOOTAGE_UNAVAILABLE',
    category: 'surveillance',
    eventName: 'Surveillance Footage Unavailable',
    description: 'Requested surveillance footage is missing or overwritten.',
    actorTypes: ['unknown'],
    objectTypes: ['surveillance_camera'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'BYSTANDER_RECORDS_VIDEO',
    category: 'surveillance',
    eventName: 'Bystander Records Video',
    description: 'Civilian records video of the incident on a phone.',
    actorTypes: ['bystander'],
    objectTypes: ['phone'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_SEIZES_CIVILIAN_RECORDING',
    category: 'surveillance',
    eventName: 'Officer Seizes Civilian Recording Device',
    description: 'Officer confiscates a civilian phone or camera.',
    actorTypes: ['officer'],
    objectTypes: ['phone'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SURVEILLANCE_GAP_DETECTED',
    category: 'surveillance',
    eventName: 'Surveillance Gap Detected',
    description: 'Time period with no available video from any source.',
    actorTypes: ['unknown'],
    objectTypes: ['surveillance_camera', 'bodycam', 'dashcam'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'BODYCAM_FOOTAGE_MISSING',
    category: 'surveillance',
    eventName: 'Body Camera Footage Missing or Corrupted',
    description: 'Expected bodycam footage is unavailable or corrupted.',
    actorTypes: ['officer'],
    objectTypes: ['bodycam'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // MEDICAL (6 types)
  // =========================================================================
  {
    eventTypeId: 'EMS_ARRIVES',
    category: 'medical',
    eventName: 'EMS Arrives at Scene',
    description: 'Emergency medical services arrive at the incident.',
    actorTypes: ['ems'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_TRANSPORTED_TO_HOSPITAL',
    category: 'medical',
    eventName: 'Person Transported to Hospital',
    description: 'Injured person is transported to medical facility.',
    actorTypes: ['ems'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_COMPLAINS_OF_INJURY',
    category: 'medical',
    eventName: 'Person Complains of Injury',
    description: 'Person verbally reports pain or injury.',
    actorTypes: ['suspect', 'officer', 'witness', 'bystander'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_ADMINISTERS_FIRST_AID',
    category: 'medical',
    eventName: 'Officer Administers First Aid',
    description: 'Officer provides immediate medical assistance.',
    actorTypes: ['officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: ['POSTLD20_MEDI_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_REFUSES_MEDICAL_AID',
    category: 'medical',
    eventName: 'Person Refuses Medical Aid',
    description: 'Person declines medical treatment.',
    actorTypes: ['suspect', 'officer'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'PERSON_DECLARED_DECEASED',
    category: 'medical',
    eventName: 'Person Declared Deceased',
    description: 'Person is pronounced dead at scene or hospital.',
    actorTypes: ['ems'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // IDENTIFICATION (6 types)
  // =========================================================================
  {
    eventTypeId: 'OFFICER_RUNS_LICENSE_PLATE',
    category: 'identification',
    eventName: 'Officer Runs License Plate',
    description: 'Officer queries license plate through dispatch or MDT.',
    actorTypes: ['officer'],
    objectTypes: ['vehicle'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_VERIFIES_IDENTITY',
    category: 'identification',
    eventName: 'Officer Verifies Identity',
    description: 'Officer confirms identity through ID, database, or other means.',
    actorTypes: ['officer'],
    objectTypes: ['person', 'identification_card'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CONDUCTS_LINEUP',
    category: 'identification',
    eventName: 'Officer Conducts Lineup',
    description: 'Officer organizes a photo or in-person lineup.',
    actorTypes: ['officer', 'detective'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'WITNESS_IDENTIFIES_SUSPECT',
    category: 'identification',
    eventName: 'Witness Identifies Suspect',
    description: 'Witness positively identifies a person as the suspect.',
    actorTypes: ['witness'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'WITNESS_FAILS_TO_IDENTIFY',
    category: 'identification',
    eventName: 'Witness Fails to Identify Suspect',
    description: 'Witness cannot identify or incorrectly identifies a person.',
    actorTypes: ['witness'],
    objectTypes: ['person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_PROVIDES_FALSE_ID',
    category: 'identification',
    eventName: 'Suspect Provides False Identification',
    description: 'Suspect gives a false name or identification.',
    actorTypes: ['suspect'],
    objectTypes: ['identification_card'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // DISPATCH (6 types)
  // =========================================================================
  {
    eventTypeId: 'DISPATCH_RECEIVES_911_CALL',
    category: 'dispatch',
    eventName: 'Dispatch Receives 911 Call',
    description: 'Emergency call received by dispatch center.',
    actorTypes: ['dispatcher'],
    objectTypes: ['none'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'DISPATCH_ASSIGNS_UNITS',
    category: 'dispatch',
    eventName: 'Dispatch Assigns Units',
    description: 'Dispatcher assigns officer units to respond to a call.',
    actorTypes: ['dispatcher'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'DISPATCH_UPGRADES_PRIORITY',
    category: 'dispatch',
    eventName: 'Dispatch Upgrades Call Priority',
    description: 'Dispatcher increases the priority level of an active call.',
    actorTypes: ['dispatcher'],
    objectTypes: ['none'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_GOES_ON_SCENE',
    category: 'dispatch',
    eventName: 'Officer Reports On-Scene',
    description: 'Officer radios dispatch that they have arrived at the call location.',
    actorTypes: ['officer'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'OFFICER_CLEARS_CALL',
    category: 'dispatch',
    eventName: 'Officer Clears Call',
    description: 'Officer reports call completed to dispatch.',
    actorTypes: ['officer'],
    objectTypes: ['radio'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'DISPATCH_RECORDS_DISPOSITION',
    category: 'dispatch',
    eventName: 'Dispatch Records Call Disposition',
    description: 'Dispatcher logs the final disposition of the call.',
    actorTypes: ['dispatcher'],
    objectTypes: ['none'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // K9 (4 types)
  // =========================================================================
  {
    eventTypeId: 'K9_DEPLOYED_FOR_TRACK',
    category: 'k9',
    eventName: 'K-9 Deployed for Tracking',
    description: 'K-9 unit deployed to track a fleeing suspect.',
    actorTypes: ['k9_handler'],
    objectTypes: ['k9'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'K9_LOCATES_SUSPECT',
    category: 'k9',
    eventName: 'K-9 Locates Suspect',
    description: 'K-9 finds hidden suspect.',
    actorTypes: ['k9_handler'],
    objectTypes: ['k9', 'person'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'K9_LOCATES_EVIDENCE',
    category: 'k9',
    eventName: 'K-9 Locates Evidence',
    description: 'K-9 indicates on hidden narcotics or evidence.',
    actorTypes: ['k9_handler'],
    objectTypes: ['k9', 'narcotics'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'K9_HANDLER_GIVES_WARNING',
    category: 'k9',
    eventName: 'K-9 Handler Gives Warning',
    description: 'K-9 handler warns suspect that K-9 will be released.',
    actorTypes: ['k9_handler'],
    objectTypes: ['person', 'k9'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  // =========================================================================
  // WEAPON (4 types)
  // =========================================================================
  {
    eventTypeId: 'WEAPON_DISCOVERED',
    category: 'weapon',
    eventName: 'Weapon Discovered',
    description: 'A weapon is found during search or in plain view.',
    actorTypes: ['officer'],
    objectTypes: ['weapon', 'firearm'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'WEAPON_MADE_SAFE',
    category: 'weapon',
    eventName: 'Weapon Made Safe',
    description: 'Officer unloads or secures a discovered weapon.',
    actorTypes: ['officer'],
    objectTypes: ['weapon', 'firearm'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_DISCARDS_WEAPON',
    category: 'weapon',
    eventName: 'Suspect Discards Weapon',
    description: 'Suspect throws or drops a weapon.',
    actorTypes: ['suspect'],
    objectTypes: ['weapon'],
    relatedDoctrineRules: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    eventTypeId: 'SUSPECT_REACHES_FOR_WEAPON',
    category: 'weapon',
    eventName: 'Suspect Reaches for Weapon',
    description: 'Suspect makes a movement toward a weapon.',
    actorTypes: ['suspect'],
    objectTypes: ['weapon'],
    relatedDoctrineRules: ['POSTLD20_DEAD_001'],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Lookup Utilities
// ---------------------------------------------------------------------------

const eventTypeMap = new Map<string, EventTypeDefinition>();
for (const et of EVENT_TYPE_REGISTRY) {
  eventTypeMap.set(et.eventTypeId, et);
}

const eventsByCategory = new Map<EventCategory, EventTypeDefinition[]>();
for (const et of EVENT_TYPE_REGISTRY) {
  const list = eventsByCategory.get(et.category) ?? [];
  list.push(et);
  eventsByCategory.set(et.category, list);
}

/**
 * Get an event type definition by ID.
 */
export function getEventType(eventTypeId: string): EventTypeDefinition | null {
  return eventTypeMap.get(eventTypeId) ?? null;
}

/**
 * Get all event types for a given category.
 */
export function getEventTypesByCategory(category: EventCategory): EventTypeDefinition[] {
  return eventsByCategory.get(category) ?? [];
}

/**
 * Get all event types that map to a specific doctrine rule.
 */
export function getEventTypesByDoctrineRule(doctrineRuleId: string): EventTypeDefinition[] {
  return EVENT_TYPE_REGISTRY.filter((et) =>
    et.relatedDoctrineRules.includes(doctrineRuleId),
  );
}

/**
 * Get category counts.
 */
export function getOntologyStats(): Record<EventCategory, number> {
  const stats: Partial<Record<EventCategory, number>> = {};
  for (const [cat, list] of eventsByCategory.entries()) {
    stats[cat] = list.length;
  }
  return stats as Record<EventCategory, number>;
}

/**
 * Validate that an event type ID exists in the registry.
 */
export function isValidEventType(eventTypeId: string): boolean {
  return eventTypeMap.has(eventTypeId);
}

export const TOTAL_EVENT_TYPES = EVENT_TYPE_REGISTRY.length;
