// ============================================================================
// Legal Disclaimer Page
// Required for production: establishes that CourtAccess does not provide legal advice.
// ============================================================================

import { Link } from 'react-router-dom';

export function LegalDisclaimerPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#0a0e17', color: '#e2e8f0' }}>
      {/* Header */}
      <header style={{
        borderBottom: '1px solid rgba(255,255,255,0.1)',
        padding: '16px 32px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      }}>
        <Link to="/" style={{ color: '#60a5fa', textDecoration: 'none', fontSize: '20px', fontWeight: 700 }}>
          CourtAccess
        </Link>
        <nav style={{ display: 'flex', gap: '24px' }}>
          <Link to="/login" style={{ color: '#94a3b8', textDecoration: 'none' }}>Login</Link>
          <Link to="/register" style={{ color: '#60a5fa', textDecoration: 'none' }}>Sign Up</Link>
        </nav>
      </header>

      {/* Content */}
      <main style={{ maxWidth: '800px', margin: '0 auto', padding: '48px 24px' }}>
        <h1 style={{ fontSize: '32px', fontWeight: 700, marginBottom: '8px', color: '#f1f5f9' }}>
          Legal Disclaimer
        </h1>
        <p style={{ color: '#64748b', marginBottom: '40px', fontSize: '14px' }}>
          Last updated: March 12, 2026
        </p>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#e2e8f0' }}>
            Not Legal Advice
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8', marginBottom: '16px' }}>
            CourtAccess is a technology platform that provides legal research tools, document analysis,
            evidence management, and investigative intelligence capabilities. <strong style={{ color: '#f1f5f9' }}>
            The information, analysis, and outputs provided by CourtAccess do not constitute legal advice.</strong>
          </p>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            CourtAccess is not a law firm and does not provide legal services. No attorney-client
            relationship is created by using this platform. The platform&apos;s AI-powered analysis,
            contradiction detection, doctrine matching, and policy intelligence features are tools
            designed to assist legal professionals in their work — they are not substitutes for
            professional legal judgment.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#e2e8f0' }}>
            For Informational and Investigative Use Only
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8', marginBottom: '16px' }}>
            All content, analysis results, contradiction reports, timeline reconstructions, evidence
            graphs, policy comparisons, and other outputs generated by CourtAccess are provided
            <strong style={{ color: '#f1f5f9' }}> for informational and investigative purposes only</strong>.
          </p>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            These outputs should be independently verified by qualified legal professionals before
            being relied upon in any legal proceeding, filing, or decision-making process. CourtAccess
            makes no warranties regarding the accuracy, completeness, or legal sufficiency of any
            analysis or output.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#e2e8f0' }}>
            Attorney Responsibility
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8', marginBottom: '16px' }}>
            <strong style={{ color: '#f1f5f9' }}>Licensed attorneys are solely responsible for all legal
            conclusions, strategies, and decisions</strong> made using information obtained through CourtAccess.
            Attorneys must exercise independent professional judgment and comply with all applicable
            rules of professional conduct and ethical obligations.
          </p>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            The use of CourtAccess does not relieve any attorney of their professional obligations,
            including but not limited to the duty of competence, the duty of diligence, and the duty
            to maintain client confidences.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#e2e8f0' }}>
            AI-Generated Content
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8', marginBottom: '16px' }}>
            CourtAccess uses artificial intelligence and machine learning technologies to analyze
            documents, detect contradictions, classify policies, and generate investigative insights.
            AI-generated content may contain errors, omissions, or inaccuracies. Users should
            critically evaluate all AI-generated outputs and verify them against primary sources.
          </p>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            AI classification confidence scores are provided as indicators of certainty but should
            not be treated as definitive assessments. Human review and verification of all
            AI-generated analysis is strongly recommended before use in legal proceedings.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#e2e8f0' }}>
            CPRA Policy Acquisition
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            The California Public Records Act (CPRA) policy acquisition features of CourtAccess
            automate the process of requesting and collecting public records from law enforcement
            agencies. All requests are made pursuant to California Government Code sections 7920-7931.
            Responses received from agencies are public records and are processed as-is. CourtAccess
            does not guarantee the completeness or accuracy of agency responses.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#e2e8f0' }}>
            Limitation of Liability
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            To the maximum extent permitted by applicable law, CourtAccess and its operators shall
            not be liable for any indirect, incidental, special, consequential, or punitive damages,
            or any loss of profits or revenues, whether incurred directly or indirectly, or any loss
            of data, use, goodwill, or other intangible losses, resulting from your use of the platform
            or any analysis, report, or output generated by the platform.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#e2e8f0' }}>
            Jurisdiction
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            CourtAccess currently focuses on California law enforcement policies and legal frameworks.
            Users operating in other jurisdictions should be aware that laws, procedures, and legal
            standards may differ. The platform&apos;s analysis should not be assumed to apply outside
            of the jurisdictions for which it was designed.
          </p>
        </section>

        <section style={{
          marginBottom: '32px',
          padding: '24px',
          background: 'rgba(59, 130, 246, 0.1)',
          borderRadius: '8px',
          border: '1px solid rgba(59, 130, 246, 0.2)',
        }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '12px', color: '#60a5fa' }}>
            Acknowledgment
          </h2>
          <p style={{ lineHeight: 1.7, color: '#94a3b8' }}>
            By using CourtAccess, you acknowledge that you have read and understood this legal
            disclaimer. You agree that CourtAccess provides tools and information for professional
            use and does not replace the judgment, expertise, or ethical obligations of licensed
            legal professionals.
          </p>
        </section>

        <div style={{ marginTop: '48px', paddingTop: '24px', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
          <p style={{ color: '#64748b', fontSize: '14px' }}>
            If you have questions about this disclaimer, please contact us at{' '}
            <a href="mailto:legal@courtaccess.net" style={{ color: '#60a5fa' }}>legal@courtaccess.net</a>.
          </p>
        </div>
      </main>
    </div>
  );
}
