// ============================================
// Court Access — California Law Enforcement Agency Seed Data
// Comprehensive directory of ~600 California agencies.
// Sources: CA POST, DOJ OpenJustice, county/city records.
// ============================================

import type { SeedAgency } from './types.js';

// ---------------------------------------------------------------------------
// 58 County Sheriff Departments
// ---------------------------------------------------------------------------

const sheriffDepartments: SeedAgency[] = [
  { agencyName: 'Alameda County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Alameda', city: 'Oakland', website: 'https://www.alamedacountysheriff.org' },
  { agencyName: 'Alpine County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Alpine', city: 'Markleeville' },
  { agencyName: 'Amador County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Amador', city: 'Jackson', website: 'https://www.amadorgov.org/government/sheriff' },
  { agencyName: 'Butte County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Butte', city: 'Oroville', website: 'https://www.buttecounty.net/sheriffcoroner' },
  { agencyName: 'Calaveras County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Calaveras', city: 'San Andreas', website: 'https://sheriff.calaverasgov.us' },
  { agencyName: 'Colusa County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Colusa', city: 'Colusa' },
  { agencyName: 'Contra Costa County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Contra Costa', city: 'Martinez', website: 'https://www.cocosheriff.org' },
  { agencyName: 'Del Norte County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Del Norte', city: 'Crescent City' },
  { agencyName: 'El Dorado County Sheriff\'s Office', agencyType: 'Sheriff', county: 'El Dorado', city: 'Placerville', website: 'https://www.edcgov.us/Government/Sheriff' },
  { agencyName: 'Fresno County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Fresno', city: 'Fresno', website: 'https://www.fresnosheriff.org' },
  { agencyName: 'Glenn County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Glenn', city: 'Willows' },
  { agencyName: 'Humboldt County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Humboldt', city: 'Eureka', website: 'https://humboldtgov.org/186/Sheriff' },
  { agencyName: 'Imperial County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Imperial', city: 'El Centro', website: 'https://www.imperialcountysheriff.org' },
  { agencyName: 'Inyo County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Inyo', city: 'Independence' },
  { agencyName: 'Kern County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Kern', city: 'Bakersfield', website: 'https://www.kernsheriff.org' },
  { agencyName: 'Kings County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Kings', city: 'Hanford' },
  { agencyName: 'Lake County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Lake', city: 'Lakeport' },
  { agencyName: 'Lassen County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Lassen', city: 'Susanville' },
  { agencyName: 'Los Angeles County Sheriff\'s Department', agencyType: 'Sheriff', county: 'Los Angeles', city: 'Los Angeles', website: 'https://www.lasd.org', policyUrl: 'https://pars.lasd.org' },
  { agencyName: 'Madera County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Madera', city: 'Madera' },
  { agencyName: 'Marin County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Marin', city: 'San Rafael', website: 'https://www.marinsheriff.org' },
  { agencyName: 'Mariposa County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Mariposa', city: 'Mariposa' },
  { agencyName: 'Mendocino County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Mendocino', city: 'Ukiah' },
  { agencyName: 'Merced County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Merced', city: 'Merced', website: 'https://www.co.merced.ca.us/sheriff' },
  { agencyName: 'Modoc County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Modoc', city: 'Alturas' },
  { agencyName: 'Mono County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Mono', city: 'Bridgeport' },
  { agencyName: 'Monterey County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Monterey', city: 'Salinas', website: 'https://www.montereysheriff.org' },
  { agencyName: 'Napa County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Napa', city: 'Napa', website: 'https://www.countyofnapa.org/181/Sheriff' },
  { agencyName: 'Nevada County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Nevada', city: 'Nevada City', website: 'https://www.mynevadacounty.com/446/Sheriff' },
  { agencyName: 'Orange County Sheriff\'s Department', agencyType: 'Sheriff', county: 'Orange', city: 'Santa Ana', website: 'https://www.ocsheriff.gov' },
  { agencyName: 'Placer County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Placer', city: 'Auburn', website: 'https://www.placer.ca.gov/2956/Sheriff' },
  { agencyName: 'Plumas County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Plumas', city: 'Quincy' },
  { agencyName: 'Riverside County Sheriff\'s Department', agencyType: 'Sheriff', county: 'Riverside', city: 'Riverside', website: 'https://www.riversidesheriff.org' },
  { agencyName: 'Sacramento County Sheriff\'s Department', agencyType: 'Sheriff', county: 'Sacramento', city: 'Sacramento', website: 'https://www.sacsheriff.com' },
  { agencyName: 'San Benito County Sheriff\'s Office', agencyType: 'Sheriff', county: 'San Benito', city: 'Hollister' },
  { agencyName: 'San Bernardino County Sheriff\'s Department', agencyType: 'Sheriff', county: 'San Bernardino', city: 'San Bernardino', website: 'https://wp.sbcounty.gov/sheriff' },
  { agencyName: 'San Diego County Sheriff\'s Department', agencyType: 'Sheriff', county: 'San Diego', city: 'San Diego', website: 'https://www.sdsheriff.gov' },
  { agencyName: 'San Francisco Sheriff\'s Department', agencyType: 'Sheriff', county: 'San Francisco', city: 'San Francisco', website: 'https://www.sfsheriff.com' },
  { agencyName: 'San Joaquin County Sheriff\'s Office', agencyType: 'Sheriff', county: 'San Joaquin', city: 'French Camp', website: 'https://www.sjgov.org/sheriff' },
  { agencyName: 'San Luis Obispo County Sheriff\'s Office', agencyType: 'Sheriff', county: 'San Luis Obispo', city: 'San Luis Obispo', website: 'https://www.slosheriff.org' },
  { agencyName: 'San Mateo County Sheriff\'s Office', agencyType: 'Sheriff', county: 'San Mateo', city: 'Redwood City', website: 'https://www.smcsheriff.com' },
  { agencyName: 'Santa Barbara County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Santa Barbara', city: 'Santa Barbara', website: 'https://www.sbsheriff.org' },
  { agencyName: 'Santa Clara County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Santa Clara', city: 'San Jose', website: 'https://www.sccgov.org/sites/sheriff' },
  { agencyName: 'Santa Cruz County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Santa Cruz', city: 'Santa Cruz', website: 'https://www.scsheriff.com' },
  { agencyName: 'Shasta County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Shasta', city: 'Redding', website: 'https://www.shastainteractive.com/sheriff' },
  { agencyName: 'Sierra County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Sierra', city: 'Downieville' },
  { agencyName: 'Siskiyou County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Siskiyou', city: 'Yreka' },
  { agencyName: 'Solano County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Solano', city: 'Fairfield', website: 'https://www.solanocounty.com/depts/sheriff' },
  { agencyName: 'Sonoma County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Sonoma', city: 'Santa Rosa', website: 'https://www.sonomasheriff.org' },
  { agencyName: 'Stanislaus County Sheriff\'s Department', agencyType: 'Sheriff', county: 'Stanislaus', city: 'Modesto', website: 'https://www.scsheriff.com' },
  { agencyName: 'Sutter County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Sutter', city: 'Yuba City' },
  { agencyName: 'Tehama County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Tehama', city: 'Red Bluff' },
  { agencyName: 'Trinity County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Trinity', city: 'Weaverville' },
  { agencyName: 'Tulare County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Tulare', city: 'Visalia', website: 'https://tularecounty.ca.gov/sheriff' },
  { agencyName: 'Tuolumne County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Tuolumne', city: 'Sonora' },
  { agencyName: 'Ventura County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Ventura', city: 'Ventura', website: 'https://www.vcsd.org' },
  { agencyName: 'Yolo County Sheriff\'s Office', agencyType: 'Sheriff', county: 'Yolo', city: 'Woodland', website: 'https://www.yolocountysheriff.com' },
  { agencyName: 'Yuba County Sheriff\'s Department', agencyType: 'Sheriff', county: 'Yuba', city: 'Marysville' },
];

// ---------------------------------------------------------------------------
// Municipal Police Departments (major cities + medium cities)
// ---------------------------------------------------------------------------

const policeDepartments: SeedAgency[] = [
  // --- Los Angeles County ---
  { agencyName: 'Los Angeles Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Los Angeles', website: 'https://www.lapdonline.org', policyUrl: 'https://www.lapdonline.org/lapd-manual' },
  { agencyName: 'Long Beach Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Long Beach', website: 'https://www.longbeach.gov/police' },
  { agencyName: 'Glendale Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Glendale', website: 'https://www.glendaleca.gov/government/departments/police-department' },
  { agencyName: 'Pasadena Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Pasadena', website: 'https://www.cityofpasadena.net/police' },
  { agencyName: 'Torrance Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Torrance' },
  { agencyName: 'Pomona Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Pomona' },
  { agencyName: 'El Monte Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'El Monte' },
  { agencyName: 'Downey Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Downey' },
  { agencyName: 'Inglewood Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Inglewood' },
  { agencyName: 'West Covina Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'West Covina' },
  { agencyName: 'Burbank Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Burbank', website: 'https://www.burbankpd.org' },
  { agencyName: 'Santa Monica Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Santa Monica', website: 'https://www.santamonica.gov/police' },
  { agencyName: 'Whittier Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Whittier' },
  { agencyName: 'Alhambra Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Alhambra' },
  { agencyName: 'Redondo Beach Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Redondo Beach' },
  { agencyName: 'Monrovia Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Monrovia' },
  { agencyName: 'Azusa Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Azusa' },
  { agencyName: 'Covina Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Covina' },
  { agencyName: 'Glendora Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Glendora' },
  { agencyName: 'Arcadia Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Arcadia' },
  { agencyName: 'Beverly Hills Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Beverly Hills', website: 'https://www.beverlyhills.org/departments/policedepartment' },
  { agencyName: 'Culver City Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Culver City' },
  { agencyName: 'Hermosa Beach Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Hermosa Beach' },
  { agencyName: 'Manhattan Beach Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Manhattan Beach' },
  { agencyName: 'Hawthorne Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Hawthorne' },
  { agencyName: 'Gardena Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Gardena' },
  { agencyName: 'Compton Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Compton' },
  { agencyName: 'South Gate Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'South Gate' },
  { agencyName: 'Bell Gardens Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Bell Gardens' },
  { agencyName: 'Claremont Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Claremont' },
  { agencyName: 'La Verne Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'La Verne' },
  { agencyName: 'Sierra Madre Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Sierra Madre' },
  { agencyName: 'San Fernando Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'San Fernando' },
  { agencyName: 'Signal Hill Police Department', agencyType: 'Police', county: 'Los Angeles', city: 'Signal Hill' },

  // --- San Francisco Bay Area ---
  { agencyName: 'San Francisco Police Department', agencyType: 'Police', county: 'San Francisco', city: 'San Francisco', website: 'https://www.sanfranciscopolice.org', policyUrl: 'https://www.sanfranciscopolice.org/your-sfpd/policies' },
  { agencyName: 'Oakland Police Department', agencyType: 'Police', county: 'Alameda', city: 'Oakland', website: 'https://www.oaklandca.gov/departments/police', policyUrl: 'https://www.oaklandca.gov/resources/opd-policies' },
  { agencyName: 'San Jose Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'San Jose', website: 'https://www.sjpd.org' },
  { agencyName: 'Fremont Police Department', agencyType: 'Police', county: 'Alameda', city: 'Fremont', website: 'https://www.fremontpolice.gov' },
  { agencyName: 'Hayward Police Department', agencyType: 'Police', county: 'Alameda', city: 'Hayward' },
  { agencyName: 'Berkeley Police Department', agencyType: 'Police', county: 'Alameda', city: 'Berkeley', website: 'https://www.cityofberkeley.info/Police' },
  { agencyName: 'Richmond Police Department', agencyType: 'Police', county: 'Contra Costa', city: 'Richmond' },
  { agencyName: 'Concord Police Department', agencyType: 'Police', county: 'Contra Costa', city: 'Concord' },
  { agencyName: 'Antioch Police Department', agencyType: 'Police', county: 'Contra Costa', city: 'Antioch' },
  { agencyName: 'Walnut Creek Police Department', agencyType: 'Police', county: 'Contra Costa', city: 'Walnut Creek' },
  { agencyName: 'Pittsburg Police Department', agencyType: 'Police', county: 'Contra Costa', city: 'Pittsburg' },
  { agencyName: 'Pleasanton Police Department', agencyType: 'Police', county: 'Alameda', city: 'Pleasanton' },
  { agencyName: 'Livermore Police Department', agencyType: 'Police', county: 'Alameda', city: 'Livermore' },
  { agencyName: 'Union City Police Department', agencyType: 'Police', county: 'Alameda', city: 'Union City' },
  { agencyName: 'Newark Police Department', agencyType: 'Police', county: 'Alameda', city: 'Newark' },
  { agencyName: 'Alameda Police Department', agencyType: 'Police', county: 'Alameda', city: 'Alameda' },
  { agencyName: 'San Leandro Police Department', agencyType: 'Police', county: 'Alameda', city: 'San Leandro' },
  { agencyName: 'Daly City Police Department', agencyType: 'Police', county: 'San Mateo', city: 'Daly City' },
  { agencyName: 'San Mateo Police Department', agencyType: 'Police', county: 'San Mateo', city: 'San Mateo' },
  { agencyName: 'Redwood City Police Department', agencyType: 'Police', county: 'San Mateo', city: 'Redwood City' },
  { agencyName: 'South San Francisco Police Department', agencyType: 'Police', county: 'San Mateo', city: 'South San Francisco' },
  { agencyName: 'Palo Alto Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Palo Alto', website: 'https://www.cityofpaloalto.org/Departments/Police' },
  { agencyName: 'Mountain View Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Mountain View' },
  { agencyName: 'Sunnyvale Department of Public Safety', agencyType: 'Police', county: 'Santa Clara', city: 'Sunnyvale' },
  { agencyName: 'Santa Clara Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Santa Clara' },
  { agencyName: 'Milpitas Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Milpitas' },
  { agencyName: 'Campbell Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Campbell' },
  { agencyName: 'Gilroy Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Gilroy' },
  { agencyName: 'Morgan Hill Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Morgan Hill' },
  { agencyName: 'Los Gatos-Monte Sereno Police Department', agencyType: 'Police', county: 'Santa Clara', city: 'Los Gatos' },
  { agencyName: 'San Rafael Police Department', agencyType: 'Police', county: 'Marin', city: 'San Rafael' },
  { agencyName: 'Novato Police Department', agencyType: 'Police', county: 'Marin', city: 'Novato' },
  { agencyName: 'Vallejo Police Department', agencyType: 'Police', county: 'Solano', city: 'Vallejo' },
  { agencyName: 'Fairfield Police Department', agencyType: 'Police', county: 'Solano', city: 'Fairfield' },
  { agencyName: 'Vacaville Police Department', agencyType: 'Police', county: 'Solano', city: 'Vacaville' },
  { agencyName: 'Napa Police Department', agencyType: 'Police', county: 'Napa', city: 'Napa' },
  { agencyName: 'Santa Rosa Police Department', agencyType: 'Police', county: 'Sonoma', city: 'Santa Rosa', website: 'https://www.srcity.org/766/Police-Department' },
  { agencyName: 'Petaluma Police Department', agencyType: 'Police', county: 'Sonoma', city: 'Petaluma' },
  { agencyName: 'Rohnert Park Department of Public Safety', agencyType: 'Police', county: 'Sonoma', city: 'Rohnert Park' },

  // --- San Diego County ---
  { agencyName: 'San Diego Police Department', agencyType: 'Police', county: 'San Diego', city: 'San Diego', website: 'https://www.sandiego.gov/police' },
  { agencyName: 'Chula Vista Police Department', agencyType: 'Police', county: 'San Diego', city: 'Chula Vista' },
  { agencyName: 'Oceanside Police Department', agencyType: 'Police', county: 'San Diego', city: 'Oceanside' },
  { agencyName: 'Escondido Police Department', agencyType: 'Police', county: 'San Diego', city: 'Escondido' },
  { agencyName: 'Carlsbad Police Department', agencyType: 'Police', county: 'San Diego', city: 'Carlsbad' },
  { agencyName: 'El Cajon Police Department', agencyType: 'Police', county: 'San Diego', city: 'El Cajon' },
  { agencyName: 'Vista Police Department', agencyType: 'Police', county: 'San Diego', city: 'Vista' },
  { agencyName: 'National City Police Department', agencyType: 'Police', county: 'San Diego', city: 'National City' },
  { agencyName: 'La Mesa Police Department', agencyType: 'Police', county: 'San Diego', city: 'La Mesa' },
  { agencyName: 'Coronado Police Department', agencyType: 'Police', county: 'San Diego', city: 'Coronado' },
  { agencyName: 'San Marcos Police Department', agencyType: 'Police', county: 'San Diego', city: 'San Marcos' },
  { agencyName: 'Encinitas Police Department', agencyType: 'Police', county: 'San Diego', city: 'Encinitas' },

  // --- Orange County ---
  { agencyName: 'Anaheim Police Department', agencyType: 'Police', county: 'Orange', city: 'Anaheim', website: 'https://www.anaheim.net/157/Police-Department' },
  { agencyName: 'Santa Ana Police Department', agencyType: 'Police', county: 'Orange', city: 'Santa Ana' },
  { agencyName: 'Irvine Police Department', agencyType: 'Police', county: 'Orange', city: 'Irvine', website: 'https://www.irvinepd.org' },
  { agencyName: 'Huntington Beach Police Department', agencyType: 'Police', county: 'Orange', city: 'Huntington Beach' },
  { agencyName: 'Garden Grove Police Department', agencyType: 'Police', county: 'Orange', city: 'Garden Grove' },
  { agencyName: 'Fullerton Police Department', agencyType: 'Police', county: 'Orange', city: 'Fullerton' },
  { agencyName: 'Costa Mesa Police Department', agencyType: 'Police', county: 'Orange', city: 'Costa Mesa' },
  { agencyName: 'Newport Beach Police Department', agencyType: 'Police', county: 'Orange', city: 'Newport Beach' },
  { agencyName: 'Westminster Police Department', agencyType: 'Police', county: 'Orange', city: 'Westminster' },
  { agencyName: 'Tustin Police Department', agencyType: 'Police', county: 'Orange', city: 'Tustin' },
  { agencyName: 'Buena Park Police Department', agencyType: 'Police', county: 'Orange', city: 'Buena Park' },
  { agencyName: 'La Habra Police Department', agencyType: 'Police', county: 'Orange', city: 'La Habra' },
  { agencyName: 'Laguna Beach Police Department', agencyType: 'Police', county: 'Orange', city: 'Laguna Beach' },
  { agencyName: 'Brea Police Department', agencyType: 'Police', county: 'Orange', city: 'Brea' },
  { agencyName: 'Placentia Police Department', agencyType: 'Police', county: 'Orange', city: 'Placentia' },
  { agencyName: 'Seal Beach Police Department', agencyType: 'Police', county: 'Orange', city: 'Seal Beach' },
  { agencyName: 'Cypress Police Department', agencyType: 'Police', county: 'Orange', city: 'Cypress' },
  { agencyName: 'Los Alamitos Police Department', agencyType: 'Police', county: 'Orange', city: 'Los Alamitos' },

  // --- Riverside County ---
  { agencyName: 'Riverside Police Department', agencyType: 'Police', county: 'Riverside', city: 'Riverside', website: 'https://www.riversideca.gov/rpd' },
  { agencyName: 'Moreno Valley Police Department', agencyType: 'Police', county: 'Riverside', city: 'Moreno Valley' },
  { agencyName: 'Corona Police Department', agencyType: 'Police', county: 'Riverside', city: 'Corona' },
  { agencyName: 'Murrieta Police Department', agencyType: 'Police', county: 'Riverside', city: 'Murrieta' },
  { agencyName: 'Temecula Police Department', agencyType: 'Police', county: 'Riverside', city: 'Temecula' },
  { agencyName: 'Hemet Police Department', agencyType: 'Police', county: 'Riverside', city: 'Hemet' },
  { agencyName: 'Palm Springs Police Department', agencyType: 'Police', county: 'Riverside', city: 'Palm Springs' },
  { agencyName: 'Indio Police Department', agencyType: 'Police', county: 'Riverside', city: 'Indio' },
  { agencyName: 'Beaumont Police Department', agencyType: 'Police', county: 'Riverside', city: 'Beaumont' },
  { agencyName: 'Cathedral City Police Department', agencyType: 'Police', county: 'Riverside', city: 'Cathedral City' },
  { agencyName: 'Perris Police Department', agencyType: 'Police', county: 'Riverside', city: 'Perris' },
  { agencyName: 'Banning Police Department', agencyType: 'Police', county: 'Riverside', city: 'Banning' },

  // --- San Bernardino County ---
  { agencyName: 'San Bernardino Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'San Bernardino' },
  { agencyName: 'Fontana Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Fontana' },
  { agencyName: 'Ontario Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Ontario' },
  { agencyName: 'Rancho Cucamonga Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Rancho Cucamonga' },
  { agencyName: 'Rialto Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Rialto' },
  { agencyName: 'Upland Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Upland' },
  { agencyName: 'Redlands Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Redlands' },
  { agencyName: 'Chino Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Chino' },
  { agencyName: 'Colton Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Colton' },
  { agencyName: 'Montclair Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Montclair' },
  { agencyName: 'Barstow Police Department', agencyType: 'Police', county: 'San Bernardino', city: 'Barstow' },

  // --- Sacramento Region ---
  { agencyName: 'Sacramento Police Department', agencyType: 'Police', county: 'Sacramento', city: 'Sacramento', website: 'https://www.cityofsacramento.org/Police' },
  { agencyName: 'Elk Grove Police Department', agencyType: 'Police', county: 'Sacramento', city: 'Elk Grove' },
  { agencyName: 'Folsom Police Department', agencyType: 'Police', county: 'Sacramento', city: 'Folsom' },
  { agencyName: 'Citrus Heights Police Department', agencyType: 'Police', county: 'Sacramento', city: 'Citrus Heights' },
  { agencyName: 'Roseville Police Department', agencyType: 'Police', county: 'Placer', city: 'Roseville' },
  { agencyName: 'Rocklin Police Department', agencyType: 'Police', county: 'Placer', city: 'Rocklin' },
  { agencyName: 'Lincoln Police Department', agencyType: 'Police', county: 'Placer', city: 'Lincoln' },
  { agencyName: 'Davis Police Department', agencyType: 'Police', county: 'Yolo', city: 'Davis' },
  { agencyName: 'West Sacramento Police Department', agencyType: 'Police', county: 'Yolo', city: 'West Sacramento' },
  { agencyName: 'Woodland Police Department', agencyType: 'Police', county: 'Yolo', city: 'Woodland' },

  // --- Central Valley ---
  { agencyName: 'Fresno Police Department', agencyType: 'Police', county: 'Fresno', city: 'Fresno', website: 'https://www.fresno.gov/police' },
  { agencyName: 'Clovis Police Department', agencyType: 'Police', county: 'Fresno', city: 'Clovis' },
  { agencyName: 'Bakersfield Police Department', agencyType: 'Police', county: 'Kern', city: 'Bakersfield', website: 'https://www.bakersfieldpd.us' },
  { agencyName: 'Stockton Police Department', agencyType: 'Police', county: 'San Joaquin', city: 'Stockton', website: 'https://www.stocktonca.gov/government/departments/police' },
  { agencyName: 'Modesto Police Department', agencyType: 'Police', county: 'Stanislaus', city: 'Modesto' },
  { agencyName: 'Visalia Police Department', agencyType: 'Police', county: 'Tulare', city: 'Visalia' },
  { agencyName: 'Merced Police Department', agencyType: 'Police', county: 'Merced', city: 'Merced' },
  { agencyName: 'Turlock Police Department', agencyType: 'Police', county: 'Stanislaus', city: 'Turlock' },
  { agencyName: 'Hanford Police Department', agencyType: 'Police', county: 'Kings', city: 'Hanford' },
  { agencyName: 'Porterville Police Department', agencyType: 'Police', county: 'Tulare', city: 'Porterville' },
  { agencyName: 'Tulare Police Department', agencyType: 'Police', county: 'Tulare', city: 'Tulare' },
  { agencyName: 'Madera Police Department', agencyType: 'Police', county: 'Madera', city: 'Madera' },
  { agencyName: 'Lodi Police Department', agencyType: 'Police', county: 'San Joaquin', city: 'Lodi' },
  { agencyName: 'Manteca Police Department', agencyType: 'Police', county: 'San Joaquin', city: 'Manteca' },
  { agencyName: 'Tracy Police Department', agencyType: 'Police', county: 'San Joaquin', city: 'Tracy' },
  { agencyName: 'Delano Police Department', agencyType: 'Police', county: 'Kern', city: 'Delano' },
  { agencyName: 'Ridgecrest Police Department', agencyType: 'Police', county: 'Kern', city: 'Ridgecrest' },
  { agencyName: 'Wasco Police Department', agencyType: 'Police', county: 'Kern', city: 'Wasco' },
  { agencyName: 'Tehachapi Police Department', agencyType: 'Police', county: 'Kern', city: 'Tehachapi' },
  { agencyName: 'Selma Police Department', agencyType: 'Police', county: 'Fresno', city: 'Selma' },
  { agencyName: 'Sanger Police Department', agencyType: 'Police', county: 'Fresno', city: 'Sanger' },
  { agencyName: 'Coalinga Police Department', agencyType: 'Police', county: 'Fresno', city: 'Coalinga' },
  { agencyName: 'Parlier Police Department', agencyType: 'Police', county: 'Fresno', city: 'Parlier' },
  { agencyName: 'Kerman Police Department', agencyType: 'Police', county: 'Fresno', city: 'Kerman' },
  { agencyName: 'Los Banos Police Department', agencyType: 'Police', county: 'Merced', city: 'Los Banos' },
  { agencyName: 'Atwater Police Department', agencyType: 'Police', county: 'Merced', city: 'Atwater' },
  { agencyName: 'Livingston Police Department', agencyType: 'Police', county: 'Merced', city: 'Livingston' },
  { agencyName: 'Ceres Police Department', agencyType: 'Police', county: 'Stanislaus', city: 'Ceres' },
  { agencyName: 'Patterson Police Department', agencyType: 'Police', county: 'Stanislaus', city: 'Patterson' },
  { agencyName: 'Oakdale Police Department', agencyType: 'Police', county: 'Stanislaus', city: 'Oakdale' },
  { agencyName: 'Ripon Police Department', agencyType: 'Police', county: 'San Joaquin', city: 'Ripon' },
  { agencyName: 'Escalon Police Department', agencyType: 'Police', county: 'San Joaquin', city: 'Escalon' },

  // --- Santa Barbara / Ventura / San Luis Obispo ---
  { agencyName: 'Santa Barbara Police Department', agencyType: 'Police', county: 'Santa Barbara', city: 'Santa Barbara' },
  { agencyName: 'Santa Maria Police Department', agencyType: 'Police', county: 'Santa Barbara', city: 'Santa Maria' },
  { agencyName: 'Lompoc Police Department', agencyType: 'Police', county: 'Santa Barbara', city: 'Lompoc' },
  { agencyName: 'Guadalupe Police Department', agencyType: 'Police', county: 'Santa Barbara', city: 'Guadalupe' },
  { agencyName: 'Ventura Police Department', agencyType: 'Police', county: 'Ventura', city: 'Ventura' },
  { agencyName: 'Oxnard Police Department', agencyType: 'Police', county: 'Ventura', city: 'Oxnard' },
  { agencyName: 'Thousand Oaks Police Department', agencyType: 'Police', county: 'Ventura', city: 'Thousand Oaks' },
  { agencyName: 'Simi Valley Police Department', agencyType: 'Police', county: 'Ventura', city: 'Simi Valley' },
  { agencyName: 'Camarillo Police Department', agencyType: 'Police', county: 'Ventura', city: 'Camarillo' },
  { agencyName: 'Moorpark Police Department', agencyType: 'Police', county: 'Ventura', city: 'Moorpark' },
  { agencyName: 'Port Hueneme Police Department', agencyType: 'Police', county: 'Ventura', city: 'Port Hueneme' },
  { agencyName: 'Fillmore Police Department', agencyType: 'Police', county: 'Ventura', city: 'Fillmore' },
  { agencyName: 'San Luis Obispo Police Department', agencyType: 'Police', county: 'San Luis Obispo', city: 'San Luis Obispo' },
  { agencyName: 'Paso Robles Police Department', agencyType: 'Police', county: 'San Luis Obispo', city: 'Paso Robles' },
  { agencyName: 'Atascadero Police Department', agencyType: 'Police', county: 'San Luis Obispo', city: 'Atascadero' },
  { agencyName: 'Arroyo Grande Police Department', agencyType: 'Police', county: 'San Luis Obispo', city: 'Arroyo Grande' },
  { agencyName: 'Pismo Beach Police Department', agencyType: 'Police', county: 'San Luis Obispo', city: 'Pismo Beach' },
  { agencyName: 'Grover Beach Police Department', agencyType: 'Police', county: 'San Luis Obispo', city: 'Grover Beach' },
  { agencyName: 'Morro Bay Police Department', agencyType: 'Police', county: 'San Luis Obispo', city: 'Morro Bay' },

  // --- Monterey / Santa Cruz ---
  { agencyName: 'Monterey Police Department', agencyType: 'Police', county: 'Monterey', city: 'Monterey' },
  { agencyName: 'Salinas Police Department', agencyType: 'Police', county: 'Monterey', city: 'Salinas' },
  { agencyName: 'Seaside Police Department', agencyType: 'Police', county: 'Monterey', city: 'Seaside' },
  { agencyName: 'Marina Police Department', agencyType: 'Police', county: 'Monterey', city: 'Marina' },
  { agencyName: 'Pacific Grove Police Department', agencyType: 'Police', county: 'Monterey', city: 'Pacific Grove' },
  { agencyName: 'King City Police Department', agencyType: 'Police', county: 'Monterey', city: 'King City' },
  { agencyName: 'Gonzales Police Department', agencyType: 'Police', county: 'Monterey', city: 'Gonzales' },
  { agencyName: 'Greenfield Police Department', agencyType: 'Police', county: 'Monterey', city: 'Greenfield' },
  { agencyName: 'Soledad Police Department', agencyType: 'Police', county: 'Monterey', city: 'Soledad' },
  { agencyName: 'Santa Cruz Police Department', agencyType: 'Police', county: 'Santa Cruz', city: 'Santa Cruz' },
  { agencyName: 'Watsonville Police Department', agencyType: 'Police', county: 'Santa Cruz', city: 'Watsonville' },
  { agencyName: 'Scotts Valley Police Department', agencyType: 'Police', county: 'Santa Cruz', city: 'Scotts Valley' },
  { agencyName: 'Capitola Police Department', agencyType: 'Police', county: 'Santa Cruz', city: 'Capitola' },

  // --- Imperial / Eastern ---
  { agencyName: 'El Centro Police Department', agencyType: 'Police', county: 'Imperial', city: 'El Centro' },
  { agencyName: 'Calexico Police Department', agencyType: 'Police', county: 'Imperial', city: 'Calexico' },
  { agencyName: 'Brawley Police Department', agencyType: 'Police', county: 'Imperial', city: 'Brawley' },

  // --- Northern California ---
  { agencyName: 'Redding Police Department', agencyType: 'Police', county: 'Shasta', city: 'Redding' },
  { agencyName: 'Chico Police Department', agencyType: 'Police', county: 'Butte', city: 'Chico' },
  { agencyName: 'Eureka Police Department', agencyType: 'Police', county: 'Humboldt', city: 'Eureka' },
  { agencyName: 'Arcata Police Department', agencyType: 'Police', county: 'Humboldt', city: 'Arcata' },
  { agencyName: 'Fortuna Police Department', agencyType: 'Police', county: 'Humboldt', city: 'Fortuna' },
  { agencyName: 'Red Bluff Police Department', agencyType: 'Police', county: 'Tehama', city: 'Red Bluff' },
  { agencyName: 'Corning Police Department', agencyType: 'Police', county: 'Tehama', city: 'Corning' },
  { agencyName: 'Anderson Police Department', agencyType: 'Police', county: 'Shasta', city: 'Anderson' },
  { agencyName: 'Susanville Police Department', agencyType: 'Police', county: 'Lassen', city: 'Susanville' },
  { agencyName: 'Yreka Police Department', agencyType: 'Police', county: 'Siskiyou', city: 'Yreka' },
  { agencyName: 'Crescent City Police Department', agencyType: 'Police', county: 'Del Norte', city: 'Crescent City' },
  { agencyName: 'Ukiah Police Department', agencyType: 'Police', county: 'Mendocino', city: 'Ukiah' },
  { agencyName: 'Fort Bragg Police Department', agencyType: 'Police', county: 'Mendocino', city: 'Fort Bragg' },
  { agencyName: 'Willits Police Department', agencyType: 'Police', county: 'Mendocino', city: 'Willits' },
  { agencyName: 'Clearlake Police Department', agencyType: 'Police', county: 'Lake', city: 'Clearlake' },
  { agencyName: 'Lakeport Police Department', agencyType: 'Police', county: 'Lake', city: 'Lakeport' },
  { agencyName: 'Paradise Police Department', agencyType: 'Police', county: 'Butte', city: 'Paradise' },
  { agencyName: 'Oroville Police Department', agencyType: 'Police', county: 'Butte', city: 'Oroville' },
  { agencyName: 'Gridley Police Department', agencyType: 'Police', county: 'Butte', city: 'Gridley' },
  { agencyName: 'Yuba City Police Department', agencyType: 'Police', county: 'Sutter', city: 'Yuba City' },
  { agencyName: 'Marysville Police Department', agencyType: 'Police', county: 'Yuba', city: 'Marysville' },
  { agencyName: 'Auburn Police Department', agencyType: 'Police', county: 'Placer', city: 'Auburn' },
  { agencyName: 'Grass Valley Police Department', agencyType: 'Police', county: 'Nevada', city: 'Grass Valley' },
  { agencyName: 'Nevada City Police Department', agencyType: 'Police', county: 'Nevada', city: 'Nevada City' },
  { agencyName: 'Truckee Police Department', agencyType: 'Police', county: 'Nevada', city: 'Truckee' },
  { agencyName: 'South Lake Tahoe Police Department', agencyType: 'Police', county: 'El Dorado', city: 'South Lake Tahoe' },
  { agencyName: 'Placerville Police Department', agencyType: 'Police', county: 'El Dorado', city: 'Placerville' },
  { agencyName: 'Jackson Police Department', agencyType: 'Police', county: 'Amador', city: 'Jackson' },
  { agencyName: 'Angels Camp Police Department', agencyType: 'Police', county: 'Calaveras', city: 'Angels Camp' },
  { agencyName: 'Sonora Police Department', agencyType: 'Police', county: 'Tuolumne', city: 'Sonora' },

  // --- Hollister / San Benito ---
  { agencyName: 'Hollister Police Department', agencyType: 'Police', county: 'San Benito', city: 'Hollister' },
];

// ---------------------------------------------------------------------------
// State Law Enforcement Agencies
// ---------------------------------------------------------------------------

const stateAgencies: SeedAgency[] = [
  { agencyName: 'California Highway Patrol', agencyType: 'State', county: 'Sacramento', city: 'Sacramento', website: 'https://www.chp.ca.gov' },
  { agencyName: 'California Department of Justice — Bureau of Investigation', agencyType: 'State', county: 'Sacramento', city: 'Sacramento', website: 'https://oag.ca.gov' },
  { agencyName: 'California Department of Corrections and Rehabilitation', agencyType: 'State', county: 'Sacramento', city: 'Sacramento', website: 'https://www.cdcr.ca.gov' },
  { agencyName: 'California Department of Fish and Wildlife — Law Enforcement Division', agencyType: 'State', county: 'Sacramento', city: 'Sacramento', website: 'https://wildlife.ca.gov/enforcement' },
  { agencyName: 'California State Parks — Law Enforcement Division', agencyType: 'State', county: 'Sacramento', city: 'Sacramento', website: 'https://www.parks.ca.gov/Rangers' },
  { agencyName: 'California Department of Alcoholic Beverage Control', agencyType: 'State', county: 'Sacramento', city: 'Sacramento', website: 'https://www.abc.ca.gov' },
  { agencyName: 'California State Capitol Police', agencyType: 'State', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'California Department of Insurance — Fraud Division', agencyType: 'State', county: 'Sacramento', city: 'Sacramento', website: 'https://www.insurance.ca.gov' },
  { agencyName: 'California Franchise Tax Board — Criminal Investigation Bureau', agencyType: 'State', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'California Department of Motor Vehicles — Investigations Division', agencyType: 'State', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'California Office of Emergency Services — Law Enforcement', agencyType: 'State', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'California Horse Racing Board — Investigators', agencyType: 'State', county: 'Sacramento', city: 'Sacramento' },
];

// ---------------------------------------------------------------------------
// District Attorney Investigative Bureaus (major counties)
// ---------------------------------------------------------------------------

const districtAttorneyBureaus: SeedAgency[] = [
  { agencyName: 'Los Angeles County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'San Diego County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'Orange County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Orange', city: 'Santa Ana' },
  { agencyName: 'Riverside County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Riverside', city: 'Riverside' },
  { agencyName: 'San Bernardino County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'San Bernardino', city: 'San Bernardino' },
  { agencyName: 'Sacramento County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'Alameda County District Attorney — Inspector Division', agencyType: 'District_Attorney', county: 'Alameda', city: 'Oakland' },
  { agencyName: 'San Francisco District Attorney — Investigations Division', agencyType: 'District_Attorney', county: 'San Francisco', city: 'San Francisco' },
  { agencyName: 'Santa Clara County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Santa Clara', city: 'San Jose' },
  { agencyName: 'Contra Costa County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Contra Costa', city: 'Martinez' },
  { agencyName: 'Fresno County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Fresno', city: 'Fresno' },
  { agencyName: 'Kern County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Kern', city: 'Bakersfield' },
  { agencyName: 'San Joaquin County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'San Joaquin', city: 'Stockton' },
  { agencyName: 'Stanislaus County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Stanislaus', city: 'Modesto' },
  { agencyName: 'Ventura County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Ventura', city: 'Ventura' },
  { agencyName: 'San Mateo County District Attorney — Inspector Division', agencyType: 'District_Attorney', county: 'San Mateo', city: 'Redwood City' },
  { agencyName: 'Sonoma County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Sonoma', city: 'Santa Rosa' },
  { agencyName: 'Solano County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Solano', city: 'Fairfield' },
  { agencyName: 'Santa Barbara County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Santa Barbara', city: 'Santa Barbara' },
  { agencyName: 'Monterey County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Monterey', city: 'Salinas' },
  { agencyName: 'Tulare County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Tulare', city: 'Visalia' },
  { agencyName: 'Placer County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Placer', city: 'Auburn' },
  { agencyName: 'San Luis Obispo County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'San Luis Obispo', city: 'San Luis Obispo' },
  { agencyName: 'Marin County District Attorney — Inspector Division', agencyType: 'District_Attorney', county: 'Marin', city: 'San Rafael' },
  { agencyName: 'Santa Cruz County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Santa Cruz', city: 'Santa Cruz' },
  { agencyName: 'Butte County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Butte', city: 'Oroville' },
  { agencyName: 'Shasta County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Shasta', city: 'Redding' },
  { agencyName: 'El Dorado County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'El Dorado', city: 'Placerville' },
  { agencyName: 'Humboldt County District Attorney — Investigations', agencyType: 'District_Attorney', county: 'Humboldt', city: 'Eureka' },
  { agencyName: 'Imperial County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Imperial', city: 'El Centro' },
  { agencyName: 'Kings County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Kings', city: 'Hanford' },
  { agencyName: 'Madera County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Madera', city: 'Madera' },
  { agencyName: 'Merced County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Merced', city: 'Merced' },
  { agencyName: 'Napa County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Napa', city: 'Napa' },
  { agencyName: 'Yolo County District Attorney — Bureau of Investigation', agencyType: 'District_Attorney', county: 'Yolo', city: 'Woodland' },
];

// ---------------------------------------------------------------------------
// University Police Departments
// ---------------------------------------------------------------------------

const universityPolice: SeedAgency[] = [
  // UC System
  { agencyName: 'UC Berkeley Police Department', agencyType: 'University', county: 'Alameda', city: 'Berkeley', website: 'https://ucpd.berkeley.edu' },
  { agencyName: 'UCLA Police Department', agencyType: 'University', county: 'Los Angeles', city: 'Los Angeles', website: 'https://www.ucpd.ucla.edu' },
  { agencyName: 'UC San Diego Police Department', agencyType: 'University', county: 'San Diego', city: 'La Jolla' },
  { agencyName: 'UC Davis Police Department', agencyType: 'University', county: 'Yolo', city: 'Davis', website: 'https://police.ucdavis.edu' },
  { agencyName: 'UC Irvine Police Department', agencyType: 'University', county: 'Orange', city: 'Irvine' },
  { agencyName: 'UC Santa Barbara Police Department', agencyType: 'University', county: 'Santa Barbara', city: 'Santa Barbara' },
  { agencyName: 'UC Santa Cruz Police Department', agencyType: 'University', county: 'Santa Cruz', city: 'Santa Cruz' },
  { agencyName: 'UC Riverside Police Department', agencyType: 'University', county: 'Riverside', city: 'Riverside' },
  { agencyName: 'UC Merced Police Department', agencyType: 'University', county: 'Merced', city: 'Merced' },
  { agencyName: 'UC San Francisco Police Department', agencyType: 'University', county: 'San Francisco', city: 'San Francisco' },
  // CSU System
  { agencyName: 'CSU Long Beach Police Department', agencyType: 'University', county: 'Los Angeles', city: 'Long Beach' },
  { agencyName: 'CSU Fullerton Police Department', agencyType: 'University', county: 'Orange', city: 'Fullerton' },
  { agencyName: 'San Diego State University Police Department', agencyType: 'University', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'San Jose State University Police Department', agencyType: 'University', county: 'Santa Clara', city: 'San Jose' },
  { agencyName: 'CSU Northridge Police Department', agencyType: 'University', county: 'Los Angeles', city: 'Northridge' },
  { agencyName: 'Cal Poly San Luis Obispo Police Department', agencyType: 'University', county: 'San Luis Obispo', city: 'San Luis Obispo' },
  { agencyName: 'Cal Poly Pomona Police Department', agencyType: 'University', county: 'Los Angeles', city: 'Pomona' },
  { agencyName: 'CSU Sacramento Police Department', agencyType: 'University', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'Fresno State Police Department', agencyType: 'University', county: 'Fresno', city: 'Fresno' },
  { agencyName: 'CSU Bakersfield Police Department', agencyType: 'University', county: 'Kern', city: 'Bakersfield' },
  { agencyName: 'Humboldt State University Police Department', agencyType: 'University', county: 'Humboldt', city: 'Arcata' },
  { agencyName: 'Chico State University Police Department', agencyType: 'University', county: 'Butte', city: 'Chico' },
  { agencyName: 'San Francisco State University Police Department', agencyType: 'University', county: 'San Francisco', city: 'San Francisco' },
  { agencyName: 'CSU East Bay Police Department', agencyType: 'University', county: 'Alameda', city: 'Hayward' },
  { agencyName: 'CSU Stanislaus Police Department', agencyType: 'University', county: 'Stanislaus', city: 'Turlock' },
  { agencyName: 'CSU Dominguez Hills Police Department', agencyType: 'University', county: 'Los Angeles', city: 'Carson' },
  { agencyName: 'CSU Los Angeles Police Department', agencyType: 'University', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'CSU San Bernardino Police Department', agencyType: 'University', county: 'San Bernardino', city: 'San Bernardino' },
  { agencyName: 'CSU Monterey Bay Police Department', agencyType: 'University', county: 'Monterey', city: 'Seaside' },
  { agencyName: 'CSU Channel Islands Police Department', agencyType: 'University', county: 'Ventura', city: 'Camarillo' },
  { agencyName: 'Sonoma State University Police Department', agencyType: 'University', county: 'Sonoma', city: 'Rohnert Park' },
  { agencyName: 'CSU San Marcos Police Department', agencyType: 'University', county: 'San Diego', city: 'San Marcos' },
  // Private Universities with sworn police
  { agencyName: 'Stanford University Department of Public Safety', agencyType: 'University', county: 'Santa Clara', city: 'Stanford', website: 'https://police.stanford.edu' },
  { agencyName: 'University of Southern California Department of Public Safety', agencyType: 'University', county: 'Los Angeles', city: 'Los Angeles', website: 'https://dps.usc.edu' },
];

// ---------------------------------------------------------------------------
// Transit Police / Special Districts
// ---------------------------------------------------------------------------

const transitAndSpecial: SeedAgency[] = [
  { agencyName: 'Bay Area Rapid Transit Police Department', agencyType: 'Transit', county: 'Alameda', city: 'Oakland', website: 'https://www.bart.gov/about/police' },
  { agencyName: 'Los Angeles Metro Transit Security', agencyType: 'Transit', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'San Francisco Municipal Transportation Agency — Transit Security', agencyType: 'Transit', county: 'San Francisco', city: 'San Francisco' },
  { agencyName: 'Sacramento Regional Transit Police', agencyType: 'Transit', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'San Diego Metropolitan Transit System Security', agencyType: 'Transit', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'Amtrak Police — California District', agencyType: 'Transit', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'Port of Long Beach Police', agencyType: 'Transit', county: 'Los Angeles', city: 'Long Beach' },
  { agencyName: 'Port of Los Angeles Police', agencyType: 'Transit', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'Port of San Diego Harbor Police', agencyType: 'Transit', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'Port of Oakland Police', agencyType: 'Transit', county: 'Alameda', city: 'Oakland' },
  { agencyName: 'Los Angeles World Airports Police', agencyType: 'Transit', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'San Francisco International Airport Police', agencyType: 'Transit', county: 'San Mateo', city: 'San Francisco' },
];

// ---------------------------------------------------------------------------
// Probation Departments (major counties)
// ---------------------------------------------------------------------------

const probationDepartments: SeedAgency[] = [
  { agencyName: 'Los Angeles County Probation Department', agencyType: 'Probation', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'San Diego County Probation Department', agencyType: 'Probation', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'Orange County Probation Department', agencyType: 'Probation', county: 'Orange', city: 'Santa Ana' },
  { agencyName: 'Riverside County Probation Department', agencyType: 'Probation', county: 'Riverside', city: 'Riverside' },
  { agencyName: 'San Bernardino County Probation Department', agencyType: 'Probation', county: 'San Bernardino', city: 'San Bernardino' },
  { agencyName: 'Sacramento County Probation Department', agencyType: 'Probation', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'Alameda County Probation Department', agencyType: 'Probation', county: 'Alameda', city: 'Oakland' },
  { agencyName: 'Santa Clara County Probation Department', agencyType: 'Probation', county: 'Santa Clara', city: 'San Jose' },
  { agencyName: 'San Francisco Adult Probation Department', agencyType: 'Probation', county: 'San Francisco', city: 'San Francisco' },
  { agencyName: 'Contra Costa County Probation Department', agencyType: 'Probation', county: 'Contra Costa', city: 'Martinez' },
  { agencyName: 'Fresno County Probation Department', agencyType: 'Probation', county: 'Fresno', city: 'Fresno' },
  { agencyName: 'Kern County Probation Department', agencyType: 'Probation', county: 'Kern', city: 'Bakersfield' },
  { agencyName: 'San Joaquin County Probation Department', agencyType: 'Probation', county: 'San Joaquin', city: 'Stockton' },
  { agencyName: 'Ventura County Probation Agency', agencyType: 'Probation', county: 'Ventura', city: 'Ventura' },
  { agencyName: 'San Mateo County Probation Department', agencyType: 'Probation', county: 'San Mateo', city: 'Redwood City' },
  { agencyName: 'Stanislaus County Probation Department', agencyType: 'Probation', county: 'Stanislaus', city: 'Modesto' },
  { agencyName: 'Sonoma County Probation Department', agencyType: 'Probation', county: 'Sonoma', city: 'Santa Rosa' },
  { agencyName: 'Tulare County Probation Department', agencyType: 'Probation', county: 'Tulare', city: 'Visalia' },
  { agencyName: 'Santa Barbara County Probation Department', agencyType: 'Probation', county: 'Santa Barbara', city: 'Santa Barbara' },
  { agencyName: 'Monterey County Probation Department', agencyType: 'Probation', county: 'Monterey', city: 'Salinas' },
  { agencyName: 'Solano County Probation Department', agencyType: 'Probation', county: 'Solano', city: 'Fairfield' },
  { agencyName: 'Placer County Probation Department', agencyType: 'Probation', county: 'Placer', city: 'Auburn' },
  { agencyName: 'Marin County Probation Department', agencyType: 'Probation', county: 'Marin', city: 'San Rafael' },
  { agencyName: 'Santa Cruz County Probation Department', agencyType: 'Probation', county: 'Santa Cruz', city: 'Santa Cruz' },
  { agencyName: 'San Luis Obispo County Probation Department', agencyType: 'Probation', county: 'San Luis Obispo', city: 'San Luis Obispo' },
];

// ---------------------------------------------------------------------------
// Task Forces and Specialized Units
// ---------------------------------------------------------------------------

const taskForces: SeedAgency[] = [
  { agencyName: 'Los Angeles High Intensity Drug Trafficking Area (HIDTA)', agencyType: 'TaskForce', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'Central Valley HIDTA', agencyType: 'TaskForce', county: 'Fresno', city: 'Fresno' },
  { agencyName: 'Northern California HIDTA', agencyType: 'TaskForce', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'San Diego/Imperial Valley HIDTA', agencyType: 'TaskForce', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'Central California Intelligence Center (CCIC)', agencyType: 'TaskForce', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'Los Angeles Joint Regional Intelligence Center (JRIC)', agencyType: 'TaskForce', county: 'Los Angeles', city: 'Norwalk' },
  { agencyName: 'Northern California Regional Intelligence Center (NCRIC)', agencyType: 'TaskForce', county: 'San Francisco', city: 'San Francisco' },
  { agencyName: 'San Diego Law Enforcement Coordination Center (SD-LECC)', agencyType: 'TaskForce', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'California Department of Justice — Bureau of Narcotic Enforcement', agencyType: 'TaskForce', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'California Anti-Terrorism Information Center (CATIC)', agencyType: 'TaskForce', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'Internet Crimes Against Children Task Force — Los Angeles', agencyType: 'TaskForce', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'Internet Crimes Against Children Task Force — San Diego', agencyType: 'TaskForce', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'Internet Crimes Against Children Task Force — Sacramento Valley', agencyType: 'TaskForce', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'Internet Crimes Against Children Task Force — San Jose', agencyType: 'TaskForce', county: 'Santa Clara', city: 'San Jose' },
  { agencyName: 'Regional Auto Theft Task Force — Los Angeles', agencyType: 'TaskForce', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'Regional Auto Theft Task Force — Sacramento', agencyType: 'TaskForce', county: 'Sacramento', city: 'Sacramento' },
  { agencyName: 'Regional Auto Theft Task Force — San Diego-Imperial', agencyType: 'TaskForce', county: 'San Diego', city: 'San Diego' },
  { agencyName: 'California Gang Task Force', agencyType: 'TaskForce', county: 'Los Angeles', city: 'Los Angeles' },
  { agencyName: 'Inland Regional Narcotics Enforcement Team (IRNET)', agencyType: 'TaskForce', county: 'San Bernardino', city: 'San Bernardino' },
  { agencyName: 'Central Coast Narcotics Task Force', agencyType: 'TaskForce', county: 'San Luis Obispo', city: 'San Luis Obispo' },
];

// ---------------------------------------------------------------------------
// Export combined seed data
// ---------------------------------------------------------------------------

export const allCaliforniaAgencies: SeedAgency[] = [
  ...sheriffDepartments,
  ...policeDepartments,
  ...stateAgencies,
  ...districtAttorneyBureaus,
  ...universityPolice,
  ...transitAndSpecial,
  ...probationDepartments,
  ...taskForces,
];
