import { chromium } from 'playwright';
const BASE='http://localhost:8090'; const OUT='reports/screenshots/shell-p84';
const b=await chromium.launch(); const pg=await b.newPage({viewport:{width:1440,height:1000}});
const errs=[]; pg.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,90));});
await pg.goto(BASE+'/login',{waitUntil:'networkidle'});
await pg.fill('input[type=email]','attorney2@courtaccess.test');await pg.fill('input[type=password]','TestPass123!');await pg.click('button[type=submit]');await pg.waitForTimeout(3500);
await pg.goto(BASE+'/dashboard',{waitUntil:'networkidle',timeout:20000}).catch(()=>{});await pg.waitForTimeout(2500);
await pg.screenshot({path:OUT+'/dashboard-shell.png'});
await pg.goto(BASE+'/cases',{waitUntil:'networkidle',timeout:20000}).catch(()=>{});await pg.waitForTimeout(1800);
await pg.screenshot({path:OUT+'/cases-shell.png'});
console.log('shell shots');
await b.close();console.log('CONSOLE_ERRORS',errs.length);errs.slice(0,6).forEach(e=>console.log('  ',e));
