import { chromium } from 'playwright';
const BASE='http://localhost:8090'; const OUT='reports/screenshots/witness'; const CID='46f6002a-cb7b-4ad5-a3bc-967c88eeebe7';
const b=await chromium.launch(); const pg=await b.newPage({viewport:{width:1440,height:1150}});
const errs=[]; pg.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,90));});
await pg.goto(BASE+'/login',{waitUntil:'networkidle'});
await pg.fill('input[type=email]','attorney2@courtaccess.test');await pg.fill('input[type=password]','TestPass123!');await pg.click('button[type=submit]');await pg.waitForTimeout(3500);
await pg.goto(BASE+'/cases/'+CID+'/witnesses',{waitUntil:'networkidle',timeout:25000}).catch(()=>{});await pg.waitForTimeout(2800);
await pg.screenshot({path:OUT+'/witness-home.png',fullPage:true});
console.log('witness shot');
await b.close();console.log('CONSOLE_ERRORS',errs.length);errs.slice(0,6).forEach(e=>console.log('  ',e));
