import { chromium } from 'playwright';
const BASE='http://localhost:8090'; const OUT='reports/screenshots/workbench';
const CID='edfce74b-b3fd-4c9f-b799-a553daf32df9';
const b=await chromium.launch(); const pg=await b.newPage({viewport:{width:1440,height:1250}});
const errs=[]; pg.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,90));});
await pg.goto(BASE+'/login',{waitUntil:'networkidle'});
await pg.fill('input[type=email]','attorney2@courtaccess.test');await pg.fill('input[type=password]','TestPass123!');await pg.click('button[type=submit]');await pg.waitForTimeout(3500);
await pg.goto(BASE+'/cases/'+CID+'/attorney-workbench',{waitUntil:'networkidle',timeout:25000}).catch(()=>{});await pg.waitForTimeout(3000);
await pg.screenshot({path:OUT+'/workbench-home.png',fullPage:true});
console.log('home shot');
await b.close();console.log('CONSOLE_ERRORS',errs.length);errs.slice(0,6).forEach(e=>console.log('  ',e));
