import { chromium } from 'playwright';
const U='https://networking-editor-dated-comment.trycloudflare.com';
const OUT='/workspace/reports/screenshots/p95';
const CID='edfce74b-b3fd-4c9f-b799-a553daf32df9';
const b=await chromium.launch();
const pg=await b.newPage({viewport:{width:1440,height:1000}});
const errs=[]; pg.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,100));});
pg.on('pageerror',e=>errs.push('PAGEERR '+e.message.slice(0,100)));
const R=[];
await pg.goto(U+'/login',{waitUntil:'networkidle',timeout:40000});await pg.waitForTimeout(1200);
await pg.fill('input[type=email]','attorney2@courtaccess.test');await pg.fill('input[type=password]','TestPass123!');await pg.click('button[type=submit]');await pg.waitForTimeout(4000);
R.push('login: '+(pg.url().includes('/login')?'FAILED':'ok'));
const r=await pg.goto(`${U}/cases/${CID}/attorney-workbench`,{waitUntil:'networkidle',timeout:40000});
await pg.waitForTimeout(4500);
const body=await pg.$eval('body',el=>el.innerText).catch(()=>'');
const has=(s)=>new RegExp(s,'i').test(body);
R.push(`workbench: HTTP ${r?.status()}`);
R.push('sections: metrics='+has('Executive Metrics')+' quick='+has('Quick Actions')+' intel='+has('Litigation Intelligence')+' feed='+has('Live Intelligence Feed')+' notes='+has('Attorney Notes')+' detail='+has('Detailed Litigation Analysis'));
R.push('panels: '+['Evidence Intelligence','Witness Intelligence','Discovery Intelligence','Timeline Intelligence','Contradiction Intelligence','Motion Intelligence','CALCRIM Intelligence','Sentencing Intelligence','CourtListener Intelligence','Authority Intelligence'].filter(p=>has(p)).length+'/10');
await pg.screenshot({path:`${OUT}/workbench.png`});
await pg.screenshot({path:`${OUT}/workbench-full.png`,fullPage:true});
// Verify a quick action navigates (Motion Builder)
await pg.$$eval('button', els=>{const el=[...els].find(e=>/Motion Builder/.test(e.textContent));if(el)el.click();});
await pg.waitForTimeout(3500);
R.push('quick-action Motion Builder → '+(pg.url().includes('/motions')?'navigated OK':'FAILED ('+pg.url()+')'));
await b.close();
console.log(R.join('\n'));
console.log('CONSOLE_ERRORS: '+errs.length);
errs.slice(0,10).forEach(e=>console.log('  '+e));
