// ============================================
// Court Access — POST LD-15 Doctrine Seed Data
// Pre-extracted doctrine rules from POST
// Learning Domain 15: Laws of Arrest (V5.0)
// ============================================

import type { ParsedDoctrineChunk } from './types.ts';

// ---------------------------------------------------------------------------
// Extracted Doctrine Rules from POST LD-15 v5.0
// These rules are structured from the manual's key doctrine sections.
// ---------------------------------------------------------------------------

export const LD15_DOCTRINE_RULES: ParsedDoctrineChunk[] = [
  // =========================================================================
  // CHAPTER: Constitutional Protections
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Fourth Amendment',
    rule: 'The Fourth Amendment protects individuals from unreasonable searches and seizures by the government.',
    explanation: 'This protection applies to all government agents, including peace officers. Any search or seizure must be reasonable under the circumstances.',
    legalImplication: 'Evidence obtained through an unreasonable search or seizure is subject to the exclusionary rule and may be suppressed at trial.',
    category: 'constitutional',
    keywords: ['fourth amendment', 'search', 'seizure', 'unreasonable', 'exclusionary rule'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Fifth Amendment',
    rule: 'The Fifth Amendment protects individuals from being compelled to be witnesses against themselves in criminal cases.',
    explanation: 'This right against self-incrimination applies during custodial interrogations and is the constitutional basis for Miranda warnings.',
    legalImplication: 'Compelled self-incriminating statements are inadmissible. Failure to respect this right may result in suppression of statements.',
    category: 'constitutional',
    keywords: ['fifth amendment', 'self-incrimination', 'miranda', 'custodial', 'interrogation'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Sixth Amendment',
    rule: 'The Sixth Amendment guarantees the right to counsel in all criminal prosecutions.',
    explanation: 'Once formal charges have been filed, the accused has the right to have an attorney present during any critical stage of the proceedings, including interrogation.',
    legalImplication: 'Deliberately eliciting statements from a charged defendant outside the presence of counsel may violate the Sixth Amendment.',
    category: 'constitutional',
    keywords: ['sixth amendment', 'right to counsel', 'attorney', 'criminal prosecution'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Fourteenth Amendment',
    rule: 'The Fourteenth Amendment requires equal protection under the law and prohibits discriminatory enforcement.',
    explanation: 'Officers must not base enforcement decisions on race, ethnicity, gender, or other protected characteristics. All persons are entitled to equal treatment.',
    legalImplication: 'Discriminatory enforcement may result in civil rights violations, civil liability, and criminal prosecution of officers.',
    category: 'constitutional',
    keywords: ['fourteenth amendment', 'equal protection', 'due process', 'discrimination'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Exclusionary Rule',
    rule: 'The exclusionary rule requires that evidence obtained in violation of the Constitution must be suppressed.',
    explanation: 'This rule is designed to deter unlawful police conduct by removing the incentive to violate constitutional rights. It applies to evidence directly obtained and evidence derived from the violation.',
    legalImplication: 'Evidence obtained through constitutional violations is inadmissible, and all derivative evidence may also be suppressed under the fruit of the poisonous tree doctrine.',
    category: 'constitutional',
    keywords: ['exclusionary rule', 'suppression', 'fruit of the poisonous tree', 'evidence'],
  },

  // =========================================================================
  // CHAPTER: Consensual Encounters
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Consensual Encounters',
    topic: 'Consensual Encounters',
    rule: 'A consensual encounter occurs when an officer contacts an individual without exerting authority or control. No reasonable suspicion is required.',
    explanation: 'During a consensual encounter, the person is free to leave at any time and is not obligated to answer questions or provide identification.',
    legalImplication: 'If encounter is determined non-consensual, it becomes a detention requiring reasonable suspicion. Evidence may be suppressed if reasonable suspicion is lacking.',
    category: 'encounter',
    keywords: ['consensual encounter', 'voluntary contact', 'consent', 'free to leave'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Consensual Encounters',
    topic: 'Consensual Encounters',
    rule: 'An officer must not use commands, physical force, sirens, or other displays of authority that would cause a reasonable person to believe they are not free to leave.',
    explanation: 'Actions such as blocking a path, activating emergency lights, drawing a weapon, or using an authoritative tone may elevate an encounter to a detention.',
    legalImplication: 'If encounter is determined non-consensual, it becomes a detention requiring reasonable suspicion.',
    category: 'encounter',
    keywords: ['consensual encounter', 'free to leave', 'authority', 'detention'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Consensual Encounters',
    topic: 'Consensual Encounters',
    rule: 'Consent to search must be voluntary and not the result of coercion, duress, or submission to authority.',
    explanation: 'An officer may request consent to search during a consensual encounter. The person has the right to refuse and to withdraw consent at any time.',
    legalImplication: 'Evidence obtained through coerced consent is subject to suppression. The prosecution bears the burden of proving voluntariness.',
    category: 'encounter',
    keywords: ['consent', 'voluntary', 'consent search', 'coercion'],
  },

  // =========================================================================
  // CHAPTER: Detentions
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'A lawful detention requires reasonable suspicion that criminal activity may be occurring and the person detained is connected to that activity.',
    explanation: 'Reasonable suspicion exists when an officer has specific, articulable facts that, combined with rational inferences, lead to a reasonable belief that criminal activity is afoot.',
    legalImplication: 'If reasonable suspicion cannot be articulated, evidence obtained during the detention may be suppressed.',
    category: 'detention',
    keywords: ['reasonable suspicion', 'detention', 'articulable facts', 'criminal activity'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'Reasonable suspicion cannot be based on a mere hunch, gut feeling, or unparticularized suspicion.',
    explanation: 'The officer must be able to point to specific facts and circumstances that justify the detention. General impressions or feelings are insufficient.',
    legalImplication: 'A detention based on a mere hunch is unlawful, and any evidence obtained as a result may be suppressed.',
    category: 'detention',
    keywords: ['reasonable suspicion', 'hunch', 'gut feeling', 'specific facts'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Detention Duration',
    rule: 'A detention must be temporary and last no longer than necessary to carry out the purpose of the stop.',
    explanation: 'Officers must diligently pursue the investigation during the detention. Unreasonable delays or extending the stop beyond its original purpose may render the detention unlawful.',
    legalImplication: 'An unreasonably prolonged detention may be deemed an unlawful seizure, and evidence obtained after the point of unreasonable delay may be suppressed.',
    category: 'detention',
    keywords: ['detention', 'duration', 'temporary', 'reasonable', 'prolonged'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Investigative Detention',
    rule: 'During a lawful detention, an officer may ask questions, request identification, and conduct limited investigation related to the suspected criminal activity.',
    explanation: 'The scope of the investigation must be reasonably related to the circumstances that justified the detention. Unrelated questioning may extend the stop unlawfully.',
    legalImplication: 'Evidence obtained through investigation unrelated to the basis for the stop may be suppressed if it unreasonably extended the detention.',
    category: 'detention',
    keywords: ['detention', 'investigation', 'questioning', 'identification', 'scope'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Terry Stops',
    rule: 'A Terry stop is a brief investigative detention based on reasonable suspicion. The officer may briefly detain the person to confirm or dispel the suspicion.',
    explanation: 'Named after Terry v. Ohio (1968), this type of stop allows officers to make brief investigative stops without probable cause, provided reasonable suspicion exists.',
    legalImplication: 'If the officer cannot articulate reasonable suspicion, the stop violates the Fourth Amendment and evidence may be suppressed.',
    category: 'detention',
    keywords: ['terry stop', 'reasonable suspicion', 'investigative detention', 'fourth amendment'],
  },

  // =========================================================================
  // CHAPTER: Searches
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Pat Searches',
    rule: 'A pat search during detention is limited to the outer clothing and is permitted only when the officer has reasonable belief the person may be armed and dangerous.',
    explanation: 'The purpose of a pat search is officer safety, not evidence discovery. The officer must be able to articulate specific facts creating a reasonable belief of danger.',
    legalImplication: 'A pat search without reasonable belief of danger is unlawful. Evidence discovered during an unjustified pat search may be suppressed.',
    category: 'search',
    keywords: ['pat search', 'frisk', 'outer clothing', 'armed', 'dangerous', 'officer safety'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Plain Feel Doctrine',
    rule: 'Under the plain feel doctrine, an officer conducting a lawful pat search may seize contraband if its identity is immediately apparent through touch without further manipulation.',
    explanation: 'The officer must not squeeze, slide, or manipulate an object to determine its identity. The contraband nature must be immediately apparent during the lawful pat search.',
    legalImplication: 'Evidence seized through manipulation beyond the scope of a pat search may be suppressed under the exclusionary rule.',
    category: 'search',
    keywords: ['plain feel', 'pat search', 'contraband', 'immediately apparent', 'manipulation'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Consent Searches',
    rule: 'An officer may conduct a search based on voluntary consent given by a person with authority over the area to be searched.',
    explanation: 'Consent must be freely and voluntarily given, not obtained through coercion, threats, or deception. The person may limit the scope or withdraw consent at any time.',
    legalImplication: 'If consent is found to be involuntary or coerced, the search is unlawful and evidence may be suppressed.',
    category: 'search',
    keywords: ['consent search', 'voluntary', 'authority', 'coercion', 'withdraw'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Search Incident to Arrest',
    rule: 'A search incident to a lawful arrest allows an officer to search the person and the area within the arrestee\'s immediate control.',
    explanation: 'This exception to the warrant requirement is justified by officer safety and prevention of evidence destruction. The arrest must be lawful for the search to be valid.',
    legalImplication: 'If the underlying arrest is unlawful, the search incident to arrest is also unlawful and evidence may be suppressed.',
    category: 'search',
    keywords: ['search incident to arrest', 'immediate control', 'officer safety', 'evidence destruction'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Warrant Requirements',
    rule: 'A search warrant must be supported by probable cause and particularly describe the place to be searched and the persons or things to be seized.',
    explanation: 'The Fourth Amendment requires warrants to be issued by a neutral magistrate based on sworn affidavits establishing probable cause.',
    legalImplication: 'Searches conducted without a valid warrant or recognized exception to the warrant requirement may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['warrant', 'probable cause', 'fourth amendment', 'magistrate', 'particularity'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Plain View Doctrine',
    rule: 'An officer may seize evidence in plain view if the officer is lawfully present, the incriminating nature of the item is immediately apparent, and the officer has lawful access to the object.',
    explanation: 'The plain view doctrine allows seizure without a warrant when the officer discovers evidence or contraband while lawfully in a position to observe it.',
    legalImplication: 'If any element of the plain view doctrine is not met, the seizure may be unlawful and the evidence suppressed.',
    category: 'search',
    keywords: ['plain view', 'seizure', 'lawfully present', 'immediately apparent'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Exigent Circumstances',
    rule: 'Exigent circumstances may justify a warrantless search when there is an immediate threat of evidence destruction, hot pursuit, or danger to life.',
    explanation: 'This exception applies in emergency situations where obtaining a warrant is impractical. The circumstances must be objectively reasonable.',
    legalImplication: 'If the claimed exigent circumstances are not supported by the facts, the warrantless search is unlawful.',
    category: 'search',
    keywords: ['exigent circumstances', 'warrantless', 'emergency', 'evidence destruction', 'hot pursuit'],
  },

  // =========================================================================
  // CHAPTER: Arrests
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Probable Cause',
    rule: 'Probable cause is required before an arrest may be made. It exists when facts and circumstances would lead a reasonable person to believe a crime has been or is being committed.',
    explanation: 'Probable cause is a higher standard than reasonable suspicion but lower than proof beyond a reasonable doubt. It must be based on objective facts, not subjective beliefs.',
    legalImplication: 'An arrest without probable cause is unlawful; all evidence obtained as a result may be suppressed under the exclusionary rule.',
    category: 'arrest',
    keywords: ['probable cause', 'arrest', 'reasonable person', 'crime'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Warrantless Arrests',
    rule: 'A peace officer may make a warrantless arrest for a felony based on probable cause, or for a misdemeanor committed in the officer\'s presence.',
    explanation: 'California Penal Code sections 836 and 836.5 authorize warrantless arrests under specific circumstances. The officer must have probable cause to believe the person committed the offense.',
    legalImplication: 'A warrantless arrest without proper legal authority or probable cause is unlawful and may result in civil liability and evidence suppression.',
    category: 'arrest',
    keywords: ['warrantless arrest', 'felony', 'misdemeanor', 'probable cause', 'penal code'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Probable Cause',
    rule: 'An officer must be able to articulate the specific facts that established probable cause at the time of the arrest.',
    explanation: 'The officer cannot rely on information learned after the arrest to justify the arrest. Probable cause must exist at the moment the arrest is made.',
    legalImplication: 'Failure to articulate probable cause at the time of arrest may result in the arrest being declared unlawful.',
    category: 'arrest',
    keywords: ['probable cause', 'articulable facts', 'arrest', 'specific facts'],
  },

  // =========================================================================
  // CHAPTER: Miranda
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Warnings',
    rule: 'Miranda warnings must be given before any custodial interrogation. The warnings must inform the suspect of the right to remain silent and the right to an attorney.',
    explanation: 'Custodial interrogation occurs when a person is in custody and subjected to questioning or its functional equivalent by law enforcement. Both elements must be present.',
    legalImplication: 'Failure to administer Miranda warnings before custodial interrogation renders statements inadmissible in the prosecution\'s case-in-chief.',
    category: 'miranda',
    keywords: ['miranda', 'custodial interrogation', 'right to remain silent', 'right to counsel', 'warnings'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Warnings',
    rule: 'A suspect must be informed of four specific rights: the right to remain silent, that anything said can be used against them, the right to an attorney, and the right to an appointed attorney if unable to afford one.',
    explanation: 'All four components must be communicated. The warnings need not follow an exact script but must convey the substance of each right.',
    legalImplication: 'Incomplete or inadequate Miranda warnings may result in suppression of the suspect\'s statements.',
    category: 'miranda',
    keywords: ['miranda', 'right to remain silent', 'right to counsel', 'appointed attorney', 'warnings'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Waiver',
    rule: 'A valid Miranda waiver must be voluntary, knowing, and intelligent. The suspect must understand the rights being waived and voluntarily choose to waive them.',
    explanation: 'A waiver cannot be presumed from silence or from the fact that the suspect eventually answered questions. The totality of circumstances determines validity.',
    legalImplication: 'Statements obtained after an invalid or coerced waiver are inadmissible.',
    category: 'miranda',
    keywords: ['miranda', 'waiver', 'voluntary', 'knowing', 'intelligent'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Warnings',
    rule: 'If a suspect invokes the right to remain silent, all questioning must cease immediately.',
    explanation: 'Once a suspect clearly and unambiguously invokes the right to silence, the officer must stop the interrogation. Questioning may resume only after a significant period of time and fresh Miranda warnings.',
    legalImplication: 'Continued questioning after invocation of the right to silence violates Miranda, and all subsequent statements are inadmissible.',
    category: 'miranda',
    keywords: ['miranda', 'right to remain silent', 'invoke', 'cease questioning'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Warnings',
    rule: 'If a suspect requests an attorney, all interrogation must stop until an attorney is present or the suspect re-initiates communication.',
    explanation: 'The request for an attorney must be clear and unambiguous. Once made, the officer cannot attempt to persuade the suspect to change their mind.',
    legalImplication: 'Statements obtained after a suspect requests an attorney, without counsel present, are inadmissible unless the suspect voluntarily re-initiates.',
    category: 'miranda',
    keywords: ['miranda', 'right to counsel', 'attorney', 'interrogation', 'invoke'],
  },

  // =========================================================================
  // CHAPTER: Interrogations
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Interrogations',
    topic: 'Custodial Interrogation',
    rule: 'Custodial interrogation is any questioning initiated by law enforcement after a person has been taken into custody or otherwise deprived of freedom in a significant way.',
    explanation: 'The test for custody is whether a reasonable person in the suspect\'s position would feel free to terminate the encounter and leave.',
    legalImplication: 'If a person is determined to be in custody, Miranda warnings are required before any interrogation.',
    category: 'interrogation',
    keywords: ['custodial', 'interrogation', 'custody', 'questioning', 'freedom'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogations',
    topic: 'Custodial Interrogation',
    rule: 'An officer must not use coercion, threats, promises of leniency, or physical force to obtain statements from a suspect.',
    explanation: 'Coercive techniques include physical violence, threats of harm, deprivation of necessities, extended isolation, and promises of specific outcomes.',
    legalImplication: 'Statements obtained through coercive interrogation techniques are inadmissible under both the Fifth Amendment and the Due Process Clause.',
    category: 'interrogation',
    keywords: ['coercion', 'interrogation', 'threats', 'force', 'inadmissible', 'due process'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogations',
    topic: 'Custodial Interrogation',
    rule: 'The voluntariness of a confession is determined by examining the totality of the circumstances surrounding the interrogation.',
    explanation: 'Factors include the length of interrogation, whether the suspect was provided food and rest, the suspect\'s age and education, and the nature of the questioning.',
    legalImplication: 'An involuntary confession violates due process and is inadmissible regardless of whether Miranda warnings were given.',
    category: 'interrogation',
    keywords: ['confession', 'voluntary', 'totality of circumstances', 'due process', 'interrogation'],
  },

  // =========================================================================
  // Additional Doctrine Rules (from manual cross-references)
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Vehicle Searches',
    rule: 'Under the automobile exception, officers may search a vehicle without a warrant if there is probable cause to believe it contains evidence of a crime.',
    explanation: 'The automobile exception is based on the reduced expectation of privacy in vehicles and the inherent mobility of vehicles.',
    legalImplication: 'A vehicle search without probable cause or another recognized exception may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['vehicle search', 'automobile exception', 'probable cause', 'warrant', 'fourth amendment'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'An officer may consider the totality of the circumstances in determining whether reasonable suspicion exists, including the location, time of day, and the suspect\'s behavior.',
    explanation: 'No single factor is determinative. Courts evaluate the collective weight of all circumstances known to the officer at the time.',
    legalImplication: 'Reliance on a single factor (such as presence in a high-crime area) without additional articulable facts is insufficient to establish reasonable suspicion.',
    category: 'detention',
    keywords: ['reasonable suspicion', 'totality of circumstances', 'detention', 'articulable facts'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Probable Cause',
    rule: 'Information from a reliable informant can contribute to probable cause, but must be corroborated by independent investigation.',
    explanation: 'The reliability of the informant and the basis of the informant\'s knowledge are factors in determining whether the information establishes probable cause.',
    legalImplication: 'Reliance on uncorroborated tips from unknown informants may be insufficient to establish probable cause.',
    category: 'arrest',
    keywords: ['probable cause', 'informant', 'corroboration', 'reliable', 'investigation'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Fruit of the Poisonous Tree',
    rule: 'Evidence derived from an initial constitutional violation is also subject to exclusion under the fruit of the poisonous tree doctrine.',
    explanation: 'If the initial police action (the tree) is unlawful, all evidence discovered as a result (the fruit) is tainted and inadmissible, unless an exception applies.',
    legalImplication: 'Derivative evidence may be suppressed unless the prosecution can show it falls under the independent source, inevitable discovery, or attenuation exceptions.',
    category: 'constitutional',
    keywords: ['fruit of the poisonous tree', 'exclusionary rule', 'derivative evidence', 'suppression'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'Reasonable suspicion must be based on objective facts, not on a person\'s race, ethnicity, national origin, gender, or other protected characteristic.',
    explanation: 'Detentions based on racial profiling or other discriminatory criteria are unlawful regardless of whether criminal activity is ultimately discovered.',
    legalImplication: 'A detention based on racial profiling violates both the Fourth and Fourteenth Amendments and may result in suppression and civil liability.',
    category: 'detention',
    keywords: ['reasonable suspicion', 'racial profiling', 'discrimination', 'fourth amendment', 'fourteenth amendment'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Pat Searches',
    rule: 'An officer cannot conduct a pat search based solely on the fact that the person is in a high-crime area.',
    explanation: 'Location alone does not establish reasonable belief that a person is armed and dangerous. Additional articulable facts are required.',
    legalImplication: 'A pat search based solely on location is unlawful and evidence discovered may be suppressed.',
    category: 'search',
    keywords: ['pat search', 'high-crime area', 'armed', 'dangerous', 'articulable facts'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Warnings',
    rule: 'Public safety exception: Officers may ask questions reasonably prompted by concern for public safety without first administering Miranda warnings.',
    explanation: 'In situations involving an immediate threat to public safety (e.g., locating a discarded weapon), brief questioning may occur without Miranda. This is a narrow exception.',
    legalImplication: 'The public safety exception is narrowly construed. Extensive questioning beyond the immediate safety concern requires Miranda warnings.',
    category: 'miranda',
    keywords: ['miranda', 'public safety exception', 'immediate threat', 'questioning'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Probable Cause',
    rule: 'Probable cause may be established through an officer\'s own observations, information from witnesses or victims, physical evidence, or a combination of these sources.',
    explanation: 'The totality of information available to the officer at the time of the arrest determines whether probable cause exists.',
    legalImplication: 'An arrest based on insufficient or unreliable information may lack probable cause and be deemed unlawful.',
    category: 'arrest',
    keywords: ['probable cause', 'observations', 'witnesses', 'physical evidence', 'arrest'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogations',
    topic: 'Custodial Interrogation',
    rule: 'Routine booking questions are generally not considered interrogation and do not require Miranda warnings.',
    explanation: 'Questions related to name, address, date of birth, and other biographical information asked during booking are administrative, not investigative.',
    legalImplication: 'If booking questions are designed to elicit incriminating responses, they may be considered interrogation requiring Miranda warnings.',
    category: 'interrogation',
    keywords: ['booking', 'routine questions', 'miranda', 'interrogation', 'administrative'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Investigative Detention',
    rule: 'An officer may move a detained person a reasonable distance for identification purposes during an investigative detention.',
    explanation: 'Moving a suspect to a nearby location for a witness show-up or identification is permissible if the distance is reasonable and the detention is not unduly prolonged.',
    legalImplication: 'Moving a detained person an unreasonable distance may convert the detention into a de facto arrest requiring probable cause.',
    category: 'detention',
    keywords: ['detention', 'identification', 'show-up', 'reasonable distance', 'de facto arrest'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Consent Searches',
    rule: 'An officer must not claim or imply that a warrant will be obtained if consent is refused, unless the officer actually intends to seek a warrant.',
    explanation: 'Threatening to obtain a warrant to coerce consent renders the consent involuntary.',
    legalImplication: 'Consent obtained through false claims about warrants is involuntary and the resulting search is unlawful.',
    category: 'search',
    keywords: ['consent search', 'voluntary', 'warrant', 'coercion', 'involuntary'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Probable Cause',
    rule: 'An officer must not arrest a person solely for exercising their constitutional rights, including the right to refuse consent to a search.',
    explanation: 'Refusal to consent to a search cannot be used as evidence of guilt or as a basis for arrest. Citizens have the constitutional right to refuse searches.',
    legalImplication: 'An arrest based on the exercise of constitutional rights is unlawful and may result in civil rights liability.',
    category: 'arrest',
    keywords: ['arrest', 'constitutional rights', 'consent', 'refusal', 'civil rights'],
  },
  // Additional rules for broader coverage
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'Flight from police, when combined with other factors, may contribute to reasonable suspicion but cannot alone justify a detention.',
    explanation: 'While unprovoked flight in a high-crime area may be considered, flight alone in an ordinary neighborhood is insufficient for detention.',
    legalImplication: 'A detention based solely on flight, without additional articulable factors, may be found unlawful.',
    category: 'detention',
    keywords: ['reasonable suspicion', 'flight', 'evasion', 'detention', 'high-crime area'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Search Incident to Arrest',
    rule: 'A search incident to arrest of a vehicle occupant is limited to the passenger compartment and only when the arrestee could access the vehicle or evidence of the crime of arrest may be found.',
    explanation: 'Per Arizona v. Gant, the search is limited when the arrestee is secured and cannot access the vehicle. A broader search requires probable cause.',
    legalImplication: 'Searching a vehicle beyond the scope permitted by Gant without probable cause may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['search incident to arrest', 'vehicle', 'passenger compartment', 'Gant', 'fourth amendment'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Warnings',
    rule: 'Spontaneous statements made without interrogation are admissible even without Miranda warnings.',
    explanation: 'Miranda only applies to custodial interrogation. Voluntary, unsolicited statements made by a suspect are not subject to Miranda requirements.',
    legalImplication: 'Spontaneous statements are admissible. However, if the statement was prompted by police questioning or its functional equivalent, Miranda applies.',
    category: 'miranda',
    keywords: ['miranda', 'spontaneous statements', 'voluntary', 'interrogation', 'admissible'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogations',
    topic: 'Custodial Interrogation',
    rule: 'Officers must not continue questioning a juvenile suspect who has requested to speak with a parent or guardian.',
    explanation: 'Juveniles are afforded additional protections during interrogation. The request to speak with a parent is treated similarly to invoking the right to counsel.',
    legalImplication: 'Statements obtained from a juvenile after they request a parent may be inadmissible.',
    category: 'interrogation',
    keywords: ['juvenile', 'interrogation', 'parent', 'guardian', 'custodial', 'miranda'],
  },
];

/**
 * Total number of seed rules.
 */
export const SEED_RULE_COUNT = LD15_DOCTRINE_RULES.length;
