// ============================================
// POST LD-30: Crime Scene Investigation — Expansion
// Additional doctrine rules to reach ~80 total
// ============================================

import type { ParsedDoctrineChunk } from './types.ts';

export const LD30_EXPANSION_RULES: ParsedDoctrineChunk[] = [
  // =========================================================================
  // CHAPTER: Crime Scene Security
  // =========================================================================
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Security',
    topic: 'Initial Scene Response',
    rule: 'The first officer on scene must establish scene security by identifying and securing the boundaries of the crime scene before any investigative activity begins.',
    explanation: 'Scene security prevents contamination and loss of evidence. The officer must balance scene security with rendering aid to victims.',
    legalImplication: 'Failure to secure the scene may result in evidence contamination that undermines prosecution.',
    category: 'crime_scene',
    keywords: ['scene security', 'first responder', 'boundaries', 'contamination'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Security',
    topic: 'Scene Perimeter',
    rule: 'The crime scene perimeter should be established larger than initially appears necessary and can be reduced later, but expanding a perimeter after contamination has occurred cannot undo the damage.',
    explanation: 'It is always easier to reduce a perimeter than to expand it. The initial perimeter should include all potential evidence areas plus buffer zones.',
    legalImplication: 'An inadequate perimeter that allows evidence contamination may result in challenged or excluded evidence.',
    category: 'crime_scene',
    keywords: ['perimeter', 'crime scene', 'buffer zone', 'contamination prevention'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Security',
    topic: 'Scene Log',
    rule: 'A crime scene log must be maintained documenting every person who enters and exits the scene, including their name, agency, purpose, and times of entry and exit.',
    explanation: 'The scene log establishes chain of custody for the scene itself and helps identify potential sources of contamination.',
    legalImplication: 'Failure to maintain a scene log may undermine the integrity of evidence collected and create chain of custody challenges.',
    category: 'crime_scene',
    keywords: ['scene log', 'entry log', 'chain of custody', 'documentation'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Security',
    topic: 'Scene Contamination Prevention',
    rule: 'Officers must wear appropriate personal protective equipment (PPE) including gloves, shoe covers, and hair coverings to prevent contamination of the crime scene with their own DNA or trace evidence.',
    explanation: 'Cross-contamination from officers is a significant concern. PPE protects both the evidence and the officer from biohazards.',
    legalImplication: 'DNA contamination from officers may compromise forensic evidence and create reasonable doubt.',
    category: 'crime_scene',
    keywords: ['PPE', 'contamination', 'DNA', 'trace evidence', 'protective equipment'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Security',
    topic: 'Multi-Scene Management',
    rule: 'When a crime involves multiple scenes, each scene must be independently secured and processed, with coordination between scene commanders to prevent cross-contamination.',
    explanation: 'Officers who process one scene should not process another related scene without changing PPE to prevent transfer of evidence between scenes.',
    legalImplication: 'Cross-contamination between related crime scenes may compromise evidence from all scenes.',
    category: 'crime_scene',
    keywords: ['multiple scenes', 'cross-contamination', 'coordination', 'scene management'],
  },

  // =========================================================================
  // CHAPTER: Crime Scene Documentation
  // =========================================================================
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Documentation',
    topic: 'Photography Documentation',
    rule: 'Crime scene photography must follow a systematic approach: overall scene photos, mid-range photos showing relationships between evidence, and close-up photos of individual items with and without scale indicators.',
    explanation: 'The three-level approach ensures comprehensive documentation. Photos should be taken before any evidence is moved or collected.',
    legalImplication: 'Inadequate photography may result in inability to reconstruct the scene and may weaken the prosecution\'s case.',
    category: 'crime_scene',
    keywords: ['photography', 'documentation', 'overall', 'mid-range', 'close-up', 'scale'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Documentation',
    topic: 'Video Documentation',
    rule: 'Video documentation of the crime scene should supplement still photography, providing a continuous visual record that captures spatial relationships and scene conditions.',
    explanation: 'Video provides context that still photos may not capture. The videographer should narrate conditions and follow a systematic path through the scene.',
    legalImplication: 'Video documentation strengthens the prosecution\'s ability to present the scene context to a jury.',
    category: 'crime_scene',
    keywords: ['video', 'documentation', 'spatial relationships', 'narration'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Documentation',
    topic: 'Sketching and Measurements',
    rule: 'A crime scene sketch with accurate measurements must be prepared showing the location of all evidence items, their relationship to fixed reference points, and the overall layout of the scene.',
    explanation: 'Sketches complement photographs by providing precise spatial data. Measurements should be taken using at least two fixed reference points for each item.',
    legalImplication: 'Inaccurate measurements may lead to incorrect scene reconstruction and may be challenged in court.',
    category: 'crime_scene',
    keywords: ['sketch', 'measurements', 'reference points', 'spatial data', 'layout'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Documentation',
    topic: 'Notes and Reports',
    rule: 'Detailed field notes must be taken contemporaneously at the crime scene, documenting observations, conditions, actions taken, and the sequence of events.',
    explanation: 'Field notes serve as the foundation for the crime scene report. They should include date, time, weather, lighting conditions, and names of all personnel.',
    legalImplication: 'Contemporaneous notes carry significant weight in court and their absence may undermine testimony.',
    category: 'crime_scene',
    keywords: ['field notes', 'contemporaneous', 'observations', 'conditions', 'report'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Crime Scene Documentation',
    topic: 'Evidence Markers',
    rule: 'Evidence items must be marked with numbered placards before photography and collection, with each marker corresponding to an entry in the evidence log.',
    explanation: 'Systematic marking ensures every item is documented and collected. Markers should be placed near but not touching the evidence.',
    legalImplication: 'Failure to properly mark evidence may create confusion about the origin and location of items.',
    category: 'crime_scene',
    keywords: ['evidence markers', 'placards', 'numbering', 'evidence log'],
  },

  // =========================================================================
  // CHAPTER: Evidence Collection Techniques
  // =========================================================================
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Collection Order',
    rule: 'Evidence should be collected in order of fragility, with the most transient evidence (such as biological fluids, trace evidence, and weather-sensitive items) collected first.',
    explanation: 'Transient evidence can be lost to environmental conditions, traffic, or other factors. Establishing collection priority preserves the most vulnerable evidence.',
    legalImplication: 'Failure to prioritize transient evidence collection may result in permanent loss of critical evidence.',
    category: 'evidence_collection',
    keywords: ['collection order', 'transient evidence', 'fragility', 'priority', 'biological'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Biological Evidence',
    rule: 'Biological evidence such as blood, saliva, and other body fluids must be collected using sterile instruments, properly packaged in breathable containers, and refrigerated or dried to prevent degradation.',
    explanation: 'Biological evidence degrades rapidly if improperly handled. Wet biological evidence must never be sealed in plastic bags, which promotes bacterial growth.',
    legalImplication: 'Improperly collected or stored biological evidence may be degraded beyond usefulness or excluded from court.',
    category: 'evidence_collection',
    keywords: ['biological evidence', 'blood', 'DNA', 'sterile', 'packaging', 'degradation'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Trace Evidence',
    rule: 'Trace evidence including fibers, hair, glass fragments, and soil must be collected using appropriate techniques such as tweezers, tape lifts, or vacuum collection, with each item packaged separately.',
    explanation: 'Trace evidence is easily lost or contaminated. Cross-contamination between items must be prevented through separate packaging and clean instruments.',
    legalImplication: 'Trace evidence that is cross-contaminated loses its evidentiary value and may be excluded.',
    category: 'evidence_collection',
    keywords: ['trace evidence', 'fibers', 'hair', 'glass', 'soil', 'tape lift'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Fingerprint Evidence',
    rule: 'Latent fingerprints must be processed using appropriate techniques based on the surface type, documented photographically before lifting, and properly preserved for comparison.',
    explanation: 'Different surfaces require different processing techniques (powder, cyanoacrylate fuming, ninhydrin, etc.). Prints must be photographed before any lifting attempt.',
    legalImplication: 'Improperly processed fingerprints may be unusable for comparison or challenged as contaminated.',
    category: 'evidence_collection',
    keywords: ['fingerprints', 'latent prints', 'processing', 'lifting', 'comparison'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Firearm Evidence',
    rule: 'Firearms found at a crime scene must be documented in place, rendered safe before collection, and packaged to preserve fingerprints, DNA, and gunshot residue.',
    explanation: 'Officers must not insert objects into the barrel or otherwise disturb potential evidence. The weapon should be unloaded for safety while preserving its condition.',
    legalImplication: 'Improper handling of firearm evidence may destroy fingerprints, DNA, or ballistic evidence.',
    category: 'evidence_collection',
    keywords: ['firearms', 'weapon', 'render safe', 'gunshot residue', 'ballistic'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Digital Evidence at Scene',
    rule: 'Digital devices found at a crime scene must be documented, collected without altering data, and isolated from network connections to prevent remote wiping.',
    explanation: 'Placing phones in airplane mode or Faraday bags prevents data alteration. Computers should not be turned on or off without forensic guidance.',
    legalImplication: 'Failure to properly preserve digital evidence may result in data loss or challenges to evidence integrity.',
    category: 'evidence_collection',
    keywords: ['digital evidence', 'devices', 'Faraday bag', 'network isolation', 'forensic'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Tool Mark Evidence',
    rule: 'Tool marks at a crime scene must be documented in place with photographs and casts, and the original surface should be collected when possible for laboratory comparison.',
    explanation: 'Tool marks can link a specific tool to a crime scene. Both the tool and the marked surface are needed for a definitive comparison.',
    legalImplication: 'Failure to properly document and collect tool mark evidence may prevent laboratory identification.',
    category: 'evidence_collection',
    keywords: ['tool marks', 'comparison', 'casts', 'impression evidence'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Collection',
    topic: 'Shoe and Tire Impressions',
    rule: 'Shoe prints and tire impressions must be documented with photographs using oblique lighting and scale indicators, and preserved using dental stone casts.',
    explanation: 'Impression evidence can identify specific shoes or tires. Proper lighting technique is critical for capturing detail in photographs.',
    legalImplication: 'Poorly documented impression evidence may not be suitable for comparison or court presentation.',
    category: 'evidence_collection',
    keywords: ['shoe prints', 'tire impressions', 'dental stone', 'oblique lighting', 'casting'],
  },

  // =========================================================================
  // CHAPTER: Specialized Crime Scenes
  // =========================================================================
  {
    source: 'POST LD-30',
    chapter: 'Specialized Crime Scenes',
    topic: 'Homicide Scene Investigation',
    rule: 'Homicide crime scenes require the highest level of documentation and evidence collection, including complete scene reconstruction, victimology assessment, and wound pattern analysis.',
    explanation: 'Homicide investigations are the most complex crime scene operations. Every detail must be documented because the scene can only be processed once.',
    legalImplication: 'Inadequate homicide scene processing may permanently compromise the investigation and prevent prosecution.',
    category: 'crime_scene',
    keywords: ['homicide', 'scene investigation', 'victimology', 'wound pattern', 'reconstruction'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Specialized Crime Scenes',
    topic: 'Sexual Assault Scene',
    rule: 'Sexual assault crime scenes require careful collection of biological evidence including bedding, clothing, and any items that may contain DNA, with attention to victim privacy and dignity.',
    explanation: 'Sexual assault evidence collection must balance thorough investigation with sensitivity to the victim. A victim advocate should be present when possible.',
    legalImplication: 'Failure to properly collect sexual assault evidence may prevent identification of the perpetrator.',
    category: 'crime_scene',
    keywords: ['sexual assault', 'biological evidence', 'DNA', 'victim privacy', 'bedding'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Specialized Crime Scenes',
    topic: 'Arson Scene Investigation',
    rule: 'Arson scene investigation requires identification of the fire\'s origin and cause, collection of accelerant samples, and documentation of burn patterns before the scene is disturbed.',
    explanation: 'Arson scenes are destructive environments that rapidly degrade evidence. Accelerant samples must be collected in airtight containers to prevent evaporation.',
    legalImplication: 'Failure to properly investigate fire origin and preserve accelerant evidence may prevent arson prosecution.',
    category: 'crime_scene',
    keywords: ['arson', 'fire origin', 'accelerant', 'burn patterns', 'airtight container'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Specialized Crime Scenes',
    topic: 'Vehicle Crime Scene',
    rule: 'Vehicles involved in crimes must be processed as contained crime scenes, with systematic documentation of the interior, exterior, trunk, and undercarriage.',
    explanation: 'Vehicles can contain a wealth of evidence including fingerprints, DNA, fibers, and digital data from onboard systems. The vehicle should be transported to a secure facility for processing.',
    legalImplication: 'Failure to process a vehicle crime scene may result in loss of critical evidence.',
    category: 'crime_scene',
    keywords: ['vehicle', 'crime scene', 'interior', 'exterior', 'contained scene'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Specialized Crime Scenes',
    topic: 'Clandestine Laboratory',
    rule: 'Clandestine drug laboratory scenes require specialized hazardous materials (HazMat) training and equipment before entry, with evidence collection following specific safety protocols.',
    explanation: 'Drug labs contain toxic chemicals that pose immediate danger to officers. HazMat-certified personnel must clear the scene before evidence collection begins.',
    legalImplication: 'Entry into a clandestine lab without proper precautions may compromise both officer safety and evidence integrity.',
    category: 'crime_scene',
    keywords: ['clandestine laboratory', 'drug lab', 'HazMat', 'toxic chemicals', 'safety'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Specialized Crime Scenes',
    topic: 'Officer-Involved Shooting Scene',
    rule: 'Officer-involved shooting scenes must be processed by investigators not involved in the incident, with the involved officer\'s weapon collected as evidence and the scene treated as a critical incident.',
    explanation: 'Independent investigation ensures objectivity. The involved officer should be separated from the scene and provided with peer support.',
    legalImplication: 'Failure to independently investigate an officer-involved shooting may create liability and undermine public trust.',
    category: 'crime_scene',
    keywords: ['officer-involved shooting', 'independent investigation', 'critical incident', 'weapon'],
  },

  // =========================================================================
  // CHAPTER: Forensic Science Principles
  // =========================================================================
  {
    source: 'POST LD-30',
    chapter: 'Forensic Science',
    topic: 'Locard\'s Exchange Principle',
    rule: 'Locard\'s Exchange Principle states that every contact leaves a trace. Investigators must be aware that the perpetrator will both leave evidence at and take evidence from the crime scene.',
    explanation: 'This principle guides evidence collection strategy. Investigators look for what the suspect may have left behind and what they may have taken with them.',
    legalImplication: 'Understanding Locard\'s principle helps investigators identify and collect the full range of evidence at a scene.',
    category: 'crime_scene',
    keywords: ['Locard', 'exchange principle', 'trace evidence', 'contact', 'transfer'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Forensic Science',
    topic: 'Crime Scene Reconstruction',
    rule: 'Crime scene reconstruction uses physical evidence, witness statements, and scientific analysis to determine the sequence of events that occurred at the scene.',
    explanation: 'Reconstruction involves analyzing bloodstain patterns, bullet trajectories, glass fracture patterns, and other physical evidence to establish what happened.',
    legalImplication: 'A well-supported crime scene reconstruction can be powerful evidence at trial but must be based on sound scientific principles.',
    category: 'crime_scene',
    keywords: ['reconstruction', 'sequence of events', 'bloodstain pattern', 'bullet trajectory'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Forensic Science',
    topic: 'Bloodstain Pattern Analysis',
    rule: 'Bloodstain pattern analysis (BPA) examines the size, shape, distribution, and location of bloodstains to determine the actions that produced them.',
    explanation: 'BPA can reveal the position of the victim, the type of weapon used, the number of blows or shots, and the movement of individuals at the scene.',
    legalImplication: 'BPA testimony must meet Daubert/Kelly-Frye standards for scientific reliability to be admissible.',
    category: 'crime_scene',
    keywords: ['bloodstain pattern', 'BPA', 'distribution', 'forensic analysis'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Forensic Science',
    topic: 'DNA Evidence Standards',
    rule: 'DNA evidence must be collected, preserved, and analyzed following strict protocols to prevent contamination and ensure the reliability of results.',
    explanation: 'DNA analysis is among the most powerful forensic tools but is also highly sensitive to contamination. Proper collection and chain of custody are essential.',
    legalImplication: 'DNA evidence that is contaminated or improperly handled may be excluded or its weight significantly diminished.',
    category: 'crime_scene',
    keywords: ['DNA', 'contamination', 'protocols', 'reliability', 'forensic'],
  },

  // =========================================================================
  // CHAPTER: Evidence Packaging and Transport
  // =========================================================================
  {
    source: 'POST LD-30',
    chapter: 'Evidence Packaging',
    topic: 'Packaging Standards',
    rule: 'Each item of evidence must be individually packaged to prevent cross-contamination, properly labeled with case number, item number, description, and collector information.',
    explanation: 'Proper packaging maintains evidence integrity from scene to laboratory to courtroom. Labels must be accurate and complete.',
    legalImplication: 'Evidence that is improperly packaged or labeled may be challenged as unreliable or contaminated.',
    category: 'evidence_collection',
    keywords: ['packaging', 'labeling', 'cross-contamination', 'individual packaging'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Packaging',
    topic: 'Wet Evidence',
    rule: 'Wet biological evidence must be air-dried before packaging in paper containers. Wet evidence must never be stored in sealed plastic bags.',
    explanation: 'Sealing wet biological evidence in plastic promotes bacterial growth that destroys DNA. Paper bags and envelopes allow air circulation.',
    legalImplication: 'Biological evidence stored in sealed plastic may be degraded beyond usefulness, potentially destroying critical DNA evidence.',
    category: 'evidence_collection',
    keywords: ['wet evidence', 'air-dried', 'paper containers', 'biological', 'DNA preservation'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Packaging',
    topic: 'Sharps and Weapons',
    rule: 'Sharp objects, weapons, and syringes must be packaged in rigid containers with appropriate biohazard labels to protect handlers from injury and exposure.',
    explanation: 'Safety is paramount when packaging dangerous items. Sharps containers or rigid boxes with padding prevent accidental puncture or cutting.',
    legalImplication: 'Failure to properly package dangerous evidence may expose personnel to injury and create liability.',
    category: 'evidence_collection',
    keywords: ['sharps', 'weapons', 'syringes', 'rigid containers', 'biohazard'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Evidence Packaging',
    topic: 'Evidence Transport',
    rule: 'Evidence must be transported to the evidence facility in a secure manner that prevents loss, contamination, or damage during transit.',
    explanation: 'Evidence should be placed in a secure vehicle compartment, protected from extreme temperatures, and delivered to the evidence facility as soon as practical.',
    legalImplication: 'Evidence damaged or lost during transport may be excluded and may constitute a chain of custody break.',
    category: 'evidence_collection',
    keywords: ['transport', 'secure', 'damage prevention', 'evidence facility'],
  },

  // =========================================================================
  // CHAPTER: Death Scene Investigation
  // =========================================================================
  {
    source: 'POST LD-30',
    chapter: 'Death Investigation',
    topic: 'Body Documentation',
    rule: 'The position, condition, and surroundings of a deceased person must be thoroughly documented before the body is moved, including detailed photography and notation of lividity, rigor, and decomposition.',
    explanation: 'Post-mortem changes provide critical information about time of death and whether the body was moved. These observations must be made before any disturbance.',
    legalImplication: 'Moving a body before thorough documentation may destroy evidence relevant to manner and time of death.',
    category: 'crime_scene',
    keywords: ['body documentation', 'lividity', 'rigor mortis', 'decomposition', 'position'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Death Investigation',
    topic: 'Coroner Notification',
    rule: 'The coroner or medical examiner must be notified immediately upon discovery of a death that is sudden, violent, unusual, or suspicious, and the body must not be moved without coroner authorization.',
    explanation: 'California Government Code Section 27491 gives the coroner jurisdiction over deaths that are not clearly natural. The coroner determines cause and manner of death.',
    legalImplication: 'Moving a body without coroner authorization may constitute a criminal offense and may compromise the death investigation.',
    category: 'crime_scene',
    keywords: ['coroner', 'medical examiner', 'notification', 'jurisdiction', 'cause of death'],
  },
  {
    source: 'POST LD-30',
    chapter: 'Death Investigation',
    topic: 'Scene Environmental Data',
    rule: 'Environmental data at a death scene, including temperature, humidity, heating/cooling status, and insect activity, must be documented to assist in determining time of death.',
    explanation: 'Environmental factors significantly affect the rate of post-mortem changes. This data is essential for forensic pathologists to estimate time of death.',
    legalImplication: 'Failure to document environmental conditions may prevent accurate time-of-death estimation.',
    category: 'crime_scene',
    keywords: ['environmental data', 'temperature', 'time of death', 'insect activity', 'humidity'],
  },
];
