// ============================================
// POST LD-15: Laws of Arrest — Expansion Seed Data
// Additional doctrine rules to reach ~120 total
// ============================================

import type { ParsedDoctrineChunk } from './types.ts';

export const LD15_EXPANSION_RULES: ParsedDoctrineChunk[] = [
  // =========================================================================
  // CHAPTER: Constitutional Protections (expanded)
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'California Constitution',
    rule: 'Article I, Section 13 of the California Constitution provides protections against unreasonable searches and seizures similar to the Fourth Amendment.',
    explanation: 'California courts may interpret state constitutional protections more broadly than federal protections, providing additional rights to individuals.',
    legalImplication: 'Evidence may be suppressed under state constitutional grounds even if it would be admissible under federal law.',
    category: 'constitutional',
    keywords: ['california constitution', 'article I', 'search', 'seizure', 'state rights'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Due Process',
    rule: 'The Due Process Clause of the Fourteenth Amendment prohibits conduct that shocks the conscience and requires fundamental fairness in law enforcement procedures.',
    explanation: 'Conduct that is outrageous or fundamentally unfair may violate due process even if it does not violate a specific constitutional provision.',
    legalImplication: 'Evidence obtained through conduct that shocks the conscience may be excluded regardless of other constitutional analyses.',
    category: 'constitutional',
    keywords: ['due process', 'shocks the conscience', 'fundamental fairness', 'fourteenth amendment'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Standing',
    rule: 'Only a person whose own Fourth Amendment rights were violated has standing to challenge the legality of a search or seizure.',
    explanation: 'A defendant cannot challenge a search of another person\'s property unless the defendant had a reasonable expectation of privacy in the area searched.',
    legalImplication: 'Without standing, a motion to suppress will be denied even if the search was unlawful.',
    category: 'constitutional',
    keywords: ['standing', 'fourth amendment', 'expectation of privacy', 'suppress'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Good Faith Exception',
    rule: 'Under the good faith exception, evidence obtained by officers acting in reasonable reliance on a facially valid warrant may not be suppressed even if the warrant is later found defective.',
    explanation: 'The good faith exception applies when officers reasonably rely on judicial authorization. It does not apply when the affidavit was so lacking that no reasonable officer would rely on it.',
    legalImplication: 'The good faith exception may save evidence from suppression when the warrant defect was not apparent to a reasonable officer.',
    category: 'constitutional',
    keywords: ['good faith', 'exception', 'warrant', 'reasonable reliance', 'suppression'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Constitutional Protections',
    topic: 'Inevitable Discovery',
    rule: 'Evidence obtained through an unlawful search may still be admissible if the prosecution can prove by a preponderance of the evidence that it would have been inevitably discovered through lawful means.',
    explanation: 'This doctrine is an exception to the exclusionary rule. The prosecution must show that lawful procedures already in motion would have led to discovery of the evidence.',
    legalImplication: 'Inevitable discovery can save evidence from exclusion but requires the prosecution to demonstrate a concrete, lawful alternative path.',
    category: 'constitutional',
    keywords: ['inevitable discovery', 'exclusionary rule', 'exception', 'lawful means'],
  },

  // =========================================================================
  // CHAPTER: Detentions (expanded)
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'An officer may consider the totality of the circumstances in determining whether reasonable suspicion exists, including the time of day, location, and behavior of the individual.',
    explanation: 'No single factor may be sufficient alone, but factors considered together may create reasonable suspicion. The officer must be able to articulate each factor.',
    legalImplication: 'A detention based solely on a single innocuous factor without additional supporting circumstances may be found unlawful.',
    category: 'detention',
    keywords: ['totality of circumstances', 'reasonable suspicion', 'factors', 'detention'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'Flight from police, when combined with other factors, may contribute to reasonable suspicion but cannot alone establish it.',
    explanation: 'While flight from officers is a relevant factor, the Supreme Court held in Illinois v. Wardlow that flight alone in a high-crime area may support reasonable suspicion.',
    legalImplication: 'A detention based solely on flight, without additional articulable factors, may be found unlawful.',
    category: 'detention',
    keywords: ['flight', 'reasonable suspicion', 'Illinois v Wardlow', 'high-crime area'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'Reasonable suspicion must be based on objective facts, not on a person\'s race, ethnicity, national origin, gender, or other protected characteristic.',
    explanation: 'Racial profiling is unconstitutional and violates both the Fourth and Fourteenth Amendments. Officers must articulate non-discriminatory factors.',
    legalImplication: 'A detention based on racial profiling violates both the Fourth and Fourteenth Amendments and may result in suppression and civil liability.',
    category: 'detention',
    keywords: ['racial profiling', 'reasonable suspicion', 'equal protection', 'discrimination'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Reasonable Suspicion',
    rule: 'An anonymous tip alone generally does not provide reasonable suspicion unless corroborated by independent police observation.',
    explanation: 'Per Alabama v. White and Navarette v. California, anonymous tips must contain sufficient detail and be corroborated before they can justify a detention.',
    legalImplication: 'A detention based solely on an uncorroborated anonymous tip may be found unlawful.',
    category: 'detention',
    keywords: ['anonymous tip', 'reasonable suspicion', 'corroboration', 'Alabama v White'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Detention Scope',
    rule: 'Officers may not extend a detention beyond its original purpose without developing additional reasonable suspicion of other criminal activity.',
    explanation: 'Per Rodriguez v. United States, a traffic stop becomes unlawful if prolonged beyond the time needed to handle the matter for which the stop was made, absent reasonable suspicion.',
    legalImplication: 'Evidence discovered during an unlawfully extended detention is subject to suppression.',
    category: 'detention',
    keywords: ['detention scope', 'Rodriguez v United States', 'traffic stop', 'prolonged'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Handcuffing During Detention',
    rule: 'Handcuffing a detainee during a Terry stop does not automatically convert the detention into an arrest, but the use of restraints must be justified by specific safety concerns.',
    explanation: 'Courts evaluate whether the use of handcuffs was reasonable under the totality of circumstances, including the nature of the suspected crime and the detainee\'s behavior.',
    legalImplication: 'Unjustified use of handcuffs during a detention may convert it into a de facto arrest requiring probable cause.',
    category: 'detention',
    keywords: ['handcuffing', 'detention', 'terry stop', 'de facto arrest', 'restraints'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Detention Duration',
    rule: 'There is no bright-line time limit for a lawful detention; reasonableness depends on the circumstances and the diligence of the investigation.',
    explanation: 'While detentions must be brief, courts evaluate whether the officer diligently pursued the investigation rather than applying a strict time limit.',
    legalImplication: 'A detention that continues after the officer ceases active investigation becomes unreasonably prolonged.',
    category: 'detention',
    keywords: ['detention duration', 'time limit', 'diligent investigation', 'reasonableness'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Show-Up Identification',
    rule: 'An officer may transport a detainee a short distance for a show-up identification if circumstances justify the procedure and the transportation is brief.',
    explanation: 'Show-up identifications during detentions are permissible when conducted promptly and the transportation is reasonably necessary.',
    legalImplication: 'Transporting a detainee an unreasonable distance for identification may convert the detention into an arrest.',
    category: 'detention',
    keywords: ['show-up', 'identification', 'detention', 'transportation'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Detentions',
    topic: 'Vehicle Detention',
    rule: 'During a vehicle stop, officers may order both the driver and passengers to exit the vehicle for officer safety purposes.',
    explanation: 'Per Maryland v. Wilson, the authority to order passengers out during a traffic stop extends the Supreme Court\'s holding in Pennsylvania v. Mimms regarding drivers.',
    legalImplication: 'An order to exit a vehicle during a lawful traffic stop is a minimal intrusion justified by officer safety.',
    category: 'detention',
    keywords: ['vehicle stop', 'exit order', 'passengers', 'Maryland v Wilson', 'officer safety'],
  },

  // =========================================================================
  // CHAPTER: Searches (expanded)
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Pat Searches',
    rule: 'An officer cannot conduct a pat search based solely on the fact that the person is in a high-crime area.',
    explanation: 'While the nature of the area is a factor, it alone does not provide reasonable belief that the person is armed. Additional specific articulable facts are required.',
    legalImplication: 'A pat search based solely on location is unlawful and evidence discovered may be suppressed.',
    category: 'search',
    keywords: ['pat search', 'high-crime area', 'reasonable belief', 'armed'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Protective Sweeps',
    rule: 'A protective sweep of a residence incident to arrest is limited to a cursory inspection of areas where a person may be hiding and must be based on articulable facts.',
    explanation: 'Per Maryland v. Buie, officers making an in-home arrest may conduct a limited sweep of adjoining areas from which an attack could be launched.',
    legalImplication: 'A protective sweep that exceeds its limited scope or lacks articulable justification may result in suppression of evidence.',
    category: 'search',
    keywords: ['protective sweep', 'Maryland v Buie', 'in-home arrest', 'cursory inspection'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Search Incident to Arrest',
    rule: 'A search incident to arrest of a vehicle occupant is limited to the passenger compartment and only when the arrestee could access the vehicle or evidence of the crime of arrest may be found.',
    explanation: 'Under Arizona v. Gant, the search incident to arrest exception for vehicles is more limited than for searches of the arrestee\'s person.',
    legalImplication: 'Searching a vehicle beyond the scope permitted by Gant without probable cause may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['search incident to arrest', 'vehicle', 'Arizona v Gant', 'passenger compartment'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Consent Searches',
    rule: 'Officers are not required to inform a person of the right to refuse consent, but failure to do so is a factor in determining voluntariness.',
    explanation: 'While there is no legal requirement to advise of the right to refuse, doing so strengthens the prosecution\'s case that consent was voluntary.',
    legalImplication: 'Failure to advise of the right to refuse, combined with other coercive factors, may render consent involuntary.',
    category: 'search',
    keywords: ['consent', 'right to refuse', 'voluntary', 'advise'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Probation and Parole Searches',
    rule: 'A person on searchable probation or parole may be searched without a warrant and without reasonable suspicion, provided the search is not conducted for harassment purposes.',
    explanation: 'California allows warrantless searches of probationers and parolees who have accepted search conditions. The search must not be arbitrary or harassing.',
    legalImplication: 'A probation search conducted solely for harassment or without knowledge of the search condition may be unlawful.',
    category: 'search',
    keywords: ['probation search', 'parole', 'warrantless', 'search condition'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'School Searches',
    rule: 'School officials may search a student if there are reasonable grounds for suspecting the search will reveal evidence of a violation of law or school rules.',
    explanation: 'Per New Jersey v. T.L.O., the standard for school searches is reasonable suspicion, not probable cause. The search must be reasonably related in scope to the circumstances.',
    legalImplication: 'A school search without reasonable grounds or that is excessive in scope may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['school search', 'student', 'reasonable grounds', 'New Jersey v TLO'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Body Cavity Searches',
    rule: 'Visual body cavity searches of arrestees must be conducted by medical personnel in a private setting and require reasonable suspicion that the person is concealing contraband.',
    explanation: 'California Penal Code Section 4030 restricts body cavity searches and requires specific procedures to protect the dignity of the individual.',
    legalImplication: 'Body cavity searches conducted without proper authority or procedures violate constitutional rights and may result in civil liability.',
    category: 'search',
    keywords: ['body cavity search', 'medical personnel', 'privacy', 'contraband'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Strip Searches',
    rule: 'Strip searches of misdemeanor arrestees in jail are prohibited unless there is reasonable suspicion the person is concealing weapons or contraband.',
    explanation: 'California Penal Code Section 4030 imposes restrictions on strip searches. For felony arrestees, policies must still comply with constitutional standards.',
    legalImplication: 'Blanket strip search policies for misdemeanor arrestees without individualized suspicion violate the Fourth Amendment.',
    category: 'search',
    keywords: ['strip search', 'misdemeanor', 'reasonable suspicion', 'jail'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Warrant Exceptions',
    rule: 'The community caretaking exception allows officers to enter a residence without a warrant when there is an objectively reasonable basis for believing someone inside needs immediate assistance.',
    explanation: 'This exception applies in emergency situations such as hearing cries for help, reports of a medical emergency, or other circumstances suggesting immediate aid is needed.',
    legalImplication: 'Entry under the community caretaking exception that is pretextual or not supported by objective facts is unlawful.',
    category: 'search',
    keywords: ['community caretaking', 'emergency', 'warrantless entry', 'immediate assistance'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Border Searches',
    rule: 'At international borders and their functional equivalents, routine searches of persons and belongings may be conducted without a warrant, probable cause, or reasonable suspicion.',
    explanation: 'The border search exception is based on the sovereign\'s right to control entry. Non-routine searches such as body cavity searches require reasonable suspicion.',
    legalImplication: 'Non-routine border searches without reasonable suspicion may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['border search', 'international border', 'routine', 'sovereign right'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Abandoned Property',
    rule: 'There is no Fourth Amendment protection for abandoned property. An officer may search and seize abandoned items without a warrant.',
    explanation: 'Abandonment is determined by whether the person voluntarily relinquished their expectation of privacy in the property. Discarding items during flight may constitute abandonment.',
    legalImplication: 'If the court finds the property was not truly abandoned, the warrantless search may be unlawful.',
    category: 'search',
    keywords: ['abandoned property', 'expectation of privacy', 'warrantless', 'abandonment'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Searches',
    topic: 'Open Fields Doctrine',
    rule: 'The Fourth Amendment does not protect open fields, even if they are private property. Officers may enter and observe open fields without a warrant.',
    explanation: 'The open fields doctrine distinguishes between the curtilage of a home (protected) and open fields beyond the curtilage (not protected).',
    legalImplication: 'Evidence observed in open fields is admissible even without a warrant, but evidence from the curtilage requires Fourth Amendment justification.',
    category: 'search',
    keywords: ['open fields', 'curtilage', 'private property', 'fourth amendment'],
  },

  // =========================================================================
  // CHAPTER: Arrests (expanded)
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Arrest Procedures',
    rule: 'An officer making an arrest must inform the person of the authority and cause for the arrest, except when the person is engaged in the commission of the offense.',
    explanation: 'California Penal Code Section 841 requires officers to state the authority and reason for the arrest unless the circumstances make it impractical.',
    legalImplication: 'Failure to inform the arrestee of the reason for arrest may affect the lawfulness of the arrest under state law.',
    category: 'arrest',
    keywords: ['arrest procedures', 'inform', 'authority', 'cause', 'penal code 841'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Citizen\'s Arrest',
    rule: 'A private person may arrest another for a public offense committed in their presence or when they have reasonable cause to believe the person committed a felony.',
    explanation: 'Under California Penal Code Section 837, private persons have limited arrest authority. Officers may accept custody of a person arrested by a citizen.',
    legalImplication: 'An invalid citizen\'s arrest may expose the arresting person to civil liability for false imprisonment.',
    category: 'arrest',
    keywords: ['citizen arrest', 'private person', 'public offense', 'penal code 837'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Probable Cause',
    rule: 'An officer must not arrest a person solely for exercising their constitutional rights, including the right to refuse consent to search or the right to remain silent.',
    explanation: 'Exercising constitutional rights cannot be used as a factor in establishing probable cause. Retaliation for asserting rights violates the First and Fourth Amendments.',
    legalImplication: 'An arrest based on the exercise of constitutional rights is unlawful and may result in civil rights violations.',
    category: 'arrest',
    keywords: ['constitutional rights', 'retaliation', 'probable cause', 'refuse consent'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Use of Force in Arrest',
    rule: 'An officer may use only the amount of force that is objectively reasonable to effect an arrest, prevent escape, or overcome resistance.',
    explanation: 'The reasonableness standard from Graham v. Connor applies. Force must be evaluated from the perspective of a reasonable officer on the scene.',
    legalImplication: 'Excessive force during an arrest violates the Fourth Amendment and may result in criminal and civil liability.',
    category: 'arrest',
    keywords: ['force', 'arrest', 'objectively reasonable', 'Graham v Connor', 'excessive force'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Arrest in Home',
    rule: 'Absent exigent circumstances, an arrest warrant is required to arrest a person inside their own home.',
    explanation: 'Per Payton v. New York, the Fourth Amendment prohibits warrantless entry into a suspect\'s home to make a routine felony arrest.',
    legalImplication: 'A warrantless in-home arrest without exigent circumstances is unlawful and may result in suppression of evidence.',
    category: 'arrest',
    keywords: ['arrest warrant', 'home', 'Payton v New York', 'warrantless entry'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Arrest in Third-Party Home',
    rule: 'To arrest a suspect in a third party\'s home, officers must have both an arrest warrant for the suspect and a search warrant for the residence, absent exigent circumstances or consent.',
    explanation: 'Per Steagald v. United States, an arrest warrant alone does not authorize entry into a third party\'s home to search for the subject of the warrant.',
    legalImplication: 'Entry into a third party\'s home with only an arrest warrant may violate the third party\'s Fourth Amendment rights.',
    category: 'arrest',
    keywords: ['third party home', 'arrest warrant', 'search warrant', 'Steagald v United States'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Post-Arrest Procedures',
    rule: 'Following an arrest, officers must book the arrestee without unnecessary delay and ensure the arrestee\'s rights are respected throughout the booking process.',
    explanation: 'California Penal Code Section 825 requires the arrestee to be brought before a magistrate without unnecessary delay, generally within 48 hours.',
    legalImplication: 'Unnecessary delay in booking or presentment may violate due process and may affect the admissibility of statements.',
    category: 'arrest',
    keywords: ['booking', 'unnecessary delay', 'post-arrest', 'magistrate', 'penal code 825'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Arrests',
    topic: 'Cite and Release',
    rule: 'For certain misdemeanor offenses, officers may issue a citation in lieu of custodial arrest, allowing the person to be released with a promise to appear in court.',
    explanation: 'California law encourages citation and release for qualifying misdemeanors to reduce jail overcrowding and minimize the impact on individuals.',
    legalImplication: 'Failure to consider cite and release when appropriate may be a policy violation, though it generally does not affect the legality of the arrest.',
    category: 'arrest',
    keywords: ['citation', 'cite and release', 'misdemeanor', 'promise to appear'],
  },

  // =========================================================================
  // CHAPTER: Miranda (expanded)
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Custody Determination',
    rule: 'A person is in custody for Miranda purposes when a reasonable person in the same circumstances would not feel free to leave or terminate the encounter.',
    explanation: 'Custody is determined by objective circumstances, not the subjective intent of the officer. Factors include physical restraint, location, duration, and tone of questioning.',
    legalImplication: 'Failure to recognize a custodial situation and provide Miranda warnings may render statements inadmissible.',
    category: 'miranda',
    keywords: ['custody', 'miranda', 'free to leave', 'reasonable person', 'objective circumstances'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Interrogation',
    rule: 'Interrogation includes not only express questioning but also any words or actions by police that are reasonably likely to elicit an incriminating response.',
    explanation: 'Per Rhode Island v. Innis, the definition of interrogation extends beyond direct questions to include any practice the police should know is reasonably likely to invoke a response.',
    legalImplication: 'Statements obtained through functional interrogation without Miranda warnings may be inadmissible.',
    category: 'miranda',
    keywords: ['interrogation', 'miranda', 'elicit response', 'Rhode Island v Innis'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Public Safety Exception',
    rule: 'Under the public safety exception, officers may question a suspect in custody without Miranda warnings when there is an immediate threat to public safety.',
    explanation: 'Per New York v. Quarles, when public safety is at stake, the need for answers outweighs the need for Miranda protections. Questions must be limited to the immediate safety concern.',
    legalImplication: 'The public safety exception is narrowly applied; questions beyond the immediate safety concern require Miranda warnings.',
    category: 'miranda',
    keywords: ['public safety', 'miranda exception', 'New York v Quarles', 'immediate threat'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Miranda Reinitiation',
    rule: 'After a suspect invokes the right to counsel, police may not reinitiate questioning until counsel has been provided or the suspect voluntarily reinitiates communication.',
    explanation: 'Per Edwards v. Arizona, once the right to counsel is invoked, the suspect must not be subjected to further interrogation until an attorney is present or the suspect initiates further communication.',
    legalImplication: 'Statements obtained after police-initiated questioning following invocation of counsel are inadmissible.',
    category: 'miranda',
    keywords: ['reinitiation', 'right to counsel', 'Edwards v Arizona', 'invoke'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Spontaneous Statements',
    rule: 'Spontaneous statements made by a suspect without police prompting are admissible even without Miranda warnings.',
    explanation: 'Miranda only applies to custodial interrogation. Voluntary, unprompted statements are not the product of interrogation and are therefore admissible.',
    legalImplication: 'If the prosecution can establish that a statement was truly spontaneous and not the product of interrogation, it is admissible regardless of Miranda.',
    category: 'miranda',
    keywords: ['spontaneous statement', 'voluntary', 'unprompted', 'miranda'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Miranda',
    topic: 'Booking Questions',
    rule: 'Routine booking questions regarding biographical data are not considered interrogation and do not require Miranda warnings.',
    explanation: 'Questions about name, address, date of birth, and similar biographical information asked during booking are administrative and fall outside Miranda requirements.',
    legalImplication: 'Responses to routine booking questions are generally admissible even without Miranda warnings.',
    category: 'miranda',
    keywords: ['booking questions', 'biographical data', 'miranda', 'administrative'],
  },

  // =========================================================================
  // CHAPTER: Interrogation (expanded)
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Interrogation',
    topic: 'Interrogation Techniques',
    rule: 'Officers must not use physical force, threats of harm, or prolonged deprivation to coerce a confession from a suspect.',
    explanation: 'Coerced confessions violate the Due Process Clause. The voluntariness of a confession is judged by the totality of circumstances surrounding the interrogation.',
    legalImplication: 'A coerced confession is inadmissible and may result in criminal charges against the officers involved.',
    category: 'interrogation',
    keywords: ['coercion', 'confession', 'physical force', 'threats', 'due process'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogation',
    topic: 'Interrogation Techniques',
    rule: 'Deception during interrogation is generally permissible but must not be so coercive as to overbear the will of the suspect.',
    explanation: 'Courts allow some deception (e.g., claiming evidence exists) but prohibit tactics that are so coercive they create a risk of false confessions.',
    legalImplication: 'Deception that is so extreme it renders a confession involuntary may result in suppression.',
    category: 'interrogation',
    keywords: ['deception', 'interrogation', 'false evidence', 'voluntary confession'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogation',
    topic: 'Interrogation Recording',
    rule: 'California law requires the electronic recording of custodial interrogations for certain serious offenses, including homicides.',
    explanation: 'California Penal Code Section 859.5 requires recording of interrogations for specified felonies. The recording must include the entire interrogation.',
    legalImplication: 'Failure to record a required interrogation may result in a jury instruction regarding the missing recording.',
    category: 'interrogation',
    keywords: ['recording', 'custodial interrogation', 'electronic recording', 'penal code 859.5'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogation',
    topic: 'Juvenile Interrogation',
    rule: 'Juveniles under age 16 must consult with an attorney before waiving Miranda rights, and officers must consider the juvenile\'s age, maturity, and understanding.',
    explanation: 'California Senate Bill 395 requires mandatory consultation with an attorney for juveniles under 16. The juvenile\'s age is a relevant factor in custody determinations.',
    legalImplication: 'Statements obtained from juveniles without mandatory attorney consultation may be inadmissible.',
    category: 'interrogation',
    keywords: ['juvenile', 'interrogation', 'miranda', 'attorney consultation', 'age'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Interrogation',
    topic: 'Interrogation — Multiple Sessions',
    rule: 'When conducting multiple interrogation sessions, officers must re-advise Miranda warnings at each session to ensure the suspect is aware of their continuing rights.',
    explanation: 'While not always legally required, best practice is to re-Mirandize at each session. A significant break between sessions may require fresh warnings.',
    legalImplication: 'Failure to re-advise Miranda before subsequent sessions may raise questions about whether the waiver remained valid.',
    category: 'interrogation',
    keywords: ['multiple sessions', 'miranda', 're-advise', 'interrogation'],
  },

  // =========================================================================
  // CHAPTER: Identification Procedures
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Identification Procedures',
    topic: 'Lineup Procedures',
    rule: 'Eyewitness identification procedures must be conducted in a manner that minimizes the risk of misidentification, including the use of sequential presentation and blind administration when practical.',
    explanation: 'Research shows that simultaneous lineups and administrator knowledge of the suspect can increase misidentification risk. Sequential, blind procedures are recommended.',
    legalImplication: 'Suggestive identification procedures may result in suppression of the identification evidence.',
    category: 'detention',
    keywords: ['lineup', 'eyewitness', 'identification', 'sequential', 'blind administration'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Identification Procedures',
    topic: 'Photo Identification',
    rule: 'Photo arrays must include a reasonable number of fillers who match the witness\'s description of the suspect, and the suspect should not stand out from the fillers.',
    explanation: 'The composition of the photo array must be fair. Using fillers who are significantly different from the suspect makes the identification procedure suggestive.',
    legalImplication: 'A suggestive photo array may result in suppression of the identification and may undermine the prosecution\'s case.',
    category: 'detention',
    keywords: ['photo array', 'identification', 'fillers', 'suggestive', 'fairness'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Identification Procedures',
    topic: 'Show-Up Identification',
    rule: 'Show-up identifications should be conducted promptly after the crime and the witness should be admonished that the person may or may not be the perpetrator.',
    explanation: 'Show-ups are inherently suggestive because the witness sees only one person. Promptness and proper admonitions help mitigate the suggestiveness.',
    legalImplication: 'A show-up conducted under suggestive circumstances may be excluded, and any subsequent in-court identification may also be challenged.',
    category: 'detention',
    keywords: ['show-up', 'identification', 'suggestive', 'admonition', 'promptness'],
  },

  // =========================================================================
  // CHAPTER: Use of Force During Arrest
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Use of Force During Arrest',
    topic: 'Deadly Force',
    rule: 'Deadly force may only be used when an officer reasonably believes it is necessary to defend against an imminent threat of death or serious bodily injury to the officer or another person.',
    explanation: 'California Penal Code Section 835a codifies the standard for use of deadly force. The threat must be imminent, meaning the suspect has the present ability and apparent intent to cause death or serious injury.',
    legalImplication: 'Use of deadly force without an imminent threat of death or serious bodily injury is unlawful and may result in criminal prosecution.',
    category: 'arrest',
    keywords: ['deadly force', 'imminent threat', 'serious bodily injury', 'penal code 835a'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Use of Force During Arrest',
    topic: 'Force Proportionality',
    rule: 'The force used to make an arrest must be proportional to the resistance encountered and the severity of the offense.',
    explanation: 'Officers must continuously reassess the level of force as circumstances change. De-escalation should be attempted when feasible.',
    legalImplication: 'Disproportionate force violates the Fourth Amendment and may result in criminal and civil liability.',
    category: 'arrest',
    keywords: ['proportionality', 'force', 'resistance', 'de-escalation', 'fourth amendment'],
  },

  // =========================================================================
  // CHAPTER: Special Arrest Situations
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Special Arrest Situations',
    topic: 'DUI Arrests',
    rule: 'Officers may request a DUI suspect to submit to a preliminary alcohol screening (PAS) test during a detention, but the PAS test is voluntary prior to arrest.',
    explanation: 'The PAS test is a field sobriety tool. Post-arrest chemical testing is mandatory under California\'s implied consent law.',
    legalImplication: 'Failure to advise the suspect of the voluntary nature of the PAS test may affect the admissibility of the test results.',
    category: 'arrest',
    keywords: ['DUI', 'preliminary alcohol screening', 'implied consent', 'chemical test'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Special Arrest Situations',
    topic: 'Domestic Violence Arrests',
    rule: 'When responding to a domestic violence incident where there is probable cause to believe a felony has occurred, officers must make an arrest even if the victim does not desire prosecution.',
    explanation: 'California Penal Code Section 13701 establishes a pro-arrest policy for domestic violence incidents. Officers must follow department policies regarding mandatory arrest.',
    legalImplication: 'Failure to arrest in a mandatory arrest situation may expose the department to liability.',
    category: 'arrest',
    keywords: ['domestic violence', 'mandatory arrest', 'pro-arrest', 'penal code 13701'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Special Arrest Situations',
    topic: 'Mental Health Detentions',
    rule: 'Under California Welfare and Institutions Code Section 5150, officers may detain a person for psychiatric evaluation if the person is a danger to self, danger to others, or gravely disabled.',
    explanation: 'A 5150 hold is a civil detention, not a criminal arrest. The person may be held for up to 72 hours for evaluation and treatment.',
    legalImplication: 'A 5150 detention without the required criteria violates the person\'s liberty interest under the Due Process Clause.',
    category: 'detention',
    keywords: ['5150', 'mental health', 'psychiatric evaluation', 'danger to self', 'gravely disabled'],
  },

  // =========================================================================
  // CHAPTER: Civil Liability
  // =========================================================================
  {
    source: 'POST LD-15',
    chapter: 'Civil Liability',
    topic: 'Section 1983 Liability',
    rule: 'Under 42 U.S.C. Section 1983, officers acting under color of law who violate a person\'s constitutional rights may be held personally liable for damages.',
    explanation: 'Section 1983 provides a civil remedy for constitutional violations by state actors. Qualified immunity may protect officers unless they violated clearly established law.',
    legalImplication: 'Officers who violate clearly established constitutional rights may face personal financial liability.',
    category: 'constitutional',
    keywords: ['section 1983', 'civil liability', 'constitutional violation', 'qualified immunity'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Civil Liability',
    topic: 'Qualified Immunity',
    rule: 'Qualified immunity shields officers from civil liability unless their conduct violated a clearly established constitutional right that a reasonable officer would have known.',
    explanation: 'The qualified immunity analysis has two prongs: whether a constitutional right was violated and whether the right was clearly established at the time of the conduct.',
    legalImplication: 'Officers who violate clearly established law are not protected by qualified immunity and may be personally liable.',
    category: 'constitutional',
    keywords: ['qualified immunity', 'clearly established', 'civil liability', 'reasonable officer'],
  },
  {
    source: 'POST LD-15',
    chapter: 'Civil Liability',
    topic: 'Municipal Liability',
    rule: 'A municipality may be held liable under Section 1983 when an official policy or custom causes a constitutional violation.',
    explanation: 'Per Monell v. Department of Social Services, municipalities can be sued when the constitutional violation results from an official policy, practice, or custom of the government entity.',
    legalImplication: 'Municipalities cannot rely on qualified immunity and may face significant financial liability for policy-driven constitutional violations.',
    category: 'constitutional',
    keywords: ['municipal liability', 'Monell', 'official policy', 'custom', 'section 1983'],
  },
];
