// ============================================
// POST LD-20: Use of Force — Expansion Seed Data
// Additional doctrine rules to reach ~80 total
// ============================================

import type { ParsedDoctrineChunk } from './types.ts';

export const LD20_EXPANSION_RULES: ParsedDoctrineChunk[] = [
  // =========================================================================
  // CHAPTER: Constitutional Standards for Force
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Constitutional Standards',
    topic: 'Fourth Amendment Force Standard',
    rule: 'All uses of force by law enforcement officers are seizures subject to Fourth Amendment reasonableness analysis under Graham v. Connor.',
    explanation: 'The Supreme Court established that claims of excessive force during arrest, investigative stop, or other seizure must be analyzed under the Fourth Amendment objective reasonableness standard.',
    legalImplication: 'Force that is objectively unreasonable under the circumstances violates the Fourth Amendment.',
    category: 'use_of_force',
    keywords: ['fourth amendment', 'Graham v Connor', 'objective reasonableness', 'seizure', 'force'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Constitutional Standards',
    topic: 'Graham Factors',
    rule: 'The reasonableness of force is evaluated by considering the severity of the crime, whether the suspect poses an immediate threat to safety, and whether the suspect is actively resisting or attempting to evade arrest.',
    explanation: 'These three factors from Graham v. Connor guide the objective reasonableness analysis. No single factor is dispositive; courts consider the totality of circumstances.',
    legalImplication: 'Force found to be objectively unreasonable under the Graham factors constitutes excessive force.',
    category: 'use_of_force',
    keywords: ['Graham factors', 'severity of crime', 'immediate threat', 'resisting arrest'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Constitutional Standards',
    topic: 'Objective Reasonableness',
    rule: 'The reasonableness of force is judged from the perspective of a reasonable officer on the scene, not with the benefit of 20/20 hindsight.',
    explanation: 'Courts recognize that officers must make split-second decisions in tense, uncertain, and rapidly evolving circumstances. The analysis must account for the situation as it appeared to the officer.',
    legalImplication: 'An officer who uses force that a reasonable officer would consider appropriate under the same circumstances is protected from liability.',
    category: 'use_of_force',
    keywords: ['objective reasonableness', 'reasonable officer', 'hindsight', 'split-second'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Constitutional Standards',
    topic: 'California AB 392 Standard',
    rule: 'Under California Assembly Bill 392, officers may use deadly force only when the officer reasonably believes, based on the totality of circumstances, that such force is necessary to defend against an imminent threat of death or serious bodily injury.',
    explanation: 'AB 392 changed the standard from "reasonable" to "necessary," requiring officers to exhaust alternatives when feasible before using deadly force.',
    legalImplication: 'Use of deadly force that is not "necessary" under the AB 392 standard may be found unlawful under California law.',
    category: 'use_of_force',
    keywords: ['AB 392', 'deadly force', 'necessary', 'imminent threat', 'California'],
  },

  // =========================================================================
  // CHAPTER: De-escalation
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'De-escalation',
    topic: 'De-escalation Duty',
    rule: 'Officers must, when feasible, use de-escalation techniques to reduce the need for force before resorting to physical force options.',
    explanation: 'De-escalation includes verbal persuasion, creating time and distance, using cover, requesting additional resources, and employing crisis intervention techniques.',
    legalImplication: 'Failure to attempt de-escalation when feasible may be considered in evaluating whether force was necessary.',
    category: 'use_of_force',
    keywords: ['de-escalation', 'verbal persuasion', 'time and distance', 'crisis intervention'],
  },
  {
    source: 'POST LD-20',
    chapter: 'De-escalation',
    topic: 'Verbal Commands',
    rule: 'Officers should use clear and calm verbal commands before resorting to physical force, giving the subject a reasonable opportunity to comply.',
    explanation: 'Verbal warnings provide subjects the opportunity to comply voluntarily and help establish that force was a last resort.',
    legalImplication: 'Failure to give verbal commands when feasible may weigh against the reasonableness of subsequent force.',
    category: 'use_of_force',
    keywords: ['verbal commands', 'warning', 'opportunity to comply', 'last resort'],
  },
  {
    source: 'POST LD-20',
    chapter: 'De-escalation',
    topic: 'Time and Distance',
    rule: 'When safe and practical, officers should create time and distance between themselves and a threat to allow for de-escalation and additional response options.',
    explanation: 'Increasing distance and slowing the pace of an encounter provides officers more time to evaluate the situation and consider alternatives to force.',
    legalImplication: 'Officers who unnecessarily close distance with a threat may limit their ability to argue force was necessary.',
    category: 'use_of_force',
    keywords: ['time and distance', 'tactical repositioning', 'de-escalation', 'alternatives'],
  },
  {
    source: 'POST LD-20',
    chapter: 'De-escalation',
    topic: 'Crisis Intervention',
    rule: 'Officers encountering persons in mental health crisis should employ crisis intervention techniques, including active listening, empathy, and patience, before considering force.',
    explanation: 'Persons in mental health crisis may not respond to traditional law enforcement commands. Crisis intervention training (CIT) provides officers with specialized tools.',
    legalImplication: 'Force used against a person in mental health crisis without attempting crisis intervention may be found unreasonable.',
    category: 'use_of_force',
    keywords: ['mental health crisis', 'crisis intervention', 'CIT', 'active listening', 'empathy'],
  },

  // =========================================================================
  // CHAPTER: Force Options
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Force Options',
    topic: 'Force Continuum',
    rule: 'Officers should use the minimum amount of force necessary to control the situation, escalating only as the level of resistance or threat increases.',
    explanation: 'While rigid force continuums are no longer mandated, the principle of proportionality guides force decisions. Officers should match their response to the threat level.',
    legalImplication: 'Use of force grossly disproportionate to the threat or resistance may constitute excessive force.',
    category: 'use_of_force',
    keywords: ['force continuum', 'proportionality', 'minimum force', 'escalation'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Options',
    topic: 'Empty-Hand Techniques',
    rule: 'Empty-hand control techniques include joint locks, pressure points, takedowns, and strikes. These techniques are appropriate for subjects who are actively resisting.',
    explanation: 'Empty-hand techniques represent a moderate level of force. Officers must be trained in proper application to minimize the risk of injury.',
    legalImplication: 'Improper application of control techniques causing unnecessary injury may constitute excessive force.',
    category: 'use_of_force',
    keywords: ['empty-hand', 'control techniques', 'joint locks', 'takedowns', 'active resistance'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Options',
    topic: 'Impact Weapons',
    rule: 'Impact weapons such as batons may be used against subjects who are actively resisting or posing a threat of physical harm to officers or others.',
    explanation: 'Impact weapons deliver focused strikes to specific target areas. Officers must avoid striking the head, neck, spine, and groin unless deadly force is justified.',
    legalImplication: 'Baton strikes to vital areas without deadly force justification may constitute excessive force and result in criminal liability.',
    category: 'use_of_force',
    keywords: ['impact weapons', 'baton', 'strikes', 'target areas', 'active resistance'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Options',
    topic: 'Conducted Energy Devices',
    rule: 'Conducted energy devices (CEDs/Tasers) may be used on subjects who are actively resisting or posing a threat. They should not be used on passively resistant, handcuffed, or restrained subjects.',
    explanation: 'CEDs are considered less-lethal force options. Department policies typically restrict their use against vulnerable populations including pregnant women, elderly persons, and small children.',
    legalImplication: 'Taser use on passive, restrained, or vulnerable subjects may be found unreasonable and constitute excessive force.',
    category: 'use_of_force',
    keywords: ['taser', 'conducted energy device', 'CED', 'less-lethal', 'passive resistance'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Options',
    topic: 'OC Spray',
    rule: 'Oleoresin capsicum (OC) spray may be used as a less-lethal force option against actively resistant subjects. Officers must provide decontamination after deployment.',
    explanation: 'OC spray causes temporary pain and visual impairment. Post-deployment care includes exposure to fresh air and water decontamination.',
    legalImplication: 'Use of OC spray on compliant or restrained subjects may constitute excessive force.',
    category: 'use_of_force',
    keywords: ['OC spray', 'pepper spray', 'less-lethal', 'decontamination'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Options',
    topic: 'Carotid Restraint',
    rule: 'California law prohibits the use of carotid restraints and chokeholds by law enforcement officers.',
    explanation: 'Assembly Bill 1196 (2020) banned the use of carotid restraints by California peace officers due to the risk of serious injury or death.',
    legalImplication: 'Use of a carotid restraint or chokehold is unlawful in California and may result in criminal prosecution.',
    category: 'use_of_force',
    keywords: ['carotid restraint', 'chokehold', 'prohibited', 'AB 1196', 'banned'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Options',
    topic: 'Positional Asphyxia',
    rule: 'Officers must be aware of the risk of positional asphyxia when restraining subjects and must not place subjects face-down with pressure on the back for extended periods.',
    explanation: 'Positional asphyxia can occur when a subject\'s body position restricts breathing. Officers must monitor breathing and reposition subjects as soon as practical.',
    legalImplication: 'Death or injury from positional asphyxia due to officer negligence may result in criminal charges and civil liability.',
    category: 'use_of_force',
    keywords: ['positional asphyxia', 'prone position', 'restraint', 'breathing', 'monitoring'],
  },

  // =========================================================================
  // CHAPTER: Deadly Force
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Deadly Force',
    topic: 'Deadly Force Authorization',
    rule: 'Deadly force is authorized only when the officer reasonably believes it is necessary to defend against an imminent threat of death or serious bodily injury to the officer or another person.',
    explanation: 'The threat must be imminent, meaning the subject has the present ability, opportunity, and apparent intent to cause death or serious bodily injury.',
    legalImplication: 'Use of deadly force without an imminent deadly threat is unlawful and may result in criminal prosecution.',
    category: 'use_of_force',
    keywords: ['deadly force', 'imminent threat', 'serious bodily injury', 'authorization'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Deadly Force',
    topic: 'Fleeing Felon',
    rule: 'An officer may use deadly force to prevent the escape of a fleeing suspect only if the officer has probable cause to believe the suspect poses a significant threat of death or serious physical injury to the officer or others.',
    explanation: 'Per Tennessee v. Garner, deadly force against a fleeing felon is limited to situations where the suspect is dangerous. An unarmed, non-violent suspect may not be shot to prevent escape.',
    legalImplication: 'Shooting an unarmed fleeing suspect who poses no imminent danger is unlawful.',
    category: 'use_of_force',
    keywords: ['fleeing felon', 'Tennessee v Garner', 'deadly force', 'significant threat'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Deadly Force',
    topic: 'Shooting at Moving Vehicles',
    rule: 'Officers should not discharge firearms at or from a moving vehicle unless the occupants are using deadly force by means other than the vehicle itself, and no other reasonable option exists.',
    explanation: 'Most department policies restrict shooting at moving vehicles because the risk to bystanders is high and disabling the driver may cause the vehicle to become an uncontrolled hazard.',
    legalImplication: 'Shooting at a moving vehicle when the vehicle alone is the threat may be found unreasonable.',
    category: 'use_of_force',
    keywords: ['moving vehicle', 'firearms', 'deadly force', 'bystander risk'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Deadly Force',
    topic: 'Warning Shots',
    rule: 'Warning shots are generally prohibited due to the risk of unintended harm to bystanders and the potential for escalating the situation.',
    explanation: 'Most agencies prohibit warning shots because of the unpredictable trajectory of bullets and the risk that a warning shot may strike an unintended person.',
    legalImplication: 'An officer who fires a warning shot that injures a bystander may face criminal and civil liability.',
    category: 'use_of_force',
    keywords: ['warning shots', 'prohibited', 'bystander risk', 'firearms'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Deadly Force',
    topic: 'Duty to Intercede',
    rule: 'Officers have a duty to intercede when they observe another officer using force that is clearly beyond what is objectively reasonable under the circumstances.',
    explanation: 'California law and department policies require officers to take action to stop the use of excessive force by fellow officers when it is safe to do so.',
    legalImplication: 'Failure to intercede when witnessing excessive force may result in disciplinary action, criminal liability, and civil liability.',
    category: 'use_of_force',
    keywords: ['duty to intercede', 'excessive force', 'intervene', 'fellow officer'],
  },

  // =========================================================================
  // CHAPTER: Force Reporting and Review
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Force Reporting',
    topic: 'Force Documentation',
    rule: 'All uses of force must be documented in a detailed use-of-force report, including the actions of the subject, the specific force used, the reason for the force, and any injuries.',
    explanation: 'Thorough documentation protects both the officer and the department. Reports should be written as soon as practical after the incident.',
    legalImplication: 'Inadequate force documentation may create an inference of concealment and may undermine the officer\'s account.',
    category: 'use_of_force',
    keywords: ['force report', 'documentation', 'injuries', 'use of force'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Reporting',
    topic: 'Supervisor Review',
    rule: 'A supervisor must respond to the scene of any reportable use of force, conduct an initial review, and ensure all evidence is properly documented.',
    explanation: 'Supervisory review is essential for accountability. The supervisor should interview witnesses, review body-worn camera footage, and document injuries.',
    legalImplication: 'Failure to conduct adequate supervisory review may indicate a pattern of deliberate indifference.',
    category: 'use_of_force',
    keywords: ['supervisor review', 'accountability', 'body camera', 'witness interviews'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Reporting',
    topic: 'Medical Aid',
    rule: 'Officers must provide or request medical aid for any person who is injured or complains of injury as a result of a use of force.',
    explanation: 'The duty to provide medical aid arises from both constitutional requirements (deliberate indifference standard) and department policy.',
    legalImplication: 'Failure to provide medical aid to an injured person in custody may constitute deliberate indifference and violate the Fourteenth Amendment.',
    category: 'use_of_force',
    keywords: ['medical aid', 'injury', 'deliberate indifference', 'duty of care'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Reporting',
    topic: 'Body-Worn Camera Requirements',
    rule: 'Officers must activate body-worn cameras prior to any use of force encounter and must not deactivate the camera until the encounter is concluded.',
    explanation: 'Body-worn camera footage provides objective evidence of the encounter and is critical for force review and investigation.',
    legalImplication: 'Failure to activate or deactivation of body-worn cameras during a use of force may create an adverse inference.',
    category: 'use_of_force',
    keywords: ['body-worn camera', 'BWC', 'activation', 'force encounter', 'evidence'],
  },

  // =========================================================================
  // CHAPTER: Special Force Situations
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Force Against Restrained Persons',
    rule: 'Officers must not use force against persons who are handcuffed or otherwise restrained unless the person is actively attacking, attempting to escape, or posing an imminent threat.',
    explanation: 'Once a person is restrained, the justification for force diminishes significantly. Gratuitous force against restrained persons is unlawful.',
    legalImplication: 'Force against restrained persons who are not posing a threat constitutes excessive force and may result in criminal charges.',
    category: 'use_of_force',
    keywords: ['restrained', 'handcuffed', 'excessive force', 'gratuitous force'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Force Against Mentally Ill',
    rule: 'Officers should use the least amount of force necessary when dealing with persons who are mentally ill, recognizing that such persons may not be able to comply with commands due to their condition.',
    explanation: 'Mental illness may affect a person\'s ability to understand and comply with officer commands. Officers should use CIT training and request mental health resources.',
    legalImplication: 'Failure to account for a person\'s mental illness when using force may render the force unreasonable.',
    category: 'use_of_force',
    keywords: ['mental illness', 'CIT', 'least force', 'inability to comply'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Force Against Minors',
    rule: 'Officers must consider the age and size of a juvenile when determining the appropriate level of force, and should use the least intrusive means available.',
    explanation: 'The use of force against minors is held to a higher standard of scrutiny. Officers should consider the juvenile\'s physical and emotional vulnerability.',
    legalImplication: 'Force that might be reasonable against an adult may be found excessive when applied to a minor.',
    category: 'use_of_force',
    keywords: ['juvenile', 'minor', 'age', 'size', 'least intrusive'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Force Against Pregnant Women',
    rule: 'Officers must exercise extreme caution when using force against pregnant women, avoiding strikes or pressure to the abdomen and using the least amount of force necessary.',
    explanation: 'Force against pregnant women poses additional risk of harm to both the woman and the unborn child. Officers should prioritize verbal commands and minimal physical intervention.',
    legalImplication: 'Excessive force against a pregnant woman may result in enhanced civil liability and criminal charges.',
    category: 'use_of_force',
    keywords: ['pregnant', 'caution', 'abdomen', 'minimal force'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Crowd Control',
    rule: 'During crowd control situations, officers may use force only against individuals who are actively engaged in unlawful conduct, not against a crowd generally.',
    explanation: 'Indiscriminate use of force against a crowd violates the First and Fourth Amendments. Force must be targeted at specific individuals engaging in specific unlawful acts.',
    legalImplication: 'Indiscriminate force against peaceful protesters may result in significant civil rights liability.',
    category: 'use_of_force',
    keywords: ['crowd control', 'protest', 'first amendment', 'indiscriminate force'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Canine Deployment',
    rule: 'Police canine deployment constitutes a significant use of force and must be justified by specific articulable facts indicating the suspect poses a threat or is actively evading arrest.',
    explanation: 'Canine bites can cause serious injury. Officers must give a warning before deploying a canine unless doing so would compromise officer safety.',
    legalImplication: 'Canine deployment without adequate justification or warning may constitute excessive force.',
    category: 'use_of_force',
    keywords: ['canine', 'K-9', 'deployment', 'warning', 'significant force'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Less-Lethal Munitions',
    rule: 'Less-lethal munitions such as bean bag rounds and rubber bullets must be deployed in accordance with department policy and targeted at approved body areas.',
    explanation: 'Less-lethal munitions can cause serious injury or death if improperly deployed. Shots to the head, neck, or chest should be avoided unless deadly force is justified.',
    legalImplication: 'Improper deployment of less-lethal munitions causing serious injury may constitute excessive force.',
    category: 'use_of_force',
    keywords: ['less-lethal munitions', 'bean bag', 'rubber bullets', 'target areas'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Special Force Situations',
    topic: 'Vehicle Ramming',
    rule: 'Intentional ramming of a suspect\'s vehicle constitutes deadly force and is subject to the same legal standards as any other application of deadly force.',
    explanation: 'PIT maneuvers and intentional vehicle contact at high speeds carry significant risk of death or serious injury and must be justified by an imminent deadly threat.',
    legalImplication: 'Vehicle ramming without deadly force justification is unlawful and may result in criminal charges.',
    category: 'use_of_force',
    keywords: ['vehicle ramming', 'PIT maneuver', 'deadly force', 'pursuit'],
  },

  // =========================================================================
  // CHAPTER: Force Training Requirements
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Force Training',
    topic: 'Perishable Skills Training',
    rule: 'Officers must complete regular perishable skills training in defensive tactics, firearms, and de-escalation to maintain proficiency in force options.',
    explanation: 'POST requires periodic training updates to ensure officers maintain competency in the use of force and are current on legal standards and department policies.',
    legalImplication: 'An officer who causes injury due to inadequate training may expose the department to municipal liability under a failure-to-train theory.',
    category: 'use_of_force',
    keywords: ['perishable skills', 'training', 'defensive tactics', 'firearms', 'proficiency'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Training',
    topic: 'Scenario-Based Training',
    rule: 'Officers must participate in scenario-based training that integrates de-escalation, communication, and force decision-making in realistic situations.',
    explanation: 'Scenario-based training develops critical thinking and decision-making skills that cannot be taught through classroom instruction alone.',
    legalImplication: 'Departments that fail to provide adequate scenario-based training may be found deliberately indifferent to use-of-force risks.',
    category: 'use_of_force',
    keywords: ['scenario-based training', 'decision-making', 'realistic situations', 'force training'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Force Training',
    topic: 'Implicit Bias Training',
    rule: 'Officers must receive training on implicit bias and its potential effect on use-of-force decisions, including recognizing and mitigating bias-influenced responses.',
    explanation: 'California AB 953 requires bias training for all officers. Implicit biases can affect split-second force decisions and must be addressed through education and awareness.',
    legalImplication: 'Force decisions influenced by racial or other biases may violate equal protection guarantees and expose officers to civil rights liability.',
    category: 'use_of_force',
    keywords: ['implicit bias', 'AB 953', 'training', 'bias-influenced', 'equal protection'],
  },

  // =========================================================================
  // CHAPTER: Pursuit-Related Force
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Pursuit-Related Force',
    topic: 'Pursuit Decision-Making',
    rule: 'Officers must weigh the risk of pursuit against the severity of the offense and the danger to the public before initiating or continuing a vehicle pursuit.',
    explanation: 'Vehicle pursuits create significant risk to officers, suspects, and the public. Officers must continuously reassess whether the pursuit should continue.',
    legalImplication: 'An officer who continues a pursuit that creates unreasonable danger to the public may face civil liability for resulting injuries.',
    category: 'pursuit',
    keywords: ['pursuit', 'risk assessment', 'public safety', 'vehicle chase'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Pursuit-Related Force',
    topic: 'Pursuit Termination',
    rule: 'A pursuit should be terminated when the risk to the public outweighs the need to apprehend the suspect, particularly for minor offenses.',
    explanation: 'Supervisors may order termination of a pursuit. Officers must comply immediately with termination orders.',
    legalImplication: 'Failure to terminate a pursuit when ordered or when risks clearly outweigh benefits may result in liability for resulting injuries.',
    category: 'pursuit',
    keywords: ['pursuit termination', 'risk-benefit', 'supervisor order', 'public safety'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Pursuit-Related Force',
    topic: 'Tire Deflation Devices',
    rule: 'Tire deflation devices (spike strips) may be deployed during pursuits in accordance with department policy, with proper consideration of risks to the suspect and bystanders.',
    explanation: 'Spike strips are generally considered a reasonable alternative to continued pursuit or more forceful intervention. Officers must be trained in proper deployment.',
    legalImplication: 'Improper deployment of spike strips causing injury to bystanders may result in civil liability.',
    category: 'pursuit',
    keywords: ['spike strips', 'tire deflation', 'pursuit intervention', 'bystander safety'],
  },

  // =========================================================================
  // CHAPTER: Post-Force Procedures
  // =========================================================================
  {
    source: 'POST LD-20',
    chapter: 'Post-Force Procedures',
    topic: 'Critical Incident Protocols',
    rule: 'Following a critical force incident involving serious injury or death, the involved officer must be separated from the scene and the investigation must be handled by independent investigators.',
    explanation: 'Critical incident protocols protect the integrity of the investigation and the rights of the involved officer. The officer should be provided with peer support resources.',
    legalImplication: 'Failure to follow critical incident protocols may compromise the investigation and create an appearance of cover-up.',
    category: 'use_of_force',
    keywords: ['critical incident', 'investigation', 'separation', 'independent investigators'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Post-Force Procedures',
    topic: 'Compelled Statements',
    rule: 'An officer involved in a force incident may be compelled to provide an administrative statement, but that statement cannot be used in criminal proceedings against the officer under Garrity protections.',
    explanation: 'Garrity v. New Jersey established that statements compelled under threat of termination are protected from use in criminal prosecution.',
    legalImplication: 'Using a Garrity-protected statement in criminal proceedings violates the officer\'s Fifth Amendment rights.',
    category: 'use_of_force',
    keywords: ['Garrity', 'compelled statement', 'administrative', 'fifth amendment', 'criminal'],
  },
  {
    source: 'POST LD-20',
    chapter: 'Post-Force Procedures',
    topic: 'Civilian Oversight',
    rule: 'California law requires civilian oversight of law enforcement use-of-force investigations, including review of officer-involved shootings and in-custody deaths.',
    explanation: 'Senate Bill 1421 and subsequent legislation increased transparency and civilian oversight of force incidents. This includes public access to certain investigation records.',
    legalImplication: 'Agencies that fail to comply with civilian oversight requirements may face legal sanctions and loss of public trust.',
    category: 'use_of_force',
    keywords: ['civilian oversight', 'SB 1421', 'transparency', 'officer-involved shooting'],
  },
];
