// ============================================
// POST LD-16: Search & Seizure — Seed Data
// ============================================

import type { ParsedDoctrineChunk } from './types.ts';

export const LD16_DOCTRINE_RULES: ParsedDoctrineChunk[] = [
  // =========================================================================
  // Search Warrants
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Search Warrants',
    topic: 'Warrant Requirements',
    rule: 'A search warrant must be supported by probable cause, describe with particularity the place to be searched and the items to be seized, and be issued by a neutral and detached magistrate.',
    explanation: 'The Fourth Amendment requires warrants to meet three criteria: probable cause established by oath or affirmation, particular description of the place and items, and issuance by a judicial officer.',
    legalImplication: 'A warrant lacking any of these elements is defective, and evidence obtained may be suppressed.',
    category: 'search',
    keywords: ['search warrant', 'probable cause', 'particularity', 'magistrate', 'fourth amendment'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Search Warrants',
    topic: 'Warrant Execution',
    rule: 'Officers executing a search warrant must knock and announce their presence and purpose before entering, unless exigent circumstances justify a no-knock entry.',
    explanation: 'The knock-and-announce rule is a constitutional requirement. Officers must give occupants a reasonable time to respond before forcing entry.',
    legalImplication: 'Failure to knock and announce, absent exigent circumstances, may result in suppression of evidence.',
    category: 'search',
    keywords: ['knock and announce', 'search warrant', 'entry', 'exigent circumstances'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Search Warrants',
    topic: 'Warrant Scope',
    rule: 'A search conducted pursuant to a warrant must be limited to the areas described in the warrant and to items specified in the warrant.',
    explanation: 'Officers may not exceed the scope of the warrant. Searching areas or seizing items not described requires additional authority.',
    legalImplication: 'Evidence seized outside the scope of the warrant may be suppressed unless another exception applies.',
    category: 'search',
    keywords: ['warrant scope', 'search warrant', 'particularity', 'seizure'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Search Warrants',
    topic: 'Warrant Staleness',
    rule: 'The information supporting probable cause for a search warrant must be current. Stale information may not support a valid warrant.',
    explanation: 'Courts evaluate whether the information in the affidavit is sufficiently recent to establish that the items sought are likely still present at the location.',
    legalImplication: 'A warrant based on stale information may be found invalid, resulting in suppression of evidence.',
    category: 'search',
    keywords: ['staleness', 'search warrant', 'probable cause', 'affidavit'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Search Warrants',
    topic: 'Warrant Affidavit',
    rule: 'The affidavit supporting a search warrant must contain sufficient facts to establish probable cause and must not contain material misrepresentations or omissions.',
    explanation: 'Under Franks v. Delaware, a defendant may challenge a warrant if the affidavit contains deliberate or reckless falsehoods material to the probable cause finding.',
    legalImplication: 'If material misrepresentations are found, the warrant may be voided and evidence suppressed.',
    category: 'search',
    keywords: ['affidavit', 'search warrant', 'probable cause', 'Franks', 'misrepresentation'],
  },

  // =========================================================================
  // Probable Cause for Searches
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Probable Cause for Searches',
    topic: 'Probable Cause Standard',
    rule: 'Probable cause to search exists when there is a fair probability that contraband or evidence of a crime will be found in a particular place.',
    explanation: 'This standard is less than certainty but more than reasonable suspicion. It requires specific facts establishing a nexus between the evidence sought and the location to be searched.',
    legalImplication: 'A search without probable cause violates the Fourth Amendment unless a recognized exception applies.',
    category: 'search',
    keywords: ['probable cause', 'search', 'fair probability', 'contraband', 'evidence'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Probable Cause for Searches',
    topic: 'Probable Cause Standard',
    rule: 'Probable cause must be based on objective facts and circumstances, not on an officer\'s subjective belief or mere suspicion.',
    explanation: 'The test for probable cause is objective: whether a reasonable person with the same information would believe evidence is present. Personal hunches are insufficient.',
    legalImplication: 'Searches based on subjective belief without objective facts may be found unlawful.',
    category: 'search',
    keywords: ['probable cause', 'objective facts', 'reasonable person', 'search'],
  },

  // =========================================================================
  // Consent Searches
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Consent Searches',
    topic: 'Voluntary Consent',
    rule: 'Consent to search must be given voluntarily and not be the product of duress, coercion, or submission to a claim of authority.',
    explanation: 'Voluntariness is determined by examining the totality of the circumstances, including the person\'s age, education, intelligence, and whether they were advised of the right to refuse.',
    legalImplication: 'Consent obtained through coercion is involuntary, and the resulting search is unlawful.',
    category: 'search',
    keywords: ['consent search', 'voluntary', 'coercion', 'duress', 'totality of circumstances'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Consent Searches',
    topic: 'Consent Scope',
    rule: 'The scope of a consent search is limited to the terms of the consent given. A person may limit or revoke consent at any time.',
    explanation: 'If a person consents to a search of a specific area, the officer may not search beyond that area. The person may withdraw consent at any point during the search.',
    legalImplication: 'Exceeding the scope of consent renders the excess portion of the search unlawful.',
    category: 'search',
    keywords: ['consent search', 'scope', 'revoke', 'withdraw', 'limitation'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Consent Searches',
    topic: 'Third-Party Consent',
    rule: 'A third party may consent to a search of shared premises if they have common authority over the area to be searched.',
    explanation: 'Common authority is based on mutual use of the property by persons generally having joint access or control. Apparent authority may also suffice if the officer reasonably believes the person has authority.',
    legalImplication: 'Consent from a person without actual or apparent authority over the area is invalid.',
    category: 'search',
    keywords: ['third-party consent', 'common authority', 'shared premises', 'consent search'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Consent Searches',
    topic: 'Consent Documentation',
    rule: 'Officers should document consent to search, including who gave consent, the scope of consent, and whether the person was informed of the right to refuse.',
    explanation: 'Written consent forms are preferred but not legally required. Clear documentation helps establish voluntariness if challenged in court.',
    legalImplication: 'Failure to document consent may weaken the prosecution\'s ability to prove voluntariness.',
    category: 'search',
    keywords: ['consent', 'documentation', 'voluntariness', 'written consent'],
  },

  // =========================================================================
  // Exigent Circumstances
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Exigent Circumstances',
    topic: 'Exigent Circumstances Exception',
    rule: 'Exigent circumstances allow warrantless entry and search when there is an immediate need that makes obtaining a warrant impractical, such as imminent destruction of evidence, hot pursuit, or threat to life.',
    explanation: 'This exception is narrowly applied. Officers must be able to articulate specific facts creating the exigency. The mere possibility that evidence might be destroyed is insufficient.',
    legalImplication: 'If the claimed exigency is not supported by the facts, the warrantless search is unlawful and evidence may be suppressed.',
    category: 'search',
    keywords: ['exigent circumstances', 'warrantless', 'evidence destruction', 'hot pursuit', 'emergency'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Exigent Circumstances',
    topic: 'Police-Created Exigency',
    rule: 'Officers may not create exigent circumstances through their own conduct for the purpose of avoiding the warrant requirement.',
    explanation: 'Per Kentucky v. King, if officers create the exigency by threatening to break down a door or engaging in conduct that would cause evidence destruction, the exception does not apply.',
    legalImplication: 'Police-created exigencies do not justify warrantless searches, and evidence obtained may be suppressed.',
    category: 'search',
    keywords: ['police-created exigency', 'warrantless', 'Kentucky v King', 'evidence destruction'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Exigent Circumstances',
    topic: 'Emergency Aid',
    rule: 'Officers may enter a dwelling without a warrant when they have an objectively reasonable basis for believing that an occupant is seriously injured or imminently threatened with such injury.',
    explanation: 'The emergency aid doctrine allows entry to render aid. The officer\'s subjective motivation is irrelevant; the standard is whether a reasonable officer would believe emergency assistance is needed.',
    legalImplication: 'Entry under false pretense of emergency aid is unlawful and evidence discovered may be suppressed.',
    category: 'search',
    keywords: ['emergency aid', 'warrantless entry', 'serious injury', 'imminent threat'],
  },

  // =========================================================================
  // Search Incident to Arrest
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Search Incident to Arrest',
    topic: 'Search Incident to Arrest',
    rule: 'A lawful custodial arrest permits a full search of the arrestee\'s person and the area within the arrestee\'s immediate control (lunging area).',
    explanation: 'This exception is justified by officer safety and prevention of evidence destruction. The arrest must be lawful; if the arrest is invalid, the search is also invalid.',
    legalImplication: 'A search incident to an unlawful arrest is itself unlawful, and all evidence obtained is subject to suppression.',
    category: 'search',
    keywords: ['search incident to arrest', 'custodial arrest', 'immediate control', 'lunging area'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Search Incident to Arrest',
    topic: 'Search Incident to Arrest — Timing',
    rule: 'A search incident to arrest must be substantially contemporaneous with the arrest. A delayed search may not qualify under this exception.',
    explanation: 'The search should occur close in time to the arrest. While it may occur slightly before or after the formal arrest, significant delays undermine the justification.',
    legalImplication: 'A search that is not contemporaneous with the arrest may require separate justification.',
    category: 'search',
    keywords: ['search incident to arrest', 'contemporaneous', 'timing', 'delayed search'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Search Incident to Arrest',
    topic: 'Cell Phone Search',
    rule: 'Under Riley v. California, officers may not search the contents of a cell phone incident to arrest without a warrant.',
    explanation: 'The Supreme Court held that the immense storage capacity of cell phones creates a privacy interest that outweighs the government\'s interests in a warrantless search.',
    legalImplication: 'Warrantless searches of cell phone contents are unlawful unless another exception applies, such as exigent circumstances or consent.',
    category: 'search',
    keywords: ['cell phone search', 'Riley v California', 'warrant', 'digital privacy', 'search incident to arrest'],
  },

  // =========================================================================
  // Vehicle Searches
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Vehicle Searches',
    topic: 'Automobile Exception',
    rule: 'Under the automobile exception, officers may search a vehicle without a warrant if there is probable cause to believe it contains evidence of a crime or contraband.',
    explanation: 'The automobile exception is based on the reduced expectation of privacy in vehicles and their inherent mobility. Probable cause must exist at the time of the search.',
    legalImplication: 'A vehicle search without probable cause or other recognized exception violates the Fourth Amendment.',
    category: 'search',
    keywords: ['automobile exception', 'vehicle search', 'probable cause', 'warrantless', 'fourth amendment'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Vehicle Searches',
    topic: 'Vehicle Inventory Search',
    rule: 'An inventory search of an impounded vehicle is permissible if conducted pursuant to standardized departmental procedures.',
    explanation: 'Inventory searches serve to protect the owner\'s property, protect the department from false claims, and protect officers from danger. They must not be used as a pretext for investigation.',
    legalImplication: 'An inventory search that deviates from standard procedures or is pretextual may be found unlawful.',
    category: 'search',
    keywords: ['inventory search', 'impounded vehicle', 'standard procedures', 'pretext'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Vehicle Searches',
    topic: 'Vehicle Search — Gant Limitation',
    rule: 'Under Arizona v. Gant, a search incident to arrest of a vehicle is limited to situations where the arrestee could access the vehicle at the time of the search or where evidence of the crime of arrest might reasonably be found in the vehicle.',
    explanation: 'If the arrestee is secured and cannot access the vehicle, the search incident to arrest exception does not apply to the vehicle. Probable cause is then required.',
    legalImplication: 'Vehicle searches exceeding the Gant limitations without probable cause are unlawful.',
    category: 'search',
    keywords: ['Arizona v Gant', 'vehicle search', 'search incident to arrest', 'passenger compartment'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Vehicle Searches',
    topic: 'Container Searches in Vehicles',
    rule: 'If probable cause exists to search a vehicle, officers may search any container within the vehicle that could reasonably contain the evidence sought.',
    explanation: 'Per United States v. Ross, the scope of the search extends to all areas and containers that might contain the evidence, including the trunk, glove compartment, and closed containers.',
    legalImplication: 'Searching containers beyond the scope justified by probable cause may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['container search', 'vehicle search', 'probable cause', 'United States v Ross'],
  },

  // =========================================================================
  // Plain View Doctrine
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Plain View Doctrine',
    topic: 'Plain View Requirements',
    rule: 'Under the plain view doctrine, an officer may seize evidence without a warrant if: (1) the officer is lawfully present, (2) the item is in plain view, and (3) the incriminating nature of the item is immediately apparent.',
    explanation: 'All three elements must be met. The officer cannot move or manipulate items to bring them into view. The discovery must be inadvertent in the sense that the officer is lawfully present for a legitimate purpose.',
    legalImplication: 'Seizure of items when any element of plain view is not met is unlawful and the evidence may be suppressed.',
    category: 'search',
    keywords: ['plain view', 'seizure', 'lawfully present', 'immediately apparent', 'incriminating'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Plain View Doctrine',
    topic: 'Plain View — No Manipulation',
    rule: 'Officers may not move, open, or manipulate objects to determine their incriminating nature under the plain view doctrine.',
    explanation: 'Moving objects to create a view or opening closed containers goes beyond plain view and constitutes a search requiring separate justification.',
    legalImplication: 'Evidence discovered through manipulation is not admissible under plain view and may be suppressed.',
    category: 'search',
    keywords: ['plain view', 'manipulation', 'search', 'closed container'],
  },

  // =========================================================================
  // Electronic Searches
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Electronic Searches',
    topic: 'Electronic Device Search',
    rule: 'Searching electronic devices such as computers, tablets, and smartphones generally requires a warrant based on probable cause.',
    explanation: 'Electronic devices contain vast amounts of personal information and are afforded strong Fourth Amendment protections. The warrant must describe with particularity the data to be searched.',
    legalImplication: 'Warrantless searches of electronic devices are presumptively unreasonable and evidence may be suppressed.',
    category: 'search',
    keywords: ['electronic search', 'digital evidence', 'warrant', 'computer', 'smartphone', 'fourth amendment'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Electronic Searches',
    topic: 'GPS Tracking',
    rule: 'Attaching a GPS tracking device to a vehicle or person constitutes a search under the Fourth Amendment and requires a warrant.',
    explanation: 'Per United States v. Jones, physical attachment of a GPS device to a vehicle is a search. Extended electronic surveillance of location data also implicates Fourth Amendment protections.',
    legalImplication: 'GPS tracking without a warrant is unlawful and location evidence may be suppressed.',
    category: 'search',
    keywords: ['GPS tracking', 'warrant', 'United States v Jones', 'fourth amendment', 'location data'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Electronic Searches',
    topic: 'Cell Site Location Information',
    rule: 'Obtaining historical cell site location information (CSLI) constitutes a search under the Fourth Amendment and generally requires a warrant.',
    explanation: 'Per Carpenter v. United States, the government must generally obtain a warrant supported by probable cause before acquiring CSLI records from wireless carriers.',
    legalImplication: 'CSLI obtained without a warrant may be suppressed unless an exception applies.',
    category: 'search',
    keywords: ['CSLI', 'cell site location', 'Carpenter', 'warrant', 'fourth amendment', 'wireless carrier'],
  },

  // =========================================================================
  // Additional Search & Seizure Rules
  // =========================================================================
  {
    source: 'POST LD-16',
    chapter: 'Protective Sweeps',
    topic: 'Protective Sweep',
    rule: 'During an in-home arrest, officers may conduct a protective sweep of the premises if they have a reasonable belief that the area harbors an individual posing a danger.',
    explanation: 'A protective sweep is a quick, limited search of premises for persons who may pose danger. It must be based on articulable facts, not a hunch.',
    legalImplication: 'An unjustified protective sweep may render evidence discovered during the sweep inadmissible.',
    category: 'search',
    keywords: ['protective sweep', 'in-home arrest', 'officer safety', 'articulable facts'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Border and Airport Searches',
    topic: 'Border Search Exception',
    rule: 'Routine searches at international borders and their functional equivalents may be conducted without a warrant or probable cause.',
    explanation: 'The government\'s interest in controlling who and what enters the country allows broader search authority at borders. However, highly intrusive searches may require reasonable suspicion.',
    legalImplication: 'Non-routine or highly intrusive border searches without reasonable suspicion may be found unlawful.',
    category: 'search',
    keywords: ['border search', 'international border', 'functional equivalent', 'customs'],
  },
  {
    source: 'POST LD-16',
    chapter: 'School Searches',
    topic: 'School Search Standard',
    rule: 'Searches of students by school officials require only reasonable suspicion, not probable cause, under the reduced standard established by New Jersey v. T.L.O.',
    explanation: 'The school setting allows a relaxed search standard. The search must be justified at its inception and reasonable in scope given the circumstances.',
    legalImplication: 'A school search without reasonable suspicion or that is excessive in scope may violate the Fourth Amendment.',
    category: 'search',
    keywords: ['school search', 'reasonable suspicion', 'New Jersey v TLO', 'student'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Probation and Parole Searches',
    topic: 'Probation Search',
    rule: 'Persons on probation or parole with search conditions may be searched without a warrant or probable cause, based on the search condition of their supervision.',
    explanation: 'Search conditions reduce the expectation of privacy. Officers must be aware of the search condition before conducting the search.',
    legalImplication: 'Searching a probationer without knowledge of a valid search condition may be unlawful.',
    category: 'search',
    keywords: ['probation search', 'parole search', 'search condition', 'reduced expectation of privacy'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Consent Searches',
    topic: 'Consent During Traffic Stops',
    rule: 'An officer may request consent to search during a lawful traffic stop, but extending the stop beyond its purpose solely to seek consent may be unlawful.',
    explanation: 'Per Rodriguez v. United States, extending a traffic stop to conduct a dog sniff or seek consent, without reasonable suspicion of additional criminal activity, violates the Fourth Amendment.',
    legalImplication: 'Evidence obtained after an unlawfully extended traffic stop may be suppressed.',
    category: 'search',
    keywords: ['consent', 'traffic stop', 'Rodriguez', 'extension', 'fourth amendment'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Abandoned Property',
    topic: 'Abandoned Property',
    rule: 'Property that has been voluntarily abandoned is not protected by the Fourth Amendment and may be searched without a warrant.',
    explanation: 'A person who voluntarily discards property has no reasonable expectation of privacy in that property. Whether property is truly abandoned depends on the circumstances.',
    legalImplication: 'If property is not truly abandoned (e.g., discarded only due to police coercion), the search may be unlawful.',
    category: 'search',
    keywords: ['abandoned property', 'expectation of privacy', 'fourth amendment', 'discarded'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Open Fields',
    topic: 'Open Fields Doctrine',
    rule: 'The open fields doctrine provides that areas outside the curtilage of a home are not protected by the Fourth Amendment, even if the property is privately owned.',
    explanation: 'Open fields do not receive Fourth Amendment protection because there is no reasonable expectation of privacy. Curtilage, the area immediately surrounding the home, is protected.',
    legalImplication: 'Searches of curtilage without a warrant may violate the Fourth Amendment; searches of open fields generally do not.',
    category: 'search',
    keywords: ['open fields', 'curtilage', 'fourth amendment', 'expectation of privacy'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Good Faith Exception',
    topic: 'Good Faith Exception',
    rule: 'Under the good faith exception, evidence obtained by officers acting in reasonable reliance on a warrant later found to be invalid may still be admissible.',
    explanation: 'Per United States v. Leon, the exclusionary rule does not apply when officers reasonably rely on a facially valid warrant issued by a neutral magistrate.',
    legalImplication: 'The good faith exception does not apply if the officer misled the magistrate, the magistrate abandoned neutrality, the affidavit was so lacking that belief in probable cause was unreasonable, or the warrant was so facially deficient that reliance was unreasonable.',
    category: 'search',
    keywords: ['good faith exception', 'United States v Leon', 'warrant', 'exclusionary rule', 'reasonable reliance'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Seizure of Persons',
    topic: 'Seizure During Search',
    rule: 'Officers executing a search warrant at a premises may detain the occupants during the search for officer safety purposes.',
    explanation: 'Per Michigan v. Summers, officers may detain persons present during the execution of a search warrant. The detention must not be unduly prolonged.',
    legalImplication: 'Detention of persons at a premises being searched must be reasonable in scope and duration.',
    category: 'search',
    keywords: ['seizure', 'detention', 'search warrant', 'Michigan v Summers', 'occupants'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Strip and Body Cavity Searches',
    topic: 'Strip Search',
    rule: 'Strip searches and body cavity searches are highly intrusive and require a higher level of justification than ordinary searches.',
    explanation: 'Strip searches generally require reasonable suspicion that the person is concealing contraband or weapons. Body cavity searches typically require a warrant.',
    legalImplication: 'Unjustified strip or body cavity searches may violate the Fourth Amendment and result in civil liability.',
    category: 'search',
    keywords: ['strip search', 'body cavity search', 'reasonable suspicion', 'warrant', 'intrusive'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Exclusionary Rule Application',
    topic: 'Exclusionary Rule',
    rule: 'The exclusionary rule prohibits the use of evidence obtained in violation of the Fourth Amendment in the prosecution\'s case-in-chief.',
    explanation: 'The rule is designed to deter unlawful police conduct. It applies to evidence directly obtained through the violation and to derivative evidence under the fruit of the poisonous tree doctrine.',
    legalImplication: 'Evidence obtained through Fourth Amendment violations is inadmissible, along with all derivative evidence unless an exception applies.',
    category: 'constitutional',
    keywords: ['exclusionary rule', 'fourth amendment', 'suppression', 'fruit of the poisonous tree', 'case-in-chief'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Exclusionary Rule Application',
    topic: 'Independent Source Doctrine',
    rule: 'Evidence obtained through an independent source untainted by the illegal conduct is admissible under the independent source doctrine.',
    explanation: 'If officers obtain evidence through a source wholly independent of the constitutional violation, the evidence is not subject to the exclusionary rule.',
    legalImplication: 'The prosecution bears the burden of proving the evidence was obtained through a genuinely independent source.',
    category: 'constitutional',
    keywords: ['independent source', 'exclusionary rule', 'untainted', 'fourth amendment'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Exclusionary Rule Application',
    topic: 'Inevitable Discovery',
    rule: 'Evidence that would inevitably have been discovered through lawful means is admissible under the inevitable discovery doctrine.',
    explanation: 'The prosecution must establish by a preponderance of the evidence that the evidence would have been discovered lawfully regardless of the constitutional violation.',
    legalImplication: 'The inevitable discovery exception prevents suppression when lawful discovery was certain to occur.',
    category: 'constitutional',
    keywords: ['inevitable discovery', 'exclusionary rule', 'lawful means', 'fourth amendment'],
  },
  {
    source: 'POST LD-16',
    chapter: 'Exclusionary Rule Application',
    topic: 'Attenuation Doctrine',
    rule: 'Evidence may be admissible if the connection between the unconstitutional conduct and the discovery of evidence is sufficiently attenuated.',
    explanation: 'Under the attenuation doctrine, factors considered include the temporal proximity, intervening circumstances, and the purpose and flagrancy of the official misconduct.',
    legalImplication: 'Evidence may survive suppression if the causal chain between the violation and discovery is broken.',
    category: 'constitutional',
    keywords: ['attenuation', 'exclusionary rule', 'causal connection', 'intervening circumstances'],
  },
];

export const LD16_RULE_COUNT = LD16_DOCTRINE_RULES.length;
