// ============================================================================
// CourtAccess — Canonical Sentencing, Enhancement & Criminal Exposure Center (Program 93)
// The definitive California sentencing-analysis workspace. Classification and
// verbatim penalty provisions are repository-backed; enhancements are detected
// within real repository text (cited). Structured terms and numeric exposure
// are UNKNOWN and NEVER estimated. Export: Print/PDF, DOCX.
// ============================================================================

import { useEffect, useMemo, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  Loader2, Printer, RefreshCw, AlertTriangle, ArrowLeft, Scale, Gavel, Landmark, Network,
  ShieldCheck, FileDown, ChevronDown, NotebookPen, Layers, ShieldAlert, FileText, Calculator,
} from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';
import { fetchSentencingCenter, type SentencingCenter, type OffenseSentencing, type SentencingCitation } from '../../services/sentencingApi';

const SECTIONS = [
  { id: 'dashboard', label: 'Dashboard', icon: Layers },
  { id: 'offenses', label: 'Offense Sentencing', icon: Scale },
  { id: 'enhancements', label: 'Enhancements', icon: ShieldAlert },
  { id: 'defenses', label: 'Defenses', icon: ShieldCheck },
  { id: 'exposure', label: 'Criminal Exposure', icon: Calculator },
  { id: 'authorities', label: 'Authorities', icon: Landmark },
  { id: 'graph', label: 'Knowledge Graph', icon: Network },
  { id: 'review', label: 'Attorney Review', icon: ShieldCheck },
  { id: 'notes', label: 'Notes', icon: NotebookPen },
];

function isUnknown(v: string | null | undefined): boolean {
  return !v || v === 'UNKNOWN' || v.startsWith('UNKNOWN');
}
function U({ v }: { v: string }) {
  return isUnknown(v) ? <span className="text-amber-400 font-medium">UNKNOWN</span> : <span className="text-slate-100">{v}</span>;
}
function Chips({ items }: { items: SentencingCitation[] }) {
  if (!items || items.length === 0) return null;
  return (
    <span className="inline-flex flex-wrap gap-1 ml-1 align-middle">
      {items.slice(0, 6).map((c, i) => (
        <span key={i} className="text-[10px] px-1.5 py-0.5 rounded bg-navy-700/70 border border-white/10 text-slate-300 font-mono">{c.type}:{(c.label ?? c.id).slice(0, 18)}</span>
      ))}
    </span>
  );
}
function Section({ id, title, icon: Icon, meta, children }: { id: string; title: string; icon: React.ElementType; meta?: string; children: React.ReactNode }) {
  return (
    <section id={id} className="report-section scroll-mt-24 ca-panel p-6 md:p-8">
      <div className="flex items-center justify-between gap-4 border-b border-white/10 pb-4 mb-6">
        <div className="flex items-center gap-3">
          <span className="w-11 h-11 rounded-xl ca-gradient-gold flex items-center justify-center text-navy shadow-gold"><Icon className="w-5 h-5" /></span>
          <h2 className="text-xl md:text-2xl font-bold text-slate-50 tracking-tight">{title}</h2>
        </div>
        {meta && <span className="text-xs text-slate-400 font-medium hidden md:inline">{meta}</span>}
      </div>
      {children}
    </section>
  );
}
function esc(s: string): string { return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function downloadDoc(title: string, bodyHtml: string, caseId: string, c: SentencingCenter) {
  const html = `<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>${esc(title)}</title></head>
<body style="font-family:'Times New Roman',serif;font-size:12pt;color:#000;">
<div style="text-align:center;margin-bottom:14pt;"><div style="font-weight:bold;letter-spacing:1pt;">COURTACCESS</div><div style="font-size:9pt;color:#555;">TRUTH · EVIDENCE · JUSTICE</div></div>
<h1 style="font-size:15pt;text-align:center;">${esc(title)}</h1>
<p style="font-size:10pt;">${esc(c.header.caseTitle)} · Case No. ${esc(c.header.caseNumber)} · ${esc(c.header.court)}</p>
<p style="font-size:8pt;color:#555;">Repository ${esc(c.header.repositoryVersion)} · Hash ${esc(c.reproducibilityHash.slice(0, 24))}… · Generated ${esc(new Date(c.header.generatedAt).toLocaleString())}</p>
<hr/>${bodyHtml}<hr/>
<p style="font-size:8pt;color:#777;">Generated by CourtAccess Sentencing Intelligence Center v${esc(c.sentencingVersion)}. Classification and penalty provisions are repository-backed; structured terms and numeric exposure are UNKNOWN and not estimated. Not legal advice.</p>
</body></html>`;
  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${title.replace(/[^a-z0-9]+/gi, '_')}_${caseId.slice(0, 8)}.doc`; a.click();
  URL.revokeObjectURL(url);
}

export function SentencingCenterPage() {
  const { caseId } = useParams<{ caseId: string }>();
  const [center, setCenter] = useState<SentencingCenter | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [notes, setNotes] = useState('');
  const [exportOpen, setExportOpen] = useState(false);
  const notesKey = useMemo(() => `ca-sentencing-notes-${caseId}`, [caseId]);

  const load = async () => {
    if (!caseId) return;
    setLoading(true);
    try { setCenter(await fetchSentencingCenter(caseId)); setError(null); }
    catch (e) { setError(e instanceof Error ? e.message : 'Failed to load Sentencing center'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [caseId]);
  useEffect(() => { setNotes(localStorage.getItem(notesKey) ?? ''); }, [notesKey]);
  const saveNotes = (v: string) => { setNotes(v); localStorage.setItem(notesKey, v); };

  if (loading) return <div className="flex flex-col items-center justify-center py-32 gap-3 text-slate-400"><Loader2 className="w-8 h-8 animate-spin text-gold-light" /><p>Assembling repository-backed sentencing intelligence…</p></div>;
  if (error || !center) return <div className="flex flex-col items-center justify-center py-32 gap-4 text-center"><AlertTriangle className="w-10 h-10 text-amber-400" /><p className="text-slate-300">{error ?? 'No sentencing data.'}</p><Button onClick={() => void load()} variant="secondary"><RefreshCw className="w-4 h-4 mr-2" />Retry</Button></div>;

  const h = center.header;
  const db = center.dashboard;
  const metrics = [
    { l: 'Charges', v: db.chargeCount }, { l: 'Felonies', v: db.felonies }, { l: 'Misdemeanors', v: db.misdemeanors },
    { l: 'Wobblers', v: db.wobblers }, { l: 'Enhancements Referenced', v: db.enhancementsReferenced }, { l: 'Unknown Classification', v: db.unknownClassification },
  ];

  const exportNotebook = () => {
    const off = center.offenses.map((o) => `<h2 style="font-size:13pt;">${esc(o.code)} ${esc(o.section)} — ${esc(o.offenseTitle)}</h2><p><b>Classification:</b> ${esc(o.classification)} · <b>Wobbler:</b> ${o.isWobbler ? 'yes' : 'no'}</p><p><b>Penalty provision (repository):</b> ${esc(o.penaltyProvision)}</p><p style="font-size:9pt;color:#555;">Lower/Middle/Upper terms, mandatory minimums: UNKNOWN (not in repository).</p>`).join('');
    const enh = `<h2 style="font-size:13pt;">Enhancements</h2><ul>${center.enhancements.map((e) => `<li>${esc(e.category)}: ${esc(e.status)}${e.status !== 'UNKNOWN' ? ' — ' + esc(e.detail) : ''}</li>`).join('')}</ul>`;
    const exp = `<h2 style="font-size:13pt;">Criminal Exposure</h2><p><b>Minimum:</b> ${esc(center.exposure.minimum)} · <b>Maximum:</b> ${esc(center.exposure.maximum)}</p><p style="font-size:9pt;color:#555;">${esc(center.exposure.note)}</p>`;
    const nn = notes.trim() ? `<h2 style="font-size:13pt;">Attorney Notes</h2><p style="white-space:pre-wrap;">${esc(notes)}</p>` : '';
    downloadDoc('Sentencing Notebook', off + enh + exp + nn, caseId!, center); setExportOpen(false);
  };
  const exportExposure = () => {
    const rows = center.exposure.penaltyProvisions.map((p) => `<tr><td>${esc(p.charge)}</td><td>${esc(p.provision)}</td></tr>`).join('');
    const body = `<p><b>Minimum:</b> ${esc(center.exposure.minimum)} · <b>Maximum:</b> ${esc(center.exposure.maximum)}</p><p style="font-size:9pt;color:#555;">${esc(center.exposure.note)}</p>` + (center.exposure.penaltyProvisions.length ? `<table border="1" cellpadding="4" style="border-collapse:collapse;width:100%;font-size:10pt;"><tr><th>Charge</th><th>Repository Penalty Provision</th></tr>${rows}</table>` : '<p style="color:#b45309;">UNKNOWN — no repository penalty provisions.</p>');
    downloadDoc('Exposure Summary', body, caseId!, center); setExportOpen(false);
  };
  const exportEnhancements = () => {
    const rows = center.enhancements.map((e) => `<tr><td>${esc(e.category)}</td><td>${esc(e.status)}</td><td>${esc(e.detail)}</td></tr>`).join('');
    downloadDoc('Enhancement Summary', `<table border="1" cellpadding="4" style="border-collapse:collapse;width:100%;font-size:10pt;"><tr><th>Enhancement</th><th>Status</th><th>Repository Reference</th></tr>${rows}</table>`, caseId!, center); setExportOpen(false);
  };

  return (
    <div className="report-root max-w-6xl mx-auto pb-16">
      <div className="report-cover hidden print:block mb-8">
        <div className="text-3xl font-bold tracking-tight">CourtAccess</div>
        <div className="ca-overline mt-1">Truth · Evidence · Justice</div>
        <h1 className="text-4xl font-bold mt-8">Sentencing & Criminal Exposure</h1>
        <p className="text-lg mt-2">{h.caseTitle} · {h.caseNumber}</p>
        <p className="text-sm mt-6 text-slate-600">{h.court} · Judge {h.judge}</p>
        <p className="text-xs mt-1 text-slate-500 font-mono">Repository {h.repositoryVersion} · Hash {center.reproducibilityHash.slice(0, 28)}…</p>
      </div>

      <div className="print:hidden mb-6">
        <Link to={`/cases/${caseId}/overview`} className="inline-flex items-center gap-1.5 text-sm text-slate-400 hover:text-gold-light mb-4"><ArrowLeft className="w-4 h-4" /> Back to case overview</Link>
        <div className="ca-panel p-6 md:p-8 relative overflow-hidden">
          <div className="absolute inset-0 ca-gradient-gold opacity-[0.06] pointer-events-none" />
          <div className="relative flex flex-col lg:flex-row lg:items-center justify-between gap-6">
            <div className="min-w-0">
              <div className="ca-overline">Sentencing & Exposure Intelligence · v{center.sentencingVersion}</div>
              <h1 className="text-2xl md:text-3xl font-bold text-slate-50 mt-1 tracking-tight flex items-center gap-3"><Scale className="w-7 h-7 text-gold-light" /> {h.caseTitle}</h1>
              <div className="flex flex-wrap items-center gap-2 mt-3">
                <Badge variant="gold">{h.caseNumber}</Badge>
                <Badge variant="navy">{db.chargeCount} charge(s)</Badge>
                <span className="text-xs text-slate-400">Generated {new Date(h.generatedAt).toLocaleString()}</span>
              </div>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0 relative">
              <Button variant="secondary" onClick={() => void load()}><RefreshCw className="w-4 h-4 mr-2" />Regenerate</Button>
              <div className="relative">
                <Button variant="secondary" onClick={() => setExportOpen((o) => !o)}><FileDown className="w-4 h-4 mr-2" />DOCX<ChevronDown className="w-3 h-3 ml-1" /></Button>
                {exportOpen && (
                  <div className="absolute right-0 mt-1 w-52 rounded-xl bg-navy-800 border border-white/10 shadow-xl z-20 py-1">
                    <button onClick={exportNotebook} className="w-full text-left px-3 py-2 text-sm text-slate-200 hover:bg-white/5">Sentencing Notebook</button>
                    <button onClick={exportExposure} className="w-full text-left px-3 py-2 text-sm text-slate-200 hover:bg-white/5">Exposure Summary</button>
                    <button onClick={exportEnhancements} className="w-full text-left px-3 py-2 text-sm text-slate-200 hover:bg-white/5">Enhancement Summary</button>
                  </div>
                )}
              </div>
              <Button variant="primary" onClick={() => window.print()}><Printer className="w-4 h-4 mr-2" />PDF / Print</Button>
            </div>
          </div>
        </div>
      </div>

      <nav className="report-toc ca-panel p-5 mb-8 print:hidden">
        <div className="ca-overline mb-3">Sentencing Command Center</div>
        <div className="flex flex-wrap gap-2">
          {SECTIONS.map((s) => (
            <a key={s.id} href={`#${s.id}`} className="inline-flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-lg bg-navy-800/50 border border-white/5 text-slate-300 hover:text-gold-light hover:border-gold-light/30 transition-colors"><s.icon className="w-3.5 h-3.5" />{s.label}</a>
          ))}
        </div>
      </nav>

      <div className="space-y-6">
        <Section id="dashboard" title="Sentencing Dashboard" icon={Layers} meta={`Repository ${h.repositoryVersion}`}>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
            {metrics.map((m) => (
              <div key={m.l} className="rounded-xl bg-navy-800/50 border border-white/5 px-4 py-3 text-center">
                <div className="text-2xl font-bold text-gold-light">{m.v}</div>
                <div className="ca-overline text-[10px] mt-1">{m.l}</div>
              </div>
            ))}
          </div>
          <p className="text-xs text-amber-400/80 mt-3">Repository coverage: {center.attorneyReview.repositoryCoverage}. Structured sentencing terms and numeric exposure are not present in the repository and are shown as UNKNOWN — never estimated.</p>
          <div className="flex flex-wrap gap-2 mt-4 print:hidden">
            <Link to={`/cases/${caseId}/calcrim`} className="text-sm text-gold-light hover:underline inline-flex items-center gap-1.5"><Scale className="w-4 h-4" />CALCRIM</Link>
            <span className="text-slate-600">·</span>
            <Link to={`/cases/${caseId}/motions`} className="text-sm text-gold-light hover:underline inline-flex items-center gap-1.5"><Gavel className="w-4 h-4" />Motion Builder</Link>
            <span className="text-slate-600">·</span>
            <Link to={`/cases/${caseId}/report`} className="text-sm text-gold-light hover:underline inline-flex items-center gap-1.5"><FileText className="w-4 h-4" />Attorney Report</Link>
          </div>
        </Section>

        {/* Offense Sentencing */}
        <Section id="offenses" title="Offense Sentencing" icon={Scale} meta={`${center.offenses.length} charge(s)`}>
          {center.offenses.length === 0 ? (
            <p className="text-sm text-amber-400/80 italic">No charges recorded — offense sentencing is UNKNOWN.</p>
          ) : (
            <div className="space-y-4">
              {center.offenses.map((o: OffenseSentencing) => (
                <div key={o.chargeId} className="report-charge rounded-2xl border border-white/10 bg-navy-800/40 p-5">
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div>
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-lg font-bold text-slate-50">{o.code} {o.section}</span>
                        {o.isFelony && <Badge variant="danger">FELONY</Badge>}
                        {o.isMisdemeanor && <Badge variant="amber">MISDEMEANOR</Badge>}
                        {o.isInfraction && <Badge variant="slate">INFRACTION</Badge>}
                        {o.isWobbler && <Badge variant="gold">WOBBLER</Badge>}
                        {o.classification === 'UNKNOWN' && <Badge variant="slate">CLASS UNKNOWN</Badge>}
                      </div>
                      <div className="text-sm text-slate-300 mt-1"><U v={o.offenseTitle} /></div>
                    </div>
                    <Badge variant="navy">{o.repositoryConfidence}</Badge>
                  </div>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3">
                    <KV label="Classification" v={o.classification} />
                    <KV label="Repository Offense ID" v={o.offenseId ?? 'UNKNOWN'} />
                    <KV label="Straight / Wobbler" v={o.isWobbler ? 'Wobbler' : o.isStraight ? 'Straight' : 'UNKNOWN'} />
                    <KV label="Classification Confidence" v={o.classificationConfidence} />
                  </div>
                  <div className="mt-3 rounded-lg bg-navy-900/40 px-3 py-2">
                    <div className="ca-overline text-[10px] mb-1">Repository Penalty Provision</div>
                    <div className="text-sm"><U v={o.penaltyProvision} /></div>
                    <Chips items={o.citations} />
                  </div>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3">
                    <KV label="Lower Term" v={o.lowerTerm} />
                    <KV label="Middle Term" v={o.middleTerm} />
                    <KV label="Upper Term" v={o.upperTerm} />
                    <KV label="Mandatory Minimum" v={o.mandatoryMinimum} />
                    <KV label="Probation Eligibility" v={o.probationEligibility} />
                    <KV label="Diversion Eligibility" v={o.diversionEligibility} />
                    <KV label="Alternative Sentencing" v={o.alternativeSentencing} />
                  </div>
                </div>
              ))}
            </div>
          )}
        </Section>

        {/* Enhancements */}
        <Section id="enhancements" title="Enhancement Analysis" icon={ShieldAlert} meta={`${center.dashboard.enhancementsReferenced} referenced`}>
          <p className="text-xs text-slate-400 mb-3">Enhancements are flagged only where referenced in repository text; each is cited. Absence of a reference is shown as UNKNOWN, not "not applicable."</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {center.enhancements.map((e) => (
              <div key={e.category} className={`rounded-xl border px-4 py-3 ${e.status === 'repository-referenced' ? 'bg-navy-800/50 border-white/10' : 'bg-navy-900/30 border-white/5'}`}>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-semibold text-slate-100">{e.category}</span>
                  <Badge variant={e.status === 'repository-referenced' ? 'emerald' : 'slate'}>{e.status === 'repository-referenced' ? 'REFERENCED' : 'UNKNOWN'}</Badge>
                </div>
                {e.status === 'repository-referenced' && <div className="text-xs text-slate-400 mt-1">{e.detail}<Chips items={e.citations} /></div>}
              </div>
            ))}
          </div>
        </Section>

        {/* Defenses */}
        <Section id="defenses" title="Defense Analysis" icon={ShieldCheck}>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <DefenseCol title="Known Defenses" items={center.defenseAnalysis.defenses} />
            <DefenseCol title="Known Exceptions" items={center.defenseAnalysis.exceptions} />
            <DefenseCol title="Known Immunities" items={center.defenseAnalysis.immunities} />
          </div>
        </Section>

        {/* Criminal Exposure */}
        <Section id="exposure" title="Criminal Exposure" icon={Calculator}>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <KV label="Minimum Exposure" v={center.exposure.minimum} />
            <KV label="Maximum Exposure" v={center.exposure.maximum} />
            <KV label="Repository Confidence" v={center.exposure.repositoryConfidence} />
            <KV label="Mandatory Terms" v={center.exposure.mandatoryTerms.length ? center.exposure.mandatoryTerms.join('; ') : 'UNKNOWN'} />
          </div>
          <div className="mt-3 rounded-xl bg-amber-500/5 border border-amber-500/20 px-4 py-3">
            <div className="ca-overline text-[10px] text-amber-400 mb-1">Exposure Governance</div>
            <p className="text-xs text-slate-300">{center.exposure.note}</p>
          </div>
          {center.exposure.penaltyProvisions.length > 0 && (
            <div className="mt-4">
              <div className="ca-overline text-[10px] mb-2">Repository-Backed Penalty Provisions</div>
              <div className="space-y-2">
                {center.exposure.penaltyProvisions.map((p, i) => (
                  <div key={i} className="text-sm rounded-lg bg-navy-800/40 border border-white/5 px-3 py-2"><span className="text-gold-light font-medium">{p.charge}</span> — <span className="text-slate-200">{p.provision}</span><Chips items={p.citations} /></div>
                ))}
              </div>
            </div>
          )}
        </Section>

        {/* Authorities */}
        <Section id="authorities" title="Authority Panel" icon={Landmark}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <div className="ca-overline text-[10px] mb-2">California Statutes</div>
              {center.authorities.statutes.length === 0 ? <span className="text-xs text-amber-400/80 italic">UNKNOWN — no repository match</span> : (
                <ul className="text-sm text-slate-200 space-y-1">{center.authorities.statutes.map((s, i) => <li key={i}>{s.code} {s.section} — {s.title}</li>)}</ul>
              )}
            </div>
            <div>
              <div className="ca-overline text-[10px] mb-2">CALCRIM References</div>
              {center.authorities.calcrim.length === 0 ? <span className="text-xs text-amber-400/80 italic">UNKNOWN — none linked</span> : (
                <ul className="text-sm text-slate-200 space-y-1">{center.authorities.calcrim.map((c, i) => <li key={i}>{c.instructionNumber} — {c.title}</li>)}</ul>
              )}
            </div>
          </div>
          <div className="mt-4">
            <div className="ca-overline text-[10px] mb-2">Provider Availability</div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
              {center.authorities.providerAvailability.map((p, i) => (
                <div key={i} className="flex items-center justify-between text-sm rounded-lg bg-navy-800/40 px-3 py-2 border border-white/5"><span className="text-slate-300">{p.provider}</span><span className={isUnknown(p.status) ? 'text-amber-400' : 'text-slate-200'}>{p.status}</span></div>
              ))}
            </div>
          </div>
        </Section>

        {/* Knowledge Graph */}
        <Section id="graph" title="Knowledge Graph" icon={Network} meta={`status: ${center.knowledgeGraph.status}`}>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-2xl font-bold text-gold-light">{center.knowledgeGraph.nodeCount}</div><div className="ca-overline text-[10px] mt-1">Nodes</div></div>
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-2xl font-bold text-gold-light">{center.knowledgeGraph.edgeCount}</div><div className="ca-overline text-[10px] mt-1">Edges</div></div>
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-2xl font-bold text-gold-light">{center.knowledgeGraph.byType['charge'] ?? 0}</div><div className="ca-overline text-[10px] mt-1">Charge Nodes</div></div>
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-sm font-bold text-slate-100 mt-1.5">{center.knowledgeGraph.status}</div><div className="ca-overline text-[10px] mt-1">Status</div></div>
          </div>
          <Link to={`/cases/${caseId}/knowledge-graph`} className="print:hidden inline-flex items-center gap-1.5 text-sm text-gold-light hover:underline mt-4"><Network className="w-4 h-4" />Open interactive knowledge graph</Link>
        </Section>

        {/* Attorney Review */}
        <Section id="review" title="Attorney Review" icon={ShieldCheck}>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
            <KV label="Repository Coverage" v={center.attorneyReview.repositoryCoverage} />
            <KV label="Unknown Exposure" v={center.attorneyReview.unknownExposure ? 'yes' : 'no'} />
          </div>
          <ReviewGroup title="Incomplete Sentencing Data" items={center.attorneyReview.incompleteSentencingData} tone="slate" />
          <ReviewGroup title="Repository Gaps" items={center.attorneyReview.repositoryGaps} tone="slate" />
          <ReviewGroup title="Manual Review Required" items={center.attorneyReview.manualReviewRequired} tone="amber" />
          <p className="text-xs text-slate-500 mt-3">All sentencing exposure, enhancement applicability, and prior-conviction consequences must be computed and verified by counsel. The platform never fabricates sentencing, priors, or strike consequences.</p>
        </Section>

        {/* Notes */}
        <Section id="notes" title="Attorney Notes" icon={NotebookPen}>
          <div className="print:hidden">
            <textarea value={notes} onChange={(e) => saveNotes(e.target.value)} placeholder="Sentencing strategy, exposure computations, mitigation…" className="w-full h-40 rounded-xl bg-navy-900/50 border border-white/10 px-3 py-2 text-sm text-slate-100 focus:border-gold-light/50 focus:outline-none resize-none" />
            <p className="text-[11px] text-slate-500 mt-2">Private to your browser · included in Sentencing Notebook DOCX export.</p>
          </div>
          {notes.trim() && <div className="hidden print:block"><p className="text-sm whitespace-pre-wrap">{notes}</p></div>}
        </Section>
      </div>

      <p className="report-footer text-center text-xs text-slate-500 mt-10">
        CourtAccess · Sentencing Intelligence Center v{center.sentencingVersion} · Classification & penalty provisions repository-backed · Exposure never estimated · Not legal advice
      </p>
    </div>
  );
}

function KV({ label, v }: { label: string; v: string }) {
  return (
    <div className="rounded-xl bg-navy-800/50 border border-white/5 px-3 py-2">
      <div className="ca-overline text-[10px]">{label}</div>
      <div className="text-sm mt-0.5"><U v={v} /></div>
    </div>
  );
}
function DefenseCol({ title, items }: { title: string; items: Array<{ text: string; citations: SentencingCitation[] }> }) {
  return (
    <div>
      <div className="ca-overline text-[10px] mb-2">{title} <span className="text-slate-500">({items.length})</span></div>
      {items.length === 0 ? <span className="text-xs text-amber-400/80 italic">UNKNOWN — none in repository</span> : (
        <ul className="space-y-1.5">{items.slice(0, 12).map((it, i) => <li key={i} className="text-xs rounded-lg bg-navy-800/40 border border-white/5 px-2.5 py-1.5 text-slate-200">{it.text}<Chips items={it.citations} /></li>)}</ul>
      )}
    </div>
  );
}
function ReviewGroup({ title, items, tone }: { title: string; items: string[]; tone: 'amber' | 'slate' }) {
  return (
    <div className="mb-4">
      <div className="ca-overline text-[10px] mb-2">{title} <span className="text-slate-500">({items.length})</span></div>
      {items.length === 0 ? <p className="text-xs text-slate-500 italic">None.</p> : (
        <ul className="space-y-1">{items.map((it, i) => <li key={i} className={`text-xs rounded-lg px-3 py-2 border ${tone === 'amber' ? 'bg-amber-500/5 border-amber-500/20 text-slate-200' : 'bg-navy-800/40 border-white/5 text-slate-300'}`}>{it}</li>)}</ul>
      )}
    </div>
  );
}
