// ============================================================================
// CourtAccess — Canonical Voir Dire Intelligence Center (Program 92)
// The attorney's jury-selection workspace. The question library and challenge
// framework are repository-derived and authority-cited. Juror evaluations and
// challenge selections are ATTORNEY-ENTERED (client-persisted) — the platform
// never infers or fabricates juror bias, opinions, or strategy. UNKNOWN is
// shown wherever repository evidence is insufficient. Export: Print/PDF, DOCX.
// ============================================================================

import { useEffect, useMemo, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  Loader2, Printer, RefreshCw, AlertTriangle, ArrowLeft, Users, BookOpen, Gavel, Landmark,
  Network, ShieldCheck, FileDown, ChevronDown, Search, Plus, Trash2, NotebookPen, FileText, Scale,
} from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';
import {
  fetchVoirDireCenter, type VoirDireCenter, type VoirDireCitation, type JurorRecord, type ChallengeRecord,
} from '../../services/voirDireApi';

const SECTIONS = [
  { id: 'dashboard', label: 'Dashboard', icon: Scale },
  { id: 'questions', label: 'Question Library', icon: BookOpen },
  { id: 'jurors', label: 'Juror Workspace', icon: Users },
  { id: 'challenges', label: 'Challenge Workspace', icon: Gavel },
  { id: 'authorities', label: 'Authorities', icon: Landmark },
  { id: 'graph', label: 'Knowledge Graph', icon: Network },
  { id: 'review', label: 'Attorney Review', icon: ShieldCheck },
  { id: 'notes', label: 'Notes', icon: NotebookPen },
];

function isUnknown(v: string | null | undefined): boolean {
  return !v || v === 'UNKNOWN' || v.startsWith('UNKNOWN');
}

function Chips({ items }: { items: VoirDireCitation[] }) {
  if (!items || items.length === 0) return null;
  return (
    <span className="inline-flex flex-wrap gap-1 ml-1 align-middle">
      {items.slice(0, 6).map((c, i) => (
        <span key={i} className="text-[10px] px-1.5 py-0.5 rounded bg-navy-700/70 border border-white/10 text-slate-300 font-mono">{c.type}:{(c.label ?? c.id).slice(0, 18)}</span>
      ))}
      {items.length > 6 && <span className="text-[10px] text-slate-500">+{items.length - 6}</span>}
    </span>
  );
}

function Section({ id, title, icon: Icon, meta, children }: { id: string; title: string; icon: React.ElementType; meta?: string; children: React.ReactNode }) {
  return (
    <section id={id} className="report-section scroll-mt-24 ca-panel p-6 md:p-8">
      <div className="flex items-center justify-between gap-4 border-b border-white/10 pb-4 mb-6">
        <div className="flex items-center gap-3">
          <span className="w-11 h-11 rounded-xl ca-gradient-gold flex items-center justify-center text-navy shadow-gold"><Icon className="w-5 h-5" /></span>
          <h2 className="text-xl md:text-2xl font-bold text-slate-50 tracking-tight">{title}</h2>
        </div>
        {meta && <span className="text-xs text-slate-400 font-medium hidden md:inline">{meta}</span>}
      </div>
      {children}
    </section>
  );
}

function esc(s: string): string {
  return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function downloadDoc(title: string, bodyHtml: string, caseId: string, c: VoirDireCenter) {
  const html = `<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>${esc(title)}</title></head>
<body style="font-family:'Times New Roman',serif;font-size:12pt;color:#000;">
<div style="text-align:center;margin-bottom:14pt;"><div style="font-weight:bold;letter-spacing:1pt;">COURTACCESS</div><div style="font-size:9pt;color:#555;">TRUTH · EVIDENCE · JUSTICE</div></div>
<h1 style="font-size:15pt;text-align:center;">${esc(title)}</h1>
<p style="font-size:10pt;">${esc(c.header.caseTitle)} · Case No. ${esc(c.header.caseNumber)} · ${esc(c.header.court)}</p>
<p style="font-size:8pt;color:#555;">Repository ${esc(c.header.repositoryVersion)} · Hash ${esc(c.reproducibilityHash.slice(0, 24))}… · Generated ${esc(new Date(c.header.generatedAt).toLocaleString())}</p>
<hr/>${bodyHtml}<hr/>
<p style="font-size:8pt;color:#777;">Generated by CourtAccess Voir Dire Intelligence Center v${esc(c.voirDireVersion)}. The question library is repository-backed; juror evaluations are attorney-entered. Items marked UNKNOWN require attorney verification. Not legal advice.</p>
</body></html>`;
  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${title.replace(/[^a-z0-9]+/gi, '_')}_${caseId.slice(0, 8)}.doc`; a.click();
  URL.revokeObjectURL(url);
}

const uid = () => Math.random().toString(36).slice(2, 10);

export function VoirDirePage() {
  const { caseId } = useParams<{ caseId: string }>();
  const [center, setCenter] = useState<VoirDireCenter | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [notes, setNotes] = useState('');
  const [jurors, setJurors] = useState<JurorRecord[]>([]);
  const [challenges, setChallenges] = useState<ChallengeRecord[]>([]);
  const [exportOpen, setExportOpen] = useState(false);

  const notesKey = useMemo(() => `ca-voirdire-notes-${caseId}`, [caseId]);
  const jurorsKey = useMemo(() => `ca-voirdire-jurors-${caseId}`, [caseId]);
  const challengesKey = useMemo(() => `ca-voirdire-challenges-${caseId}`, [caseId]);

  const load = async () => {
    if (!caseId) return;
    setLoading(true);
    try { setCenter(await fetchVoirDireCenter(caseId)); setError(null); }
    catch (e) { setError(e instanceof Error ? e.message : 'Failed to load Voir Dire center'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [caseId]);
  useEffect(() => {
    setNotes(localStorage.getItem(notesKey) ?? '');
    try { setJurors(JSON.parse(localStorage.getItem(jurorsKey) ?? '[]')); } catch { setJurors([]); }
    try { setChallenges(JSON.parse(localStorage.getItem(challengesKey) ?? '[]')); } catch { setChallenges([]); }
  }, [notesKey, jurorsKey, challengesKey]);

  const saveNotes = (v: string) => { setNotes(v); localStorage.setItem(notesKey, v); };
  const saveJurors = (j: JurorRecord[]) => { setJurors(j); localStorage.setItem(jurorsKey, JSON.stringify(j)); };
  const saveChallenges = (c: ChallengeRecord[]) => { setChallenges(c); localStorage.setItem(challengesKey, JSON.stringify(c)); };

  const addJuror = () => saveJurors([...jurors, { id: uid(), jurorNumber: String(jurors.length + 1), seatNumber: '', notes: '', observedResponses: '', rating: 'unknown', concerns: '' }]);
  const updateJuror = (id: string, patch: Partial<JurorRecord>) => saveJurors(jurors.map((j) => (j.id === id ? { ...j, ...patch } : j)));
  const removeJuror = (id: string) => saveJurors(jurors.filter((j) => j.id !== id));
  const addChallenge = (type: 'cause' | 'peremptory') => saveChallenges([...challenges, { id: uid(), jurorRef: '', type, notes: '' }]);
  const updateChallenge = (id: string, patch: Partial<ChallengeRecord>) => saveChallenges(challenges.map((c) => (c.id === id ? { ...c, ...patch } : c)));
  const removeChallenge = (id: string) => saveChallenges(challenges.filter((c) => c.id !== id));

  const filteredCategories = useMemo(() => {
    if (!center) return [];
    const qq = query.trim().toLowerCase();
    if (!qq) return center.questionLibrary;
    return center.questionLibrary
      .map((cat) => ({ ...cat, questions: cat.questions.filter((x) => x.text.toLowerCase().includes(qq) || cat.label.toLowerCase().includes(qq)) }))
      .filter((cat) => cat.questions.length > 0 || cat.label.toLowerCase().includes(qq));
  }, [center, query]);

  if (loading) {
    return <div className="flex flex-col items-center justify-center py-32 gap-3 text-slate-400"><Loader2 className="w-8 h-8 animate-spin text-gold-light" /><p>Assembling repository-backed voir dire intelligence…</p></div>;
  }
  if (error || !center) {
    return <div className="flex flex-col items-center justify-center py-32 gap-4 text-center"><AlertTriangle className="w-10 h-10 text-amber-400" /><p className="text-slate-300">{error ?? 'No voir dire data.'}</p><Button onClick={() => void load()} variant="secondary"><RefreshCw className="w-4 h-4 mr-2" />Retry</Button></div>;
  }

  const h = center.header;
  const db = center.dashboard;
  const metrics = [
    { l: 'Question Categories', v: db.categoryCount },
    { l: 'Questions', v: db.questionCount },
    { l: 'Repository-Backed', v: db.repositoryBackedQuestions },
    { l: 'Charges', v: db.chargeCount },
    { l: 'Authorities', v: db.authorityCount },
    { l: 'Jurors Recorded', v: jurors.length },
  ];

  const exportNotebook = () => {
    const qs = center.questionLibrary.map((cat) => `<h2 style="font-size:13pt;margin:14pt 0 4pt;">${esc(cat.label)}</h2><p style="font-size:9pt;color:#555;">${esc(cat.basis)}</p><ol>${cat.questions.map((x) => `<li>${esc(x.text)}</li>`).join('')}</ol>`).join('');
    const jr = jurors.length ? `<h2 style="font-size:13pt;">Juror Notes</h2><table border="1" cellpadding="4" style="border-collapse:collapse;width:100%;font-size:10pt;"><tr><th>Juror</th><th>Seat</th><th>Rating</th><th>Notes</th><th>Concerns</th></tr>${jurors.map((j) => `<tr><td>${esc(j.jurorNumber)}</td><td>${esc(j.seatNumber)}</td><td>${esc(j.rating)}</td><td>${esc(j.notes)}</td><td>${esc(j.concerns)}</td></tr>`).join('')}</table>` : '';
    const ch = challenges.length ? `<h2 style="font-size:13pt;">Challenges</h2><ul>${challenges.map((c) => `<li>${esc(c.type)} — Juror ${esc(c.jurorRef)}: ${esc(c.notes)}</li>`).join('')}</ul>` : '';
    const nn = notes.trim() ? `<h2 style="font-size:13pt;">Attorney Notes</h2><p style="white-space:pre-wrap;">${esc(notes)}</p>` : '';
    downloadDoc('Voir Dire Notebook', qs + jr + ch + nn, caseId!, center); setExportOpen(false);
  };
  const exportJurors = () => {
    const body = jurors.length ? `<table border="1" cellpadding="4" style="border-collapse:collapse;width:100%;font-size:10pt;"><tr><th>Juror</th><th>Seat</th><th>Rating</th><th>Observed Responses</th><th>Notes</th><th>Concerns</th></tr>${jurors.map((j) => `<tr><td>${esc(j.jurorNumber)}</td><td>${esc(j.seatNumber)}</td><td>${esc(j.rating)}</td><td>${esc(j.observedResponses)}</td><td>${esc(j.notes)}</td><td>${esc(j.concerns)}</td></tr>`).join('')}</table>` : '<p style="color:#b45309;">UNKNOWN — no jurors recorded.</p>';
    downloadDoc('Juror Notes', body, caseId!, center); setExportOpen(false);
  };
  const exportQuestions = () => {
    const body = center.questionLibrary.map((cat) => `<h2 style="font-size:13pt;">${esc(cat.label)}</h2><ol>${cat.questions.map((x) => `<li>${esc(x.text)}</li>`).join('')}</ol>`).join('');
    downloadDoc('Voir Dire Question List', body, caseId!, center); setExportOpen(false);
  };

  return (
    <div className="report-root max-w-6xl mx-auto pb-16">
      {/* Print cover */}
      <div className="report-cover hidden print:block mb-8">
        <div className="text-3xl font-bold tracking-tight">CourtAccess</div>
        <div className="ca-overline mt-1">Truth · Evidence · Justice</div>
        <h1 className="text-4xl font-bold mt-8">Voir Dire Intelligence</h1>
        <p className="text-lg mt-2">{h.caseTitle} · {h.caseNumber}</p>
        <p className="text-sm mt-6 text-slate-600">{h.court} · Judge {h.judge}</p>
        <p className="text-xs mt-1 text-slate-500 font-mono">Repository {h.repositoryVersion} · Hash {center.reproducibilityHash.slice(0, 28)}…</p>
      </div>

      {/* Screen header hero */}
      <div className="print:hidden mb-6">
        <Link to={`/cases/${caseId}/overview`} className="inline-flex items-center gap-1.5 text-sm text-slate-400 hover:text-gold-light mb-4"><ArrowLeft className="w-4 h-4" /> Back to case overview</Link>
        <div className="ca-panel p-6 md:p-8 relative overflow-hidden">
          <div className="absolute inset-0 ca-gradient-gold opacity-[0.06] pointer-events-none" />
          <div className="relative flex flex-col lg:flex-row lg:items-center justify-between gap-6">
            <div className="min-w-0">
              <div className="ca-overline">Voir Dire Intelligence Center · v{center.voirDireVersion}</div>
              <h1 className="text-2xl md:text-3xl font-bold text-slate-50 mt-1 tracking-tight flex items-center gap-3"><Users className="w-7 h-7 text-gold-light" /> {h.caseTitle}</h1>
              <div className="flex flex-wrap items-center gap-2 mt-3">
                <Badge variant="gold">{h.caseNumber}</Badge>
                <Badge variant="navy">{db.questionCount} question(s)</Badge>
                <span className="text-xs text-slate-400">Generated {new Date(h.generatedAt).toLocaleString()}</span>
              </div>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0 relative">
              <Button variant="secondary" onClick={() => void load()}><RefreshCw className="w-4 h-4 mr-2" />Regenerate</Button>
              <div className="relative">
                <Button variant="secondary" onClick={() => setExportOpen((o) => !o)}><FileDown className="w-4 h-4 mr-2" />DOCX<ChevronDown className="w-3 h-3 ml-1" /></Button>
                {exportOpen && (
                  <div className="absolute right-0 mt-1 w-52 rounded-xl bg-navy-800 border border-white/10 shadow-xl z-20 py-1">
                    <button onClick={exportNotebook} className="w-full text-left px-3 py-2 text-sm text-slate-200 hover:bg-white/5">Voir Dire Notebook</button>
                    <button onClick={exportJurors} className="w-full text-left px-3 py-2 text-sm text-slate-200 hover:bg-white/5">Juror Notes</button>
                    <button onClick={exportQuestions} className="w-full text-left px-3 py-2 text-sm text-slate-200 hover:bg-white/5">Question List</button>
                  </div>
                )}
              </div>
              <Button variant="primary" onClick={() => window.print()}><Printer className="w-4 h-4 mr-2" />PDF / Print</Button>
            </div>
          </div>
        </div>
      </div>

      {/* TOC */}
      <nav className="report-toc ca-panel p-5 mb-8 print:hidden">
        <div className="ca-overline mb-3">Voir Dire Command Center</div>
        <div className="flex flex-wrap gap-2">
          {SECTIONS.map((s) => (
            <a key={s.id} href={`#${s.id}`} className="inline-flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-lg bg-navy-800/50 border border-white/5 text-slate-300 hover:text-gold-light hover:border-gold-light/30 transition-colors"><s.icon className="w-3.5 h-3.5" />{s.label}</a>
          ))}
        </div>
      </nav>

      <div className="space-y-6">
        {/* Dashboard */}
        <Section id="dashboard" title="Voir Dire Dashboard" icon={Scale} meta={`Repository ${h.repositoryVersion}`}>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
            {metrics.map((m) => (
              <div key={m.l} className="rounded-xl bg-navy-800/50 border border-white/5 px-4 py-3 text-center">
                <div className="text-2xl font-bold text-gold-light">{m.v}</div>
                <div className="ca-overline text-[10px] mt-1">{m.l}</div>
              </div>
            ))}
          </div>
          <div className="flex flex-wrap gap-2 mt-4 print:hidden">
            <Link to={`/cases/${caseId}/trial-prep`} className="text-sm text-gold-light hover:underline inline-flex items-center gap-1.5"><ShieldCheck className="w-4 h-4" />Trial Prep</Link>
            <span className="text-slate-600">·</span>
            <Link to={`/cases/${caseId}/calcrim`} className="text-sm text-gold-light hover:underline inline-flex items-center gap-1.5"><Scale className="w-4 h-4" />CALCRIM</Link>
            <span className="text-slate-600">·</span>
            <Link to={`/cases/${caseId}/report`} className="text-sm text-gold-light hover:underline inline-flex items-center gap-1.5"><FileText className="w-4 h-4" />Attorney Report</Link>
          </div>
        </Section>

        {/* Question Library */}
        <Section id="questions" title="Question Library" icon={BookOpen} meta={`${db.categoryCount} categor(ies)`}>
          <div className="relative mb-4 print:hidden">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
            <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search questions or categories…" className="w-full rounded-xl bg-navy-900/50 border border-white/10 pl-9 pr-3 py-2 text-sm text-slate-100 focus:border-gold-light/50 focus:outline-none" />
          </div>
          {filteredCategories.length === 0 ? (
            <p className="text-sm text-slate-400 italic">No questions match your search.</p>
          ) : (
            <div className="space-y-4">
              {filteredCategories.map((cat) => (
                <div key={cat.id} className="report-charge rounded-2xl border border-white/10 bg-navy-800/40 p-5">
                  <div className="flex items-center justify-between gap-3 flex-wrap">
                    <h3 className="text-base font-bold text-slate-50">{cat.label}</h3>
                    <Badge variant="emerald">repository-backed</Badge>
                  </div>
                  <p className="text-xs text-slate-400 mt-1">{cat.basis}<Chips items={cat.citations} /></p>
                  <ol className="mt-3 space-y-2 list-decimal list-inside">
                    {cat.questions.map((x) => (
                      <li key={x.id} className="text-sm text-slate-200">{x.text}<Chips items={x.citations} /></li>
                    ))}
                  </ol>
                </div>
              ))}
            </div>
          )}
        </Section>

        {/* Juror Workspace */}
        <Section id="jurors" title="Juror Workspace" icon={Users} meta={`${jurors.length} juror(s) recorded`}>
          <div className="flex items-center justify-between mb-3 print:hidden">
            <p className="text-xs text-slate-400">Juror evaluations are attorney-entered and saved in this browser. The platform never infers juror bias.</p>
            <Button size="sm" variant="secondary" onClick={addJuror}><Plus className="w-4 h-4 mr-1" />Add Juror</Button>
          </div>
          {jurors.length === 0 ? (
            <p className="text-sm text-amber-400/80 italic">No jurors recorded yet — juror evaluations are UNKNOWN until entered by counsel.</p>
          ) : (
            <div className="space-y-3">
              {jurors.map((j) => (
                <div key={j.id} className="report-charge rounded-2xl border border-white/10 bg-navy-800/40 p-4">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2 items-end">
                    <Field label="Juror #"><input value={j.jurorNumber} onChange={(e) => updateJuror(j.id, { jurorNumber: e.target.value })} className={inputCls} /></Field>
                    <Field label="Seat #"><input value={j.seatNumber} onChange={(e) => updateJuror(j.id, { seatNumber: e.target.value })} className={inputCls} /></Field>
                    <Field label="Attorney Rating">
                      <select value={j.rating} onChange={(e) => updateJuror(j.id, { rating: e.target.value as JurorRecord['rating'] })} className={inputCls}>
                        <option value="unknown">UNKNOWN</option><option value="favorable">Favorable</option><option value="neutral">Neutral</option><option value="unfavorable">Unfavorable</option>
                      </select>
                    </Field>
                    <div className="text-right print:hidden"><button onClick={() => removeJuror(j.id)} className="text-slate-500 hover:text-red-400"><Trash2 className="w-4 h-4" /></button></div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mt-2">
                    <Field label="Observed Responses"><textarea value={j.observedResponses} onChange={(e) => updateJuror(j.id, { observedResponses: e.target.value })} className={`${inputCls} h-16 resize-none`} /></Field>
                    <Field label="Notes"><textarea value={j.notes} onChange={(e) => updateJuror(j.id, { notes: e.target.value })} className={`${inputCls} h-16 resize-none`} /></Field>
                    <Field label="Potential Concerns"><textarea value={j.concerns} onChange={(e) => updateJuror(j.id, { concerns: e.target.value })} className={`${inputCls} h-16 resize-none`} /></Field>
                  </div>
                  <div className="mt-1"><Badge variant={j.rating === 'favorable' ? 'emerald' : j.rating === 'unfavorable' ? 'danger' : j.rating === 'neutral' ? 'amber' : 'slate'}>{j.rating.toUpperCase()}</Badge></div>
                </div>
              ))}
            </div>
          )}
        </Section>

        {/* Challenge Workspace */}
        <Section id="challenges" title="Challenge Workspace" icon={Gavel}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
            <div className="rounded-xl bg-navy-800/40 border border-white/5 p-4">
              <div className="ca-overline text-[10px] mb-1">Cause Challenges</div>
              <p className="text-xs text-slate-300">{center.challengeFramework.causeChallenges.guidance}</p>
              <p className="text-[11px] text-slate-500 mt-1">Authority: {center.challengeFramework.causeChallenges.authority.join('; ')}</p>
            </div>
            <div className="rounded-xl bg-navy-800/40 border border-white/5 p-4">
              <div className="ca-overline text-[10px] mb-1">Peremptory Challenges</div>
              <p className="text-xs text-slate-300">{center.challengeFramework.peremptoryChallenges.guidance}</p>
              <p className="text-[11px] text-amber-400/80 mt-1">{center.challengeFramework.peremptoryChallenges.batsonWheeler}</p>
              <p className="text-[11px] text-slate-500 mt-1">Authority: {center.challengeFramework.peremptoryChallenges.authority.join('; ')}</p>
            </div>
          </div>
          <div className="flex items-center gap-2 mb-3 print:hidden">
            <Button size="sm" variant="secondary" onClick={() => addChallenge('cause')}><Plus className="w-4 h-4 mr-1" />Cause Challenge</Button>
            <Button size="sm" variant="secondary" onClick={() => addChallenge('peremptory')}><Plus className="w-4 h-4 mr-1" />Peremptory</Button>
          </div>
          {challenges.length === 0 ? (
            <p className="text-sm text-slate-400 italic">No challenges recorded yet.</p>
          ) : (
            <div className="space-y-2">
              {challenges.map((c) => (
                <div key={c.id} className="report-charge rounded-xl border border-white/10 bg-navy-800/40 p-3 grid grid-cols-1 md:grid-cols-[120px_140px_1fr_auto] gap-2 items-end">
                  <div><Badge variant={c.type === 'cause' ? 'amber' : 'navy'}>{c.type}</Badge></div>
                  <Field label="Juror Ref"><input value={c.jurorRef} onChange={(e) => updateChallenge(c.id, { jurorRef: e.target.value })} className={inputCls} /></Field>
                  <Field label="Notes / Basis"><input value={c.notes} onChange={(e) => updateChallenge(c.id, { notes: e.target.value })} className={inputCls} /></Field>
                  <div className="print:hidden"><button onClick={() => removeChallenge(c.id)} className="text-slate-500 hover:text-red-400"><Trash2 className="w-4 h-4" /></button></div>
                </div>
              ))}
            </div>
          )}
        </Section>

        {/* Authorities */}
        <Section id="authorities" title="Authority Panel" icon={Landmark}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <div className="ca-overline text-[10px] mb-2">California Authority</div>
              {center.authorities.statutes.length === 0 ? <span className="text-xs text-amber-400/80 italic">UNKNOWN — no repository match</span> : (
                <ul className="text-sm text-slate-200 space-y-1">{center.authorities.statutes.map((s, i) => <li key={i}>{s.code} {s.section} — {s.title}</li>)}</ul>
              )}
            </div>
            <div>
              <div className="ca-overline text-[10px] mb-2">CALCRIM References</div>
              {center.authorities.calcrim.length === 0 ? <span className="text-xs text-amber-400/80 italic">UNKNOWN — none linked</span> : (
                <ul className="text-sm text-slate-200 space-y-1">{center.authorities.calcrim.map((c, i) => <li key={i}>{c.instructionNumber} — {c.title}</li>)}</ul>
              )}
            </div>
          </div>
          <div className="mt-4">
            <div className="ca-overline text-[10px] mb-2">Provider Availability</div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
              {center.authorities.providerAvailability.map((p, i) => (
                <div key={i} className="flex items-center justify-between text-sm rounded-lg bg-navy-800/40 px-3 py-2 border border-white/5"><span className="text-slate-300">{p.provider}</span><span className={isUnknown(p.status) ? 'text-amber-400' : 'text-slate-200'}>{p.status}</span></div>
              ))}
            </div>
          </div>
        </Section>

        {/* Knowledge Graph */}
        <Section id="graph" title="Knowledge Graph" icon={Network} meta={`status: ${center.knowledgeGraph.status}`}>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-2xl font-bold text-gold-light">{center.knowledgeGraph.nodeCount}</div><div className="ca-overline text-[10px] mt-1">Nodes</div></div>
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-2xl font-bold text-gold-light">{center.knowledgeGraph.edgeCount}</div><div className="ca-overline text-[10px] mt-1">Edges</div></div>
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-2xl font-bold text-gold-light">{Object.keys(center.knowledgeGraph.byType).length}</div><div className="ca-overline text-[10px] mt-1">Node Types</div></div>
            <div className="rounded-xl bg-navy-800/50 px-4 py-3 text-center"><div className="text-sm font-bold text-slate-100 mt-1.5">{center.knowledgeGraph.status}</div><div className="ca-overline text-[10px] mt-1">Status</div></div>
          </div>
          <p className="text-xs text-slate-500 mt-3">Juror and question nodes are attorney-generated during selection; the case graph provides charge, evidence, witness, and authority context.</p>
          <Link to={`/cases/${caseId}/knowledge-graph`} className="print:hidden inline-flex items-center gap-1.5 text-sm text-gold-light hover:underline mt-3"><Network className="w-4 h-4" />Open interactive knowledge graph</Link>
        </Section>

        {/* Attorney Review */}
        <Section id="review" title="Attorney Review" icon={ShieldCheck}>
          <div className="mb-4">
            <div className="ca-overline text-[10px] mb-2">Areas to Probe (case-derived) <span className="text-slate-500">({center.attorneyReview.probeAreas.length})</span></div>
            <div className="space-y-2">
              {center.attorneyReview.probeAreas.map((p) => (
                <div key={p.id} className="text-sm rounded-lg bg-navy-800/40 border border-white/5 px-3 py-2"><span className="text-slate-100">{p.area}</span> — <span className="text-slate-400 text-xs">{p.rationale}</span><Chips items={p.citations} /></div>
              ))}
            </div>
          </div>
          <ReviewGroup title="Human Review Required" items={center.attorneyReview.humanReviewRequired} tone="amber" />
          <ReviewGroup title="Incomplete Information" items={center.attorneyReview.incompleteInformation} tone="slate" />
          <div className="mb-2">
            <div className="ca-overline text-[10px] mb-2">Repository Gaps <span className="text-slate-500">({center.attorneyReview.repositoryGaps.length})</span></div>
            {center.attorneyReview.repositoryGaps.length === 0 ? <p className="text-xs text-slate-500 italic">None flagged.</p> : (
              <div className="space-y-1.5">{center.attorneyReview.repositoryGaps.map((g) => <div key={g.id} className="text-xs rounded-lg bg-navy-800/40 border border-white/5 px-3 py-2 text-slate-200">{g.value}</div>)}</div>
            )}
          </div>
          <p className="text-xs text-slate-500 mt-3">Potential bias indicators are never inferred by the platform. All juror assessments are the attorney's professional judgment.</p>
        </Section>

        {/* Notes */}
        <Section id="notes" title="Attorney Notes" icon={NotebookPen}>
          <div className="print:hidden">
            <textarea value={notes} onChange={(e) => saveNotes(e.target.value)} placeholder="Voir dire strategy, panel observations, follow-up questions…" className="w-full h-40 rounded-xl bg-navy-900/50 border border-white/10 px-3 py-2 text-sm text-slate-100 focus:border-gold-light/50 focus:outline-none resize-none" />
            <p className="text-[11px] text-slate-500 mt-2">Private to your browser · included in Voir Dire Notebook DOCX export.</p>
          </div>
          {notes.trim() && <div className="hidden print:block"><p className="text-sm whitespace-pre-wrap">{notes}</p></div>}
        </Section>
      </div>

      <p className="report-footer text-center text-xs text-slate-500 mt-10">
        CourtAccess · Voir Dire Intelligence Center v{center.voirDireVersion} · Question library repository-backed · Juror evaluations attorney-entered · Not legal advice
      </p>
    </div>
  );
}

const inputCls = 'w-full rounded-lg bg-navy-900/50 border border-white/10 px-2.5 py-1.5 text-sm text-slate-100 focus:border-gold-light/50 focus:outline-none';

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="ca-overline text-[9px] block mb-1">{label}</span>
      {children}
    </label>
  );
}

function ReviewGroup({ title, items, tone }: { title: string; items: string[]; tone: 'amber' | 'slate' }) {
  return (
    <div className="mb-4">
      <div className="ca-overline text-[10px] mb-2">{title} <span className="text-slate-500">({items.length})</span></div>
      {items.length === 0 ? <p className="text-xs text-slate-500 italic">None.</p> : (
        <ul className="space-y-1">{items.map((it, i) => <li key={i} className={`text-xs rounded-lg px-3 py-2 border ${tone === 'amber' ? 'bg-amber-500/5 border-amber-500/20 text-slate-200' : 'bg-navy-800/40 border-white/5 text-slate-300'}`}>{it}</li>)}</ul>
      )}
    </div>
  );
}
